pgsql-jp/jpug-doc

src/backend/catalog/sql_feature_packages.txt.ja
src/backend/catalog/sql_features.txt.ja

For 9.4 Japanese documents.

---

doc/src/sgml/file-fdw.sgml
doc/src/sgml/geqo.sgml
doc/src/sgml/hstore.sgml
doc/src/sgml/indexam.sgml
doc/src/sgml/lobj.sgml
doc/src/sgml/ltree.sgml
doc/src/sgml/nls.sgml
doc/src/sgml/oid2name.sgml
doc/src/sgml/passwordcheck.sgml
doc/src/sgml/pgbuffercache.sgml
doc/src/sgml/pgfreespacemap.sgml
doc/src/sgml/plhandler.sgml
doc/src/sgml/postgres.sgml

Translate into Japanese (part 2: file-fdw.sgml to postgres.sgml)

Translate into Japanese (part 2: file-fdw.sgml to postgres.sgml)

---

doc/src/sgml/bgworker.sgml

I might be a problem for the first work.

 Translate into Japanese (bgworker.sgml)

---

doc/src/sgml/bgworker.sgml

Unification of terminology.

---

doc/src/sgml/datatype.sgml

fix little TYPO

---

doc/src/sgml/ref/alter_aggregate.sgml
doc/src/sgml/ref/alter_database.sgml
doc/src/sgml/ref/begin.sgml
doc/src/sgml/ref/create_aggregate.sgml
doc/src/sgml/ref/pg_recvlogical.sgml
doc/src/sgml/ref/show.sgml

make html で openjade がエラーになっていたので修正しました。

Fix to pass 'make html' (syntax error, tabs)

---

doc/src/sgml/json.sgml

Target version 9.4.0.
Character code of this file is euc-jp. Please refer to the link. 
https://raw.githubusercontent.com/noborus/jpug-doc/translate_json/doc/src/sgml/json.sgml

translate_json

---

doc/src/sgml/queries.sgml

translate_queries

---

doc/src/sgml/plpgsql.sgml

Fix tag error and remove tabs

---

doc/src/sgml/high-availability.sgml
doc/src/sgml/logicaldecoding.sgml

Fix description about recovery conflict in section 25.5.2

---

doc/src/sgml/config.sgml

Pointed out in [jpug-doc: 4264] from Saitou-san.

Fix inconsistent translation of "huge page".

---

doc/src/sgml/release-9.1.sgml

9.1 of a translation

---

doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml

 9.0分のコピー＆ペースト

---

doc/src/sgml/release-9.0.sgml
doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml

改行、インデントの調整

---

doc/src/sgml/charset.sgml
doc/src/sgml/citext.sgml
doc/src/sgml/mvcc.sgml
doc/src/sgml/syntax.sgml

Update to 9.4.3 (part 1)

---

doc/src/sgml/logicaldecoding.sgml

No translation change is needed.

Merge typo fix in upstream.

---

doc/src/sgml/release-9.4.sgml

release-9.4.sgml の 9.4.2 と 9.4.3 を訳しました。

translate release 9.4.3 and 9.4.2

---

doc/src/sgml/ecpg.sgml
doc/src/sgml/extend.sgml
doc/src/sgml/pgcrypto.sgml
doc/src/sgml/pgupgrade.sgml

第2弾です。多少翻訳が必要だったものです。（面倒なのが残った(T_T)）

Update to 9.4.3 (part 2)

---

doc/src/sgml/release-9.0.sgml
doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml

VACUUM FULLの記述が残っていたようです。削除しました。

remove duplicate "<command>VACUUM FULL</>"

---

doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml

fix version number

---

doc/src/sgml/catalogs.sgml

高塚さんからのご指摘分([jpug-doc: 4483])の修正

fix catalog_9_4_4([jpug-doc: 4483])

---

doc/src/sgml/installation.sgml

Fix the position of the comment closing tag

---

doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml

グランド -> グラウンド

---

doc/src/sgml/runtime.sgml

fix error of xmllint  --noout --valid postgres.xml.

---

doc/src/sgml/stylesheet.css

xhtml版の見た目をhtml4版と同じになるように調整しました

Updated css the xhtml version to the same look like html4 edition

---

doc/src/sgml/datatype.sgml
doc/src/sgml/queries.sgml

jpug-doc 4534のディスカッションの内容を反映しました。

reflected "jpug-doc 4534"

---

doc/src/sgml/high-availability.sgml

レプリケーションスロットの「スロット」が抜けていた。

---

doc/src/sgml/logicaldecoding.sgml
doc/src/sgml/protocol.sgml

typo、日本語が不自然だった点、および原文と比較して気になった点を直してみました。

ロジカルデコーディング関連の文章を修正

---

.travis.yml

Test of TravisCI

---

doc/src/sgml/config.sgml

config.sgml の 9.4.5 用翻訳です。よろしくお願いします。

Translation for 9.4.5 of config.sgml.

---

doc/src/sgml/sources.sgml

sources.sgmlの9.4.5対応版です。
Travis CIの動作が変わったみたいなのでまた試しです。

update sources (9.4.5)

---

doc/src/sgml/pgstatstatements.sgml
doc/src/sgml/postgres-fdw.sgml

pgstatstatementsとpostgres-fdwを9.4.5に対応しました。

update pgstatstatements and postgres-fdw (9.4.5)

---

doc/src/sgml/storage.sgml
doc/src/sgml/textsearch.sgml

storage.sgmlとtextsearch.sgmlの9.4.5対応

update storage and textsearch (9.4.5)

---

doc/src/sgml/ref/psql-ref.sgml

原文の抜けがあったのを修正

---

doc/src/sgml/array.sgml

array.sgmlを9.4.5向けに更新しました。
（まずはお試しということでファイル一つから）

update array (9.4.5)

---

doc/src/sgml/syntax.sgml

[jpug-doc: 4072] 含有 → 包含
[jpug-doc: 4253] ？？？？？ の修正

以前の修正の漏れ＆再修正

---

doc/src/sgml/release-9.0.sgml

9.0.23の表記が誤っているままだったようですので修正PRを出しておきました。

9.0.23表記の修正

---

doc/src/sgml/xtypes.sgml

訳を少し改善しました。
あと（周辺も含めて）shouldも直しています。

fix typo in xtypes

---

doc/src/sgml/sql.sgml

見つけたので修正しました。しかしfilelist.sgmlにcurrently unused
とあるようにsql.sgmlは使用されていません。

typo修正＆タグ整合修正

---

doc/src/sgml/release-9.0.sgml
doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml

ケイマン島という島はなくてケイマン諸島だと思います。（英語も複数形になっています）
外務省のページにも
ケイマン諸島（英領）
http://www.mofa.go.jp/mofaj/area/latinamerica/kikan/caricom/gaiyo.html
とあります。

fix Cayman Island<<s>>

---

doc/src/sgml/release-8.0.sgml
doc/src/sgml/release-8.1.sgml
doc/src/sgml/release-8.2.sgml
doc/src/sgml/release-8.3.sgml
doc/src/sgml/release-9.4.sgml

昼時間規則->夏時間規則
チリが抜けている部分の修正
チリ->中国

タイムゾーン周りの修正

---

doc/src/sgml/auto-explain.sgml
doc/src/sgml/btree-gin.sgml
doc/src/sgml/charset.sgml
doc/src/sgml/datetime.sgml
doc/src/sgml/extend.sgml
doc/src/sgml/legal.sgml
doc/src/sgml/ref/alter_system.sgml
doc/src/sgml/ref/discard.sgml
doc/src/sgml/ref/explain.sgml
doc/src/sgml/ref/initdb.sgml
doc/src/sgml/ref/pg_isready.sgml
doc/src/sgml/release-7.4.sgml
doc/src/sgml/release-9.0.sgml
doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml
doc/src/sgml/sources.sgml
doc/src/sgml/spi.sgml
doc/src/sgml/xml2.sgml

Fix conflicts

---

doc/src/sgml/brin.sgml

The first translation of brin.sgml

---

doc/src/sgml/catalogs.sgml

Fix confilicts

---

doc/src/sgml/brin.sgml

First translation of brin.sgml.

---

doc/src/sgml/brin.sgml

Fix translation errors pointed out by Shinichi Matsuda.

---

doc/src/sgml/brin.sgml
doc/src/sgml/datatype.sgml
doc/src/sgml/func.sgml

brin.sgml, datatype.sgml, func.sgmlの更新分です。

RC1以降のドキュメント差分反映

---

doc/src/sgml/ref/pg_resetxlog.sgml

Reported by: Alain Laporte (#13836)

doc: pg_committs -> pg_commit_ts

---

doc/src/sgml/array.sgml
doc/src/sgml/client-auth.sgml

array.sgmlとclient-auth.sgmlをやってみました。
9.5で初なので試行錯誤していますが、できているでしょうか。

array.sgml and client-auth.sgml for 9.5

---

COPYRIGHT
doc/src/sgml/legal.sgml

Backpatch certain files through 9.1

Update copyright for 2016

---

doc/src/sgml/docguide.sgml
doc/src/sgml/external-projects.sgml

docguide.sgml とexternal-projects.sgml です。

docguide.sgml and external-projects.sgml for 9.5

---

doc/src/sgml/cube.sgml
doc/src/sgml/ecpg.sgml

cube.sgmlとecpg.sgmlです。
(extension)は迷いましたが、ひとまず「拡張」としておきます。いつか一括変換でお願いできれば。

cube.sgml and ecpg.sgml for 9.5

---

doc/src/sgml/ref/create_transform.sgml
doc/src/sgml/ref/drop_transform.sgml

"transform"は「変換」と訳しましたが、より適切な訳語があれば、他のファイルと合わせて修正します。

新機能のcreate/drop_transformの翻訳です。

---

doc/src/sgml/ref/alter_extension.sgml

transformは新機能で、訳語をどうするべきか考えましたが、取り敢えず「変換」と訳しました。
より適切な訳語があれば、他のファイルも合わせて変更します。

alter_extention.sgmlの変更部分の翻訳です。

---

doc/src/sgml/indexam.sgml
doc/src/sgml/keywords.sgml
doc/src/sgml/pgcrypto.sgml

以下のファイルの翻訳です。
indexam.sgml
keywords.sgml
pgcrypto.sgml

indexam.sgml, keywords.sgml and pgcrypto.sgml for 9.5

---

doc/src/sgml/release-8.3.sgml
doc/src/sgml/sepgsql.sgml
doc/src/sgml/xindex.sgml

release-8.3.sgml
sepgsql.sgml
xindex.sgml

release-8.3.sgml, sepgsql.sgml and xindex.sgml for 9.5.0

---

doc/src/sgml/gin.sgml
doc/src/sgml/protocol.sgml

gin.sgml and protocol.sgml for 9.5.0

---

doc/src/sgml/ref/alter_policy.sgml
doc/src/sgml/ref/create_policy.sgml
doc/src/sgml/ref/drop_policy.sgml

新機能のcreate/alter/drop_policyの翻訳です。

---

doc/src/sgml/release-8.4.sgml
doc/src/sgml/release-9.0.sgml
doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml

以下のファイル5個の9.5.0対応です。
release-8.4.sgml
release-9.[0-3].sgml

release-8.4.sgml and release-9.[0-3].sgml for 9.5.0

---

doc/src/sgml/ref/pg_dump.sgml
doc/src/sgml/ref/pg_dumpall.sgml

pg_dumpallの原文の変更は、翻訳には影響のないものでした。

pg_dump.sgml, pg_dumpall.sgmlの変更部分の翻訳です。

---

doc/src/sgml/ref/insert.sgml

insert.sgmlの訳抜けしていた部分を翻訳(jpug-doc: 4820)

---

doc/src/sgml/plpython.sgml

plpython.sgml for 9.5.0

---

doc/src/sgml/datatype.sgml

datatypeの9.5.0対応です。
representionというのが出てきますがrepresentationとみなして訳しています。
（BUG #13872として本家の方に報告しています。）

datatype.sgml for 9.5.0

---

doc/src/sgml/perform.sgml
doc/src/sgml/pgstatstatements.sgml

perform.sgml
pgstatstatements.sgml

perform.sgml and pgstatstatements.sgml for 9.5.0

---

doc/src/sgml/event-trigger.sgml
doc/src/sgml/maintenance.sgml

event-trigger.sgml
maintenance.sgml

event-trigger.sgml and maintenance.sgml for 9.5.0

---

doc/src/sgml/recovery-config.sgml

recovery-config.sgml の9.5.0対応です。

recovery-config.sgml for 9.5.0

---

doc/src/sgml/catalogs.sgml
doc/src/sgml/client-auth.sgml
doc/src/sgml/config.sgml
doc/src/sgml/contrib-spi.sgml
doc/src/sgml/datatype.sgml
doc/src/sgml/ecpg.sgml
doc/src/sgml/func.sgml
doc/src/sgml/high-availability.sgml
doc/src/sgml/information_schema.sgml
doc/src/sgml/json.sgml
doc/src/sgml/libpq.sgml
doc/src/sgml/plpgsql.sgml
doc/src/sgml/pltcl.sgml
doc/src/sgml/queries.sgml
doc/src/sgml/recovery-config.sgml
doc/src/sgml/ref/psql-ref.sgml
doc/src/sgml/rules.sgml
doc/src/sgml/runtime.sgml
doc/src/sgml/textsearch.sgml
doc/src/sgml/xfunc.sgml

revise index

---

doc/src/sgml/release-9.0.sgml
doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml

（誰もが好きな）つまらない変更
ACSTを日本語の方でも書くようにしました。
使われなくなったものだそうで、ここで頑張るのも微妙ですが、、、、

add ACST in translated sentence

---

doc/src/sgml/high-availability.sgml

翻訳の修正は無し。
REL9_5_0から削除される行(-)が無いようにした。
(+)は最小限に。

REL9_5_0との差分を減らした

---

doc/src/sgml/info.sgml

"your work or play"を「利用・操作」と訳していますが、単に「仕事や遊び」なのではないかと。

info.sgmlの軽微な誤訳修正です

---

doc/src/sgml/release-7.4.sgml

レグレッション->リグレッション

---

doc/src/sgml/release-9.3.sgml

グレゴリア->グレゴリオ

---

doc/src/sgml/func.sgml

誤訳訂正の他、意味をとりにくい表現を改善する、意味を原文に近づける、
文体を周囲の文に合わせる、などの変更を行いました。

func.sgmlのマニュアル9.9節に該当する部分の誤訳訂正と翻訳改善。

---

doc/src/sgml/config.sgml

only recognized 〜は変更行が削除されずに追加されてしまっていたようです。
Increasing this parameter〜は既に原文では削除されたエントリのようです。

config.sgml 原文にない行の削除

---

doc/src/sgml/ref/psql-ref.sgml

psql-ref.sgml 原文にない行の削除

---

doc/src/sgml/ref/pgbench.sgml

pgbench.sgml 原文との差分を減らす修正

---

doc/src/sgml/installation.sgml
doc/src/sgml/libpq.sgml
doc/src/sgml/plperl.sgml
doc/src/sgml/ref/reassign_owned.sgml
doc/src/sgml/rules.sgml
doc/src/sgml/sepgsql.sgml
doc/src/sgml/storage.sgml
doc/src/sgml/xfunc.sgml

複数ファイル 原文との差分を減らすように修正

---

doc/src/sgml/hstore.sgml

hstore.sgml の9.5.1対応です。
ついでにsoの訳が逆っぽかったので直しています。

hstore for 9.5.1

---

src/backend/catalog/sql_features.txt.ja
src/backend/utils/errcodes.txt.ja

doc/src/sgml以外のところにあって更新の必要があるファイルを更新。

Update files outside doc/src/sgml

---

doc/src/sgml/func.sgml

範囲型の演算子、関数の説明で、一部、わかりにくい部分があるので改善を図りました。

func.sgmlの9.19節に該当する部分の翻訳改善

---

README.md

README.mdがどのように表記されるかは以下のリンクから確認できます。
https://github.com/KenichiroTanaka/jpug-doc/tree/readmetest
参考：issues159
https://github.com/pgsql-jp/jpug-doc/issues/159

README.mdを作成しました(issues159)

---

doc/src/sgml/ref/update.sgml

delete extra comma

---

doc/src/sgml/backup.sgml
doc/src/sgml/charset.sgml
doc/src/sgml/config.sgml
doc/src/sgml/datatype.sgml
doc/src/sgml/dblink.sgml
doc/src/sgml/ddl.sgml
doc/src/sgml/func.sgml
doc/src/sgml/indexam.sgml
doc/src/sgml/mvcc.sgml
doc/src/sgml/pgstatstatements.sgml
doc/src/sgml/plpgsql.sgml
doc/src/sgml/ref/alter_database.sgml
doc/src/sgml/ref/alter_table.sgml
doc/src/sgml/ref/create_role.sgml
doc/src/sgml/ref/createuser.sgml
doc/src/sgml/ref/psql-ref.sgml
doc/src/sgml/ref/reindexdb.sgml
doc/src/sgml/ref/set_role.sgml
doc/src/sgml/ref/set_session_auth.sgml
doc/src/sgml/release-7.4.sgml
doc/src/sgml/release-8.0.sgml
doc/src/sgml/release-8.1.sgml
doc/src/sgml/release-8.3.sgml
doc/src/sgml/release-8.4.sgml
doc/src/sgml/release-9.4.sgml
doc/src/sgml/rowtypes.sgml
doc/src/sgml/storage.sgml
doc/src/sgml/xindex.sgml

<!--の後に余計なものがついているのを削除しました。
具体的には空白と「-」です。
（ですので、今回も当然日本語訳には影響有りません。）
誰得 第2弾 って感じですが、見つけてしまったので。

remove extra spaces and '-' after '<!--'

---

doc/src/sgml/ddl.sgml

ddl.sgml 誤変換の訂正

---

doc/src/sgml/tcn.sgml

tcnの訳の改善です。
- 文の途中での改行の削除
- 受け身の誤訳？訂正
- letterの翻訳誤り修正

improve translation of tcn

---

doc/src/sgml/stylesheet-custom.xsl

(nav-prev) 戻る -> 前へ
(nav-up) 上に戻る -> 上へ
(xref-number-and-title sect*) 「%t」-> %n. %t

docbook のデフォルトja.xmlから修正変更

---

doc/src/sgml/stylesheet.css

typo修正＆古いブラウザ対応の削除

---

doc/src/sgml/planstats.sgml

9.5.1の原文の改善をリクエストしたのが石井なので、責任を取って担当しました:-)

planstats.sgmlの9.5.2対応です。

---

doc/src/sgml/installation.sgml
doc/src/sgml/planstats.sgml
doc/src/sgml/recovery-config.sgml

下記のファイルの9.5.2対応です。
installation.sgml
planstats.sgml
recovery-config.sgml
もしかして一番乗り？

update to 9.5.2 (part 1)

---

doc/src/sgml/pgstattuple.sgml

pgstattuple.sgml分を翻訳致しました。
翻訳のPRは初めてなので、ルールに沿えていないところもあるかもれませんが、
ご確認、コメントよろしくお願いします。
今回、原文の変更が加わっていないところ 1箇所についても、
訳文の修正を加えています。(単語の訳漏れ)

pgstattuple.sgml変更分翻訳.

---

doc/src/sgml/fdwhandler.sgml

変更はちょっとだけなのですが、"outer subplan"とか、何を指しているのかも、どういう訳語が適当なのかもよくわかりませんでした。

fdwhandler.sgmlの9.5.2対応

---

doc/src/sgml/ref/insert.sgml

ref/insert.sgmlで訳し忘れている所を見つけました。

untranslated title

---

doc/src/sgml/release-9.5.sgml

  release note 9.5.2 

---

doc/src/sgml/ref/insert.sgml

Hi,
Could you apply this change which fixes a typo?
Regards,

Remove unnecessary left angle bracket.

---

doc/src/sgml/xindex.sgml

xindex.sgmlの9.5.2対応です。
[jpug-doc: 5097] BRINでのsummary で取り上げた件ですが、初志貫徹で「要約」としました。

update xindex to 9.5.2

---

doc/src/sgml/brin.sgml

fix a little typo

---

doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml

update release-9.[1-4].sgml to 9.5.2

---

doc/src/sgml/release-old.sgml

またまたrelease-oldなのですが、これは看過できないだろうという誤訳をみつけたのでPRします。
per を
…につき, ごとに
で訳した（つもり）のだと思いますが
…によって示されたとおり, に従って
で、ここでは解釈すべきかと。

fix mistranslation of 'per'

---

doc/src/sgml/config.sgml

Hi,
Could you apply this fix?
Regards,

Translate "configuration parameter" into Japanese.

---

doc/src/sgml/catalogs.sgml

変更箇所が多いように見えますが、場所の移動だけなので、すべて9.5.2からのコピペです。

catalogs.sgmlの9.5.3対応

---

doc/src/sgml/func.sgml
doc/src/sgml/func4.sgml

Issues#617 の訳抜けの訂正

---

doc/src/sgml/high-availability.sgml

Issues #619 synchronous_replication -> synchronous_commit

---

doc/src/sgml/logicaldecoding.sgml

Fix typo in logicaldecoding.sgml

---

doc/src/sgml/config.sgml

config.sgmlのタイポを修正しました

---

doc/src/sgml/information_schema.sgml

information_schema.sgmlの9.5.4対応

---

doc/src/sgml/btree-gist.sgml
doc/src/sgml/pgbuffercache.sgml

以下のファイルの9.5.4対応です。
btree-gist.sgml
pgbuffercache.sgml
btree-gist.sgmlは（英語の変更とはほとんど関係なくて）改行の追加だけです。

update for 9.5.4

---

doc/src/sgml/release-9.5.sgml

release note 9.5.4 translation

---

doc/src/sgml/regress.sgml
doc/src/sgml/release-8.4.sgml
doc/src/sgml/release-9.0.sgml
doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml
doc/src/sgml/release-9.5.sgml
doc/src/sgml/replication-origins.sgml
doc/src/sgml/rules.sgml
doc/src/sgml/runtime.sgml
doc/src/sgml/sepgsql.sgml
doc/src/sgml/sources.sgml
doc/src/sgml/spgist.sgml
doc/src/sgml/sslinfo.sgml
doc/src/sgml/storage.sgml
doc/src/sgml/syntax.sgml
doc/src/sgml/tablesample-method.sgml
doc/src/sgml/textsearch.sgml
doc/src/sgml/tsm-system-rows.sgml
doc/src/sgml/tsm-system-time.sgml
doc/src/sgml/unaccent.sgml
doc/src/sgml/user-manag.sgml
doc/src/sgml/wal.sgml
doc/src/sgml/xfunc.sgml
doc/src/sgml/xindex.sgml
doc/src/sgml/xml2.sgml
doc/src/sgml/xplang.sgml

partDのうちref/*以外をやってみました。
やり方が違うだろ、とかあったらお知らせ下さい。

resolve conflict part D (1)

---

doc/src/sgml/ref/pg_restore.sgml
doc/src/sgml/ref/pg_rewind.sgml
doc/src/sgml/ref/pg_xlogdump.sgml
doc/src/sgml/ref/pgarchivecleanup.sgml
doc/src/sgml/ref/pgbench.sgml
doc/src/sgml/ref/pgtestfsync.sgml
doc/src/sgml/ref/pgupgrade.sgml
doc/src/sgml/ref/postgres-ref.sgml
doc/src/sgml/ref/prepare.sgml
doc/src/sgml/ref/psql-ref.sgml
doc/src/sgml/ref/reassign_owned.sgml
doc/src/sgml/ref/select.sgml
doc/src/sgml/ref/set_role.sgml
doc/src/sgml/ref/truncate.sgml
doc/src/sgml/ref/update.sgml
doc/src/sgml/ref/vacuumdb.sgml

resolve conflict part D (2)

---

doc/src/sgml/ref/select.sgml

git diff REL9_6_RC1 select.sgml|grep "^-"
で変更されていました

REL9_6_RC1 との差分修正です。

---

doc/src/sgml/ddl.sgml

ddl.sgmlの9.6対応です。

---

doc/src/sgml/adminpack.sgml
doc/src/sgml/array.sgml
doc/src/sgml/docguide.sgml
doc/src/sgml/sepgsql.sgml
doc/src/sgml/syntax.sgml
doc/src/sgml/trigger.sgml
doc/src/sgml/unaccent.sgml

以下のファイルの9.6対応です。
adminpack.sgml
array.sgml
docguide.sgml
sepgsql.sgml
syntax.sgml
trigger.sgml
unaccent.sgml

update for 9.6.0 - part 2

---

doc/src/sgml/ref/alter_function.sgml
doc/src/sgml/ref/alter_index.sgml
doc/src/sgml/ref/alter_materialized_view.sgml
doc/src/sgml/ref/alter_trigger.sgml

alter_function.sgml
alter_index.sgml
alter_materialized_view.sgml
alter_trigger.sgml
の4つのALTER文で、"DEPENDS ON extension_name"句が追加されたことへの対応がメインです。

主な変更点が"depends on extension"の句であるものをまとめてPR

---

doc/src/sgml/keywords.sgml

keywords for 9.6.0

---

doc/src/sgml/ref/values.sgml

変更部分の直後に誤訳を見つけたので、それも合わせて直しました。

values.sgmlの9.6対応です。

---

doc/src/sgml/func.sgml
doc/src/sgml/func1.sgml

差分が大きいので、パーツ毎にPRを出すことにしました。
DISTINCT FROMに関する部分にマージミスがあったため、原文の一部修正と大幅削除があるように見えます。

func.sgmlの9.2節(比較演算子)に対応する部分の9.6対応です。

---

doc/src/sgml/recovery-config.sgml
doc/src/sgml/tablefunc.sgml

recovery-config.sgml
tablefunc.sgml

update recovery-config and tablefunc for 9.6.0

---

doc/src/sgml/installation.sgml
doc/src/sgml/intarray.sgml

installation.sgml
intarray.sgml

update installation and intarray to 9.6.0

---

doc/src/sgml/ref/pgarchivecleanup.sgml

pgarchivecleanup.sgmlの9.6対応です。

---

doc/src/sgml/func.sgml

変更のほとんどは、集約関数の表にPartial Modeの列を追加したものです。
Partial Modeは部分モード、Yes/Noは可・不可と訳しました。

func.sgmlの9.20節（集約関数）の9.6対応です。

---

doc/src/sgml/func.sgml
doc/src/sgml/func4.sgml

func.sgmlについては、分割して多数のPRを出しましたが、これで完了です。

func.sgmlの9.26節(システム管理関数)の9.6対応です。

---

doc/src/sgml/regress.sgml

update regress to 9.6.0

---

doc/src/sgml/fdwhandler.sgml

fdwhandler.sgml の ver.9.6変更点を翻訳

---

doc/src/sgml/pgcrypto.sgml
doc/src/sgml/storage.sgml

update pgcrypto and storage to 9.6.0

---

doc/src/sgml/monitoring.sgml

monitoring.sgmlの9.6対応（前半）です。

---

doc/src/sgml/protocol.sgml

update protocol to 9.6.0

---

doc/src/sgml/plpgsql.sgml

update plpgsql to 9.6.0

---

doc/src/sgml/rules.sgml

済みません。原文の変更部分は日本語訳に影響なかったのですが、目印に付けた★を消す作業がありました、、、、、、orz

remove place holders (rules.sgml)

---

doc/src/sgml/ref/alter_user_mapping.sgml
doc/src/sgml/ref/drop_foreign_data_wrapper.sgml
doc/src/sgml/rules.sgml

以下のファイルに★が残っているのを見つけました。
ref/alter_user_mapping.sgml
ref/drop_foreign_data_wrapper.sgml

remove place holders (ref/*)

---

doc/src/sgml/manage-ag.sgml

こちらにも★が残っていましたので、削除です。
原文は変わっていますが、he -> they なので訳には影響しません。

remove place holder

---

doc/src/sgml/func2.sgml
doc/src/sgml/func3.sgml
doc/src/sgml/func4.sgml

今回変更されたのはfunc[234].sgmlです。(func1.sgmlは変更なし)

split.shを実行してfunc.sgmlとfunc[1-4].sgmlの同期を取りました。

---

doc/src/sgml/bgworker.sgml

全体的に見直して改行を入れているため、差分が多くなってます。

bgworker.sgmlの9.6.0対応です。

---

doc/src/sgml/config.sgml
doc/src/sgml/textsearch.sgml

斉藤さんに作成いただいた一括変換　textsearch.sgml config.sgml　のみ

---

doc/src/sgml/filelist.sgml
doc/src/sgml/jpug-doc.sgml
doc/src/sgml/postgres.sgml

表記の順番はORDER BY 会社名 NULLS FIRST,お名前　の順としています。
基本コピー＆ペーストしていますが、表記に問題があればお知らせください。

9.6貢献者クレジットの初版です

---

doc/src/sgml/jpug-doc.sgml

申請からの転載時ミスを修正

---

doc/src/sgml/installation.sgml

update installtion to 9.6.1

---

doc/src/sgml/release-9.6.sgml

release-9.[1-5]対応をしていたときに見つけた9.6のささいなバグです。

fix trivial bugs

---

doc/src/sgml/release-9.6.sgml

五月雨式で済みません。9.5作業中に9.6の誤記をまた見つけました。

fix trivial typos - 2

---

doc/src/sgml/release-9.5.sgml

release-9.5の9.6.1対応です。
release-9.[1-4]はこの結果を利用するつもりです。

update release-9.5 for 9.6.1

---

doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml

release-9.[1-4].sgmlの9.6.1対応です。

update release-9.[1-4] for 9.6.1

---

doc/src/sgml/config.sgml

マージミスで残った原文の削除

---

doc/src/sgml/config.sgml
doc/src/sgml/extend.sgml
doc/src/sgml/ref/psql-ref.sgml
doc/src/sgml/tsm-system-rows.sgml

原文のコメントアウトに失敗している部分をいくつか見つけましたので対処してみました。

unintended original sentence exposure

---

doc/src/sgml/config.sgml

"Better ways to improve the quality..."の文の解釈が間違っていたので訳し直しました。
そのついでの細かな改善として、冒頭の「これらの」を、より自然で意味が明確な「以下の」に修正、次の文の「もしも」は"if"の訳として意味が強すぎるので、削除しました。

プランナメソッド設定の誤訳訂正

---

doc/src/sgml/install-windows.sgml
doc/src/sgml/pgstattuple.sgml
doc/src/sgml/syntax.sgml
doc/src/sgml/xfunc.sgml

以下のファイルの9.6.2対応です。
doc/src/sgml/install-windows.sgml
doc/src/sgml/pgstattuple.sgml
doc/src/sgml/syntax.sgml
doc/src/sgml/xfunc.sgml

update to 9.6.2

---

doc/src/sgml/Makefile
doc/src/sgml/stylesheet-common.xsl
doc/src/sgml/stylesheet-fo.xsl
doc/src/sgml/stylesheet-speedup-common.xsl
doc/src/sgml/stylesheet-speedup-xhtml.xsl
doc/src/sgml/stylesheet.xsl

stylesheet-speedup-common.xsl
stylesheet-speedup-xhtml.xsl
の追加と使用するためのincludeの追加。
日本語版で入れていた修正との調整。

Speed up XSLT builds のバックポート

---

doc/src/sgml/rules.sgml

＃まずは簡単なものから。
rules.sgmlの9.6.3対応です。

update rules.sgml to 9.6.3

---

doc/src/sgml/logicaldecoding.sgml

ほとんどがprogramlisting部分の変更で、日本語の変更が必要な部分は一箇
所だけでした。

logicaldecoding.sgmlの9.6.3対応です。

---

doc/src/sgml/config.sgml

[jpug-doc: 5329] で松田さんが指摘されていた件ですね。

config.sgmlの9.6.3対応です。

---

doc/src/sgml/installation.sgml

update installation to 9.6.3

---

doc/src/sgml/release-7.4.sgml
doc/src/sgml/release-8.0.sgml
doc/src/sgml/release-old.sgml

9.6.3対応とは関係ないのですが、古いリリースノートに気になるところを見つけたので、修正してみました。

fix old relnotes

---

doc/src/sgml/monitoring.sgml

monitoring.sgmlの9.6.3対応

---

doc/src/sgml/catalogs.sgml

catalogs.sgmlの9.6.3対応

---

doc/src/sgml/docguide.sgml

trivial fix

---

doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml

（なお、実際は 2^n × N - 6  |  n>=14  でも該当する模様だが、これは元コミットログにすら記載が無い話なので翻訳の範囲ではない）

power を「倍数」と記載していたものを「冪乗」に修正しました

---

doc/src/sgml/plpgsql.sgml

fix typos in plpgsql

---

doc/src/sgml/release-9.4.sgml

remove an extra link

---

doc/src/sgml/acronyms.sgml
doc/src/sgml/release-7.4.sgml
doc/src/sgml/release-8.0.sgml

acronyms.sgmlの964対応

---

doc/src/sgml/func1.sgml

変更は翻訳対象でない部分だけなので、マージのみでしたが、分割したファイルが更新されていなかったので、split.sh を実行しました。

func.sgmlの9.6.4対応（本体は変更なし、分割したfunc1.sgmlの更新のみ）

---

doc/src/sgml/external-projects.sgml
doc/src/sgml/installation.sgml
doc/src/sgml/plpgsql.sgml

以下のファイルの9.6.4対応です。
- external-projects.sgml
- installation.sgml
- plpgsql.sgml

update to 9.6.4 (part 6)

---

doc/src/sgml/release-9.6.sgml

release-9.[2-5]の作業の過程で気付いた、release-9.6の抜けへの対処です。

fix release-9.6 for 9.6.4

---

doc/src/sgml/config.sgml

Fixed #987

---

doc/src/sgml/catalogs.sgml

Catalogs964

---

doc/src/sgml/logicaldecoding.sgml

fix typo in logicaldecoding

---

doc/src/sgml/ref/pg_restore.sgml

fix typo in pg_restore

---

doc/src/sgml/json.sgml

version 10.0対応

---

doc/src/sgml/bloom.sgml

fix translation of 'author'

---

doc/src/sgml/docguide.sgml

docguide.sgmlの10.0対応です。
いろいろとパッサリやったのだなぁ、と言うのが内容に対する個人の感想です。

Update docguide to 10.0

---

doc/src/sgml/dfunc.sgml

Update dfunc to 10.0

---

doc/src/sgml/xml2.sgml

Update xml2 to 10.0

---

doc/src/sgml/stylesheet-custom.xsl
doc/src/sgml/stylesheet.xsl

stylesheet.xslはコメントとして残し
styhesheet-custom.xslで設定

日本語版のヘッダを独自に変更

---

doc/src/sgml/adminpack.sgml
doc/src/sgml/advanced.sgml

- adminpack.sgml
- advanced.sgml

update for 10.0 - part 1

---

doc/src/sgml/biblio.sgml
doc/src/sgml/btree-gin.sgml
doc/src/sgml/btree-gist.sgml

- biblio.sgml
- btree-gin.sgml
- btree-gist.sgml

update for 10.0 - part 2

---

src/backend/catalog/sql_features.txt.ja

メジャーバージョンアップなので
- src/backend/catalog/sql_feature_packages.txt.ja
- src/backend/catalog/sql_features.txt.ja
を更新する必要が出てくる可能性がありました。確認したところsql_features.txt.jaのみ更新が必要なようです。

update feature for 10.0

---

doc/src/sgml/ref/create_statistics.sgml
doc/src/sgml/ref/select.sgml

functional dependencyの訳語を変更

---

doc/src/sgml/ref/alter_table.sgml

Similarly, when の英文が見えてしまっているようです。

fix exposed English sentences

---

doc/src/sgml/mvcc.sgml

Update mvcc to 10.0

---

doc/src/sgml/pgbuffercache.sgml
doc/src/sgml/pgfreespacemap.sgml
doc/src/sgml/pgrowlocks.sgml

以下のファイル3つの10.0対応です。
- pgbuffercache.sgml
- pgfreespacemap.sgml

update 3 pg*.sgml files for 10.0

---

doc/src/sgml/queries.sgml
doc/src/sgml/query.sgml

- queries.sgml
- query.sgml
後者は本当に大したことないですが。

update quer* for 10.0

---

doc/src/sgml/logicaldecoding.sgml

logicaldecoding.sgmlのPostgreSQL 10対応です。

---

doc/src/sgml/plperl.sgml

update plperl for 10.0

---

doc/src/sgml/sepgsql.sgml
doc/src/sgml/textsearch.sgml

- sepgsql.sgml
- textsearch.sgml
textsearch.sgmlで追加した部分は9.6で訳が漏れていたものです。

Update for 10.0 - part 4

---

doc/src/sgml/maintenance.sgml

update maintenance for 10.0

---

doc/src/sgml/indices.sgml
doc/src/sgml/install-windows.sgml

- indices.sgml
- install-windows.sgml

update for 10.0 - part 5

---

doc/src/sgml/pgbuffercache.sgml
doc/src/sgml/pgfreespacemap.sgml
doc/src/sgml/pgrowlocks.sgml
doc/src/sgml/pgvisibility.sgml

- pgbuffercache.sgml
- pgfreespacemap.sgml
- pgvisibility.sgml

Update for 10.0 - part 6

---

doc/src/sgml/keywords.sgml

update keywords for 10.0

---

doc/src/sgml/pgstatstatements.sgml

pgstatstatements.sgml の 10.0 対応です。

update pgstatstatements for 10.0

---

doc/src/sgml/regress.sgml

update regress for 10.0

---

doc/src/sgml/plpython.sgml

update plpython for 10.0

---

doc/src/sgml/gin.sgml

update gin for 10.0

---

doc/src/sgml/ecpg.sgml

update ecpg for 10.0

---

doc/src/sgml/charset.sgml

"collation"は、基本的に「照合順序」と訳しています。

charset.sgmlのPostgreSQL 10対応です。

---

doc/src/sgml/postgres-fdw.sgml

postgres-fdwの10.0対応です。

---

doc/src/sgml/information_schema.sgml

information_schema.sgml の10.0対応です。

update information_schema to 10.0

---

doc/src/sgml/recovery-config.sgml

recovery-config.sgmlの10.0対応です。

---

doc/src/sgml/pageinspect.sgml

update pageinspect for 10.0

---

doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml
doc/src/sgml/release-9.5.sgml

- release-9.2.sgml
- release-9.3.sgml
- release-9.4.sgml
- release-9.5.sgml

Update release-9.[2-5] for 10.0

---

doc/src/sgml/release-9.6.sgml

update release-9.6 to 10.0

---

doc/src/sgml/pgstattuple.sgml

update pgstattuple for 10.0

---

doc/src/sgml/user-manag.sgml

ブランチの誤削除に伴い #1148 を間違えてクローズしてしまっため、再度作成しました。

user-manag.sgmlのPostgreSQL 10対応です。

---

doc/src/sgml/wal.sgml

wal.sgmlのPostgreSQL 10.0対応です。

---

doc/src/sgml/func.sgml
doc/src/sgml/func3.sgml

索引でおかしくなっているところを見つけましたので、修正です。
（makeしてみないと結果は分からないのですが、おそらく今回修正した部分が空の索引の原因ではないかと、、、）

fix typo (part 2)

---

doc/src/sgml/xfunc.sgml

update xfunc for 10.0

---

doc/src/sgml/plpgsql.sgml

update plpgsql for 10.0

---

doc/src/sgml/spgist.sgml

update spgist for 10.0

---

doc/src/sgml/typeconv.sgml

update typeconv to 10.0

---

doc/src/sgml/config.sgml

config.sgml に訳の誤りを見つけました。
（dead tuple絡みです、、、、）

correct wrong translation in config.sgml

---

doc/src/sgml/protocol.sgml

分量が多いので、分割してPRを出します。
その1では52.4節に相当する部分まで翻訳しました。
その２は新設の52.5節(Logical Streaming Replication Protocol)から翻訳します。

protocol.sgmlの10.0対応（その１）～52.4節まで

---

doc/src/sgml/protocol.sgml

52.9節（Logical Replication Message Formats)については、その3として別途やります。

protocol.sgmlの10.0対応（その2）～52.8節まで

---

doc/src/sgml/config.sgml

unify the translation of 'cipher suite'

---

doc/src/sgml/ddl.sgml

マージミスで重複して入っていた原文（＋訳文）を削除した箇所があります。

ddl.sgmlの10.0対応

---

doc/src/sgml/high-availability.sgml

Issue 1029 https://github.com/pgsql-jp/jpug-doc/issues/1029 対応を含めて訳を見直しました。

26.2.6. レプリケーションスロットの訳改善

---

doc/src/sgml/monitoring.sgml

monitoring.sgmlのTYPPOや原文削除などの対応

---

doc/src/sgml/rules.sgml
doc/src/sgml/runtime.sgml
doc/src/sgml/sourcerepo.sgml
doc/src/sgml/spi.sgml
doc/src/sgml/user-manag.sgml

10.3 向けコンフリクト解消のpart aの一部です。
part bと同じく、release-*を除く、ということで。

resolve conflicts part of 'part a'

---

doc/src/sgml/lobj.sgml

update lobj to 10.3

---

doc/src/sgml/contrib-spi.sgml
doc/src/sgml/contrib.sgml

以下の10.3対応です。
- contrib.sgml
- contrib-spi.sgml

update contrib* to 10.3

---

doc/src/sgml/ecpg.sgml

update ecpg to 10.3

---

doc/src/sgml/fdwhandler.sgml

fdwhandler の10.3対応

---

doc/src/sgml/plpgsql.sgml

update plpgsql to 10.3

---

doc/src/sgml/ref/prepare_transaction.sgml

ref/prepare_transaction.sgml の10.3対応です。

update prepare_transaction to 10.3

---

doc/src/sgml/extend.sgml

10.3で新しくコメントが追加されているのですが、そこは翻訳していません。

extend.sgmlのPostgreSQL 10.3対応です。

---

doc/src/sgml/release-10.sgml

release-10で＜！ーーの後にあったタブを削除しました。
#1232 対策になっていると思います。（手元では（そんな環境は構築していないためか）make checkできていませんが。）

remove extra tabs

---

src/backend/utils/errcodes.txt.ja

済みません。10になったときだと思いますが、errcodeの更新を忘れていたようです。

update errcodes for 10.3

---

doc/src/sgml/stylesheet-custom.xsl

[jpug-doc: 5635] 参考文献に表示について で取り上げた問題に対応するパッチです。（[jpug-doc: 5636] Re: 参考文献に表示について に添付されているものと同じです。）

custom stylesheet patch

---

doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml

リリースノートで訳の誤りと思われる所を見つけました。
何処をどのように修正したかはそのものを見てもらった方が早いかと。
変更したファイルは三つになっていますが、どれも同じ所を同じように修正しています。

fixes in release notes

---

doc/src/sgml/trigger.sgml

ビューに対するトリガの解説が付け加えられていますが、背景については、
pgsql-bugsの15106番をご覧ください。

trigger.sgmlのPostgreSQL 10.4対応です。

---

doc/src/sgml/high-availability.sgml

fix description of cascading replication (#1270)

---

doc/src/sgml/release-9.1.sgml
doc/src/sgml/release-9.2.sgml
doc/src/sgml/release-9.3.sgml

fix typo (catalog access)

---

doc/src/sgml/ref/pgbench.sgml

fix 'transaction'

---

doc/src/sgml/ref/drop_subscription.sgml

fix typo (transaction block)

---

doc/src/sgml/release-10.sgml

fix typo (logical replication)

---

doc/src/sgml/config.sgml

fix typo (client)

---

doc/src/sgml/release-9.6.sgml

fix typo in release note 9.6

---

doc/src/sgml/external-projects.sgml

external-projects.sgmlの10.5対応です。

update external-projects.sgml for 10.5

---

doc/src/sgml/install-windows.sgml

install-windows.sgmlの10.5対応です。

update install-windows.sgml for 10.5

---

doc/src/sgml/test-decoding.sgml

update test-decodeing for 10.5

---

doc/src/sgml/monitoring.sgml

update monitoring for 10.5

---

doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml
doc/src/sgml/release-9.5.sgml
doc/src/sgml/release-9.6.sgml

update release-9.[3-6] for 10.5

---

doc/src/sgml/ecpg.sgml

update ecpg for 10.5

---

doc/src/sgml/func.sgml
doc/src/sgml/func3.sgml

best effortの誤訳

---

doc/src/sgml/syntax.sgml
doc/src/sgml/typeconv.sgml

以下のファイルの10.5対応です。
- syntax.sgml
- typeconv.sgml

update syntax and typeconv for 10.5

---

doc/src/sgml/ref/create_function.sgml

ref/create_function.sgml の10.5対応です。

update create_function for 10.5

---

doc/src/sgml/release-10.sgml
doc/src/sgml/release-9.3.sgml
doc/src/sgml/release-9.4.sgml
doc/src/sgml/release-9.5.sgml
doc/src/sgml/release-9.6.sgml

行末の余分な空白を削除しました。
＃かなりどうでもいい修正ですが、、、、

remove extra white space at line end

---

doc/src/sgml/config.sgml

「キーワードANYと組わせると」の段落の誤訳を修正しました。

synchronous_standby_namesの誤訳の修正です。

---

doc/src/sgml/xplang.sgml

update xplang to 11.1

---

doc/src/sgml/xoper.sgml

update xoper for 11.1

---

doc/src/sgml/isn.sgml
doc/src/sgml/oid2name.sgml
doc/src/sgml/uuid-ossp.sgml

11.1対応（新たに翻訳したところは無し）

---

doc/src/sgml/xaggr.sgml

update xaggr for 11.1

---

doc/src/sgml/ref/refresh_materialized_view.sgml
doc/src/sgml/ref/security_label.sgml

- ref/refresh_materialized_view.sgml
- ref/security_label.sgml

update refresh... and seclabel for 11.1

---

doc/src/sgml/cube.sgml

cubeの11.1対応です。

---

doc/src/sgml/typeconv.sgml
doc/src/sgml/unaccent.sgml

- typeconv.sgml
- unaccent.sgml

update typeconv and unaccent for 11.1

---

doc/src/sgml/ref/update.sgml
doc/src/sgml/ref/vacuum.sgml

- ref/update.sgml
- ref/vacuum.sgml

update update and vacuum for 11.1

---

doc/src/sgml/user-manag.sgml
doc/src/sgml/wal.sgml

update user-manag and wal for 11.1

---

doc/src/sgml/storage.sgml

update storage for 11.1

---

doc/src/sgml/postgres-fdw.sgml

postgres-fdw.sgmlで些細な誤りを見つけました。

minor fix for postgres-fdw

---

doc/src/sgml/ref/pgupgrade.sgml
doc/src/sgml/ref/prepare.sgml

update pgupgrade and prepare for 11.1

---

doc/src/sgml/ref/lock.sgml
doc/src/sgml/ref/pg_ctl-ref.sgml

- ref/lock.sgml
- ref/pg_ctl-ref.sgml

update lock and pg_ctl-ref for 11.1

---

doc/src/sgml/ref/alter_extension.sgml
doc/src/sgml/ref/alter_opfamily.sgml

- ref/alter_extension.sgml
- ref/alter_opfamily.sgml

update alter_extension and opfamily for 11.1

---

doc/src/sgml/ref/analyze.sgml
doc/src/sgml/ref/comment.sgml
doc/src/sgml/ref/copy.sgml

- ref/analyze.sgml
- ref/comment.sgml
- ref/copy.sgml

update analyze, comment and copy for 11.1

---

doc/src/sgml/history.sgml

history.sgmlの11.1対応です。

---

doc/src/sgml/gin.sgml

gin.sgmlの11.1対応です。

---

doc/src/sgml/bgworker.sgml

bgwork.sgmlのPostgreSQL11.1対応分翻訳いたしました。
レビューよろしくお願いいたします。

update bgworker for 11.1

---

doc/src/sgml/btree.sgml

数学用語の翻訳で少し悩みました。"the ordering is total"は、「順序は全である」と訳しましたが、あまり自信ありません。

btree.sgmlのPostgreSQL 11.1対応です。

---

doc/src/sgml/ref/alter_default_privileges.sgml

alter_default_privileges.sgml の 11.1 対応です。

updete alter_default_privileges for 11.1

---

doc/src/sgml/ref/create_opclass.sgml
doc/src/sgml/ref/create_operator.sgml
doc/src/sgml/ref/do.sgml

- ref/create_opclass.sgml
- ref/create_operator.sgml
- ref/do.sgml

update create_opclass, create_operator and do for 11.1

---

doc/src/sgml/release-10.sgml

10.6 リリースノート翻訳

---

doc/src/sgml/pgtrgm.sgml

words を「単語」と訳してはまずそうな箇所は単語の並びと書きました。
もっと良い案があれば指摘ください。

pgtrgm.sgml を 11.1 むけに翻訳

---

doc/src/sgml/rules.sgml

コメントアウトされていた部分がxml対応の修正で外れてしまったので、通常のコメント化に直しています。

rules.sgmlの11.1対応です。

---

doc/src/sgml/func.sgml
doc/src/sgml/func4.sgml

fix unclosed comment

---

doc/src/sgml/bki.sgml

皆さんあけましておめでとうございます。
bki.sgmlは久しぶりに大量の追記がありました。

bki.sgmlのPostgreSQL 11.1対応です。

---

doc/src/sgml/pgstattuple.sgml

update pgstattuple for 11.1

---

doc/src/sgml/installation.sgml

update installation for 11.1

---

doc/src/sgml/runtime.sgml

fix missing comment tags

---

doc/src/sgml/information_schema.sgml

information_schema.sgmlの11.1対応です。

update information_schema for 11.1

---

doc/src/sgml/lobj.sgml

fix a missing comment tag

---

doc/src/sgml/ref/grant.sgml
doc/src/sgml/ref/insert.sgml

- ref/grant.sgml
- ref/insert.sgml

update grant and insert for 11.1

---

doc/src/sgml/ref/create_event_trigger.sgml
doc/src/sgml/ref/create_trigger.sgml

- ref/create_event_trigger.sgml
- ref/create_trigger.sgml

update create*_trigger for 11.1

---

doc/src/sgml/ref/pg_verify_checksums.sgml

ref/pg_verify_checksums.sgml の11.1向けの翻訳です。11で新しく追加されたファイルだと思います。

pg_verify_checksums for 11.1

---

doc/src/sgml/ref/call.sgml

call.sgmlのPostgreSQL11.1 の対応をいたしました

update ref/call.sgml for 11.1

---

doc/src/sgml/syntax.sgml

全角スペースを見つけました。見た目に大きな影響はないですが、literalタグの中なのでちょっと許容はできないかな、と。

remove zenkaku space

---

doc/src/sgml/func.sgml
doc/src/sgml/func4.sgml

https://pgsql-jp.github.io/jpug-doc/11.1/html/functions-info.html#FUNCTIONS-TXID-SNAPSHOT
の修正です。

表9.69 トランザクションIDとスナップショットの修正

---

.travis.yml

travis環境のxenialへのアップグレード

---

doc/src/sgml/ref/copy.sgml
doc/src/sgml/ref/initdb.sgml

以下のファイルの11.3対応です。
- ref/copy.sgml
- ref/initdb.sgml

update copy and initdb for 11.3

---

doc/src/sgml/ref/pgbench.sgml
doc/src/sgml/ref/pgupgrade.sgml

以下のファイルの11.3対応です。
- ref/pgbench.sgml
- ref/pgupgrade.sgml

update pgbench and pgupgrade for 11.3

---

doc/src/sgml/monitoring.sgml

"speculative"の訳を「推論的」から「投機的」に変更。

Issue 1471対応です。

---

doc/src/sgml/func.sgml
doc/src/sgml/func4.sgml

func.sgmlのPostgreSQL 11.3対応です。

---

doc/src/sgml/perform.sgml

一部の日本語訳がマージミスで削除されていたので復活しています。

perform.sgmlのPostgreSQL 11.3対応です。

---

doc/src/sgml/ref/prepare_transaction.sgml
doc/src/sgml/xml2.sgml

以下のファイルの11.3対応です。
- ref/prepare_transaction.sgml
- xml2.sgml

update some unassigned files to 11.3

---

doc/src/sgml/runtime.sgml

一部の日本語訳がマージミスで削除されていたので復活しています。

runtime.sgmlのPostgreSQL 11.3対応です。

---

doc/src/sgml/ref/create_type.sgml
doc/src/sgml/ref/drop_owned.sgml

以下のファイルの11.3対応です。create_typeの差分が大きく見えますが、ほとんどはマージミス対応です。
- ref/create_type.sgml
- ref/drop_owned.sgml

update some unassigned files to 11.3 (2)

---

doc/src/sgml/maintenance.sgml

update maintenance for 11.3

---

doc/src/sgml/custom-scan.sgml

custom-scan.sgmlのPostgreSQL 11.3対応です。

---

doc/src/sgml/ref/create_foreign_table.sgml

ref/create_foreign_table.sgmlの11.3対応です。

update create_foreign_table for 11.3

---

doc/src/sgml/ref/alter_large_object.sgml

ref/alter_large_object.sgmlの11.3対応です。

update alter_large_object for 11.3

---

doc/src/sgml/ddl.sgml

ddl.sgmlの原文のインデントが変わってしまっているのを修正

---

doc/src/sgml/legal.sgml
doc/src/sgml/postgres-fdw.sgml

以下のファイルの11.3対応です。
- legal.sgml
- postgres-fdw.sgml

update some unassigned files to 11.3 (3)

---

doc/src/sgml/ref/update.sgml

update 'update' for 11.3

---

doc/src/sgml/information_schema.sgml
doc/src/sgml/storage.sgml

以下のファイルの11.4対応です。
- information_schema.sgml
- storage.sgml

update information_schema and storage for 11.4

---

doc/src/sgml/backup.sgml
doc/src/sgml/high-availability.sgml
doc/src/sgml/libpq.sgml
doc/src/sgml/runtime.sgml

原文がそのまま表示されていた部分の修正

---

doc/src/sgml/client-auth.sgml

fix punctuation

---

doc/src/sgml/func.sgml
doc/src/sgml/func3.sgml
doc/src/sgml/func4.sgml

func.sgmlのPostgreSQL 11.4対応です。

---

doc/src/sgml/ref/alter_table.sgml

fix typo in "ALTER TABLE"

---

doc/src/sgml/datatype.sgml

datatype.sgmlの削除漏れ

---

doc/src/sgml/ref/create_foreign_table.sgml

ref/create_foreign_table.sgmlの11.5対応です。

update create_foreign_table for 11.5

---

doc/src/sgml/ref/pgbench.sgml

update pgbench for 11.5

---

doc/src/sgml/config.sgml
doc/src/sgml/config2.sgml

コメントの翻訳のみです。ちょっと意味が取れていないところがあり、あまり
訳出に自信がありません。

config.sgmlのPostgreSQL 11.5対応です。

---

doc/src/sgml/ddl.sgml

update ddl for 11.5

---

doc/src/sgml/func.sgml

variance関数の索引引用タグを追加し、索引に追加しました。

varianceの索引生成

---

doc/src/sgml/monitoring.sgml

idx_scanの翻訳の修正

---

doc/src/sgml/gin.sgml

gin.sgmlの12.0対応です。

---

doc/src/sgml/ref/abort.sgml
doc/src/sgml/ref/alter_default_privileges.sgml
doc/src/sgml/ref/alter_foreign_table.sgml
doc/src/sgml/ref/alter_function.sgml
doc/src/sgml/ref/alter_type.sgml
doc/src/sgml/ref/analyze.sgml
doc/src/sgml/ref/clusterdb.sgml
doc/src/sgml/ref/copy.sgml

- ref/abort.sgml
- ref/alter_default_privileges.sgml
- ref/alter_foreign_table.sgml
- ref/alter_function.sgml
- ref/alter_type.sgml
- ref/analyze.sgml
- ref/clusterdb.sgml
- ref/copy.sgml

update ref/abort etc. for 12

---

doc/src/sgml/ref/create_access_method.sgml
doc/src/sgml/ref/create_collation.sgml
doc/src/sgml/ref/create_foreign_table.sgml
doc/src/sgml/ref/create_materialized_view.sgml
doc/src/sgml/ref/create_statistics.sgml
doc/src/sgml/ref/create_table_as.sgml
doc/src/sgml/ref/create_tablespace.sgml
doc/src/sgml/ref/create_trigger.sgml

- ref/create_access_method.sgml
- ref/create_collation.sgml
- ref/create_foreign_table.sgml
- ref/create_materialized_view.sgml
- ref/create_statistics.sgml
- ref/create_table_as.sgml
- ref/create_tablespace.sgml
- ref/create_trigger.sgml

update ref/create_* for 12

---

doc/src/sgml/mvcc.sgml
doc/src/sgml/ref/select_into.sgml
doc/src/sgml/sslinfo.sgml
doc/src/sgml/tablesample-method.sgml

- mvcc.sgml
- ref/select_into.sgml
- sslinfo.sgml
- tablesample-method.sgml

update mvcc etc. for 12

---

doc/src/sgml/ref/pg_controldata.sgml
doc/src/sgml/ref/pg_ctl-ref.sgml

- ref/pg_controldata.sgml
- ref/pg_ctl-ref.sgml

update pg_ctl-ref and pg_controldata for 12

---

doc/src/sgml/ref/pg_resetwal.sgml

環境とPG_COLORの日本語訳を作成しました。
内容がclusterdb.sgmlと同じであったため、日本語訳も同じにさせて頂きました。

source from clusterdb.sgml

---

doc/src/sgml/installation.sgml
doc/src/sgml/standalone-install.xml

- installation.sgml
- standalone-install.xml

update installation etc. for 12

---

doc/src/sgml/ref/createdb.sgml
doc/src/sgml/ref/createuser.sgml
doc/src/sgml/ref/dropdb.sgml
doc/src/sgml/ref/dropuser.sgml
doc/src/sgml/ref/end.sgml
doc/src/sgml/ref/explain.sgml
doc/src/sgml/ref/grant.sgml
doc/src/sgml/ref/initdb.sgml
doc/src/sgml/ref/insert.sgml

- ref/createdb.sgml
- ref/createuser.sgml
- ref/dropdb.sgml
- ref/dropuser.sgml
- ref/end.sgml
- ref/explain.sgml
- ref/grant.sgml
- ref/initdb.sgml
- ref/insert.sgml

update ref/createdb etc for 12

---

doc/src/sgml/docguide.sgml
doc/src/sgml/ref/pg_waldump.sgml

以下のファイルの12対応です。 
- docguide.sgml
- ref/pg_waldump.sgml

update docguide and ref/pg_waldump for 12

---

doc/src/sgml/amcheck.sgml
doc/src/sgml/custom-scan.sgml

- amcheck.sgml
- custom-scan.sgml

update amcheck and custom-scan for 12

---

doc/src/sgml/file-fdw.sgml
doc/src/sgml/xindex.sgml

update file-fdw and xindex for 12

---

doc/src/sgml/ref/pg_restore.sgml

update pg_restore for 12

---

doc/src/sgml/ref/reindexdb.sgml

update reindexdb for 12

---

doc/src/sgml/ref/pg_basebackup.sgml

ref/pg_basebackup.sgmlの12対応です。

update pg_basebackup for 12

---

doc/src/sgml/install-windows.sgml

update install-windows for 12

---

doc/src/sgml/pgstatstatements.sgml

update pgstatstatements for 12

---

doc/src/sgml/ref/alter_index.sgml
doc/src/sgml/ref/create_aggregate.sgml
doc/src/sgml/ref/pg_rewind.sgml

- ref/alter_index.sgml
- ref/create_aggregate.sgml
- ref/pg_rewind.sgml

update pg_rewind etc for 12

---

doc/src/sgml/bgworker.sgml
doc/src/sgml/release-12.sgml

ものすごく些細な修正です。
「。」の後にある余分な空白を削除しました。

remove extra space

---

doc/src/sgml/vacuumlo.sgml

update vacuumlo for 12

---

doc/src/sgml/backup.sgml

加えて、本セクション内の"リカバリ"、"リカバリー"、"復旧"を"復旧"に寄せる変更を加えています。

backup.sgml の 12.0 の変更点を翻訳

---

doc/src/sgml/ref/pgarchivecleanup.sgml

ref/pgarchivecleanup.sgml の12対応です。

update pg_archcleanup for 12

---

doc/src/sgml/user-manag.sgml

update user-manag for 12

---

doc/src/sgml/ref/alter_domain.sgml
doc/src/sgml/ref/create_domain.sgml

- ref/alter_domain.sgml
- ref/create_domain.sgml

update alter/create_domain for 12

---

doc/src/sgml/ref/alter_table.sgml

update alter_table for 12

---

doc/src/sgml/ref/pg_dumpall.sgml

update pg_dumpall for 12

---

doc/src/sgml/oid2name.sgml

update oid2name for 12

---

doc/src/sgml/ref/create_index.sgml

ref/create_index.sgml の12対応です。

update create_index for 12

---

doc/src/sgml/ref/create_function.sgml
doc/src/sgml/ref/pg_dump.sgml

- ref/create_function.sgml
- ref/pg_dump.sgml

update create_fn and pg_dump for 12

---

doc/src/sgml/ref/vacuum.sgml
doc/src/sgml/ref/vacuumdb.sgml

- ref/vacuum.sgml
- ref/vacuumdb.sgml

update vacuum and vacuumdb for 12

---

doc/src/sgml/auto-explain.sgml

update auto-explain for 12

---

doc/src/sgml/spgist.sgml

update spgist for 12

---

doc/src/sgml/func.sgml
doc/src/sgml/func4.sgml

minor fix of func

---

doc/src/sgml/ecpg.sgml

update ecpg for 12

---

doc/src/sgml/maintenance.sgml

update maintenance for 12

---

doc/src/sgml/ref/commit.sgml

update commit for 12

---

doc/src/sgml/ref/rollback.sgml

update rollback for 12

---

doc/src/sgml/storage.sgml

update storage for 12

---

doc/src/sgml/spi.sgml

update spi for 12

---

doc/src/sgml/plpgsql.sgml

update plpgsql for 12

---

doc/src/sgml/charset.sgml

Update charset for 12

---

doc/src/sgml/xfunc.sgml

update xfunc for 12

---

doc/src/sgml/ref/pgupgrade.sgml

update pgupgrade for 12

---

doc/src/sgml/sources.sgml
doc/src/sgml/trigger.sgml

以下のファイルの12.0対応です。
- sources.sgml
- trigger.sgml

update sources and trigger for 12.0

---

doc/src/sgml/features.sgml

features.sgml の PostgreSQL 12対応翻訳

---

doc/src/sgml/acronyms.sgml
doc/src/sgml/ref/psql-ref.sgml

update psql-ref for 12

---

doc/src/sgml/regress.sgml

update regress for 12

---

doc/src/sgml/ref/pgbench.sgml

update pgbench for 12

---

doc/src/sgml/planstats.sgml

update planstats for 12

---

doc/src/sgml/limits.sgml

limits.sgml の新規翻訳です。（limits.sgml は12で初めて現れたもののはずです。）

translate limits for 12

---

doc/src/sgml/func.sgml
doc/src/sgml/func2.sgml
doc/src/sgml/func3.sgml

「accessorの訳語#1656」の修正です。
fixed #1656

アクセッサ演算子をアクセサ演算子に変更

---

doc/src/sgml/ref/create_table.sgml

remove an extra white space

---

doc/src/sgml/func.sgml

func.sgmlの12.0の修正漏れ追加

---

doc/src/sgml/legal.sgml

update legal for 12.3

---

doc/src/sgml/ref/pgarchivecleanup.sgml
doc/src/sgml/ref/pgbench.sgml
doc/src/sgml/ref/pgtestfsync.sgml

- ref/pgarchivecleanup.sgml
- ref/pgbench.sgml
- ref/pgtestfsync.sgml

update pgbench etc. for 12.3

---

doc/src/sgml/ref/refresh_materialized_view.sgml
doc/src/sgml/ref/security_label.sgml
doc/src/sgml/ref/set_role.sgml

- ref/refresh_materialized_view.sgml
- ref/security_label.sgml
- ref/set_role.sgml

update ref/refresh... etc. for 12.3

---

doc/src/sgml/jpug-doc.sgml

PostgreSQL12の貢献者を記載

---

doc/src/sgml/ref/revoke.sgml
doc/src/sgml/ref/select.sgml

- ref/revoke.sgml
- ref/select.sgml

update revoke and select for 12.3

---

doc/src/sgml/install-windows.sgml

install-windows.sgml の12.3対応です。

update install-win for 12.3

---

doc/src/sgml/ref/create_index.sgml
doc/src/sgml/ref/drop_index.sgml
doc/src/sgml/ref/reindex.sgml

- ref/create_index.sgml
- ref/drop_index.sgml
- ref/reindex.sgml

update create/drop/re-index for 12.3

---

doc/src/sgml/mvcc.sgml

update mvcc for 12.3

---

doc/src/sgml/ref/truncate.sgml
doc/src/sgml/ref/update.sgml

- ref/truncate.sgml
- ref/update.sgml

update truncate and update for 12.3

---

doc/src/sgml/libpq.sgml

update libpq for 12.3

---

doc/src/sgml/pgbuffercache.sgml

update pgbuffercache for 12.3

---

doc/src/sgml/ref/grant.sgml

update grant for 12.3

---

doc/src/sgml/ref/ecpg-ref.sgml

update ecpg-ref for 12.3

---

doc/src/sgml/ref/copy.sgml

update copy for 12.3

---

doc/src/sgml/ref/delete.sgml

update delete for 12.3

---

doc/src/sgml/ref/alter_table.sgml

ref/alter_table.sgmlの12.3対応です。

update alter_table for 12.3

---

doc/src/sgml/ref/alter_default_privileges.sgml

ref/alter_default_privileges.sgmlの12.3対応です。

update alter_def.._priv.. for 12.3

---

doc/src/sgml/ltree.sgml

update ltree for 12.3

---

doc/src/sgml/textsearch.sgml

update textsearch for 12.3

---

doc/src/sgml/config.sgml
doc/src/sgml/config3.sgml

fix typo in config

---

doc/src/sgml/config.sgml
doc/src/sgml/config3.sgml

remove extra white space

---

doc/src/sgml/release-12.sgml

12.3部分、12.2部分だけで、12.1 部分が未だです。後からコミットする予定です。

12.3 リリースノート翻訳です。

---

doc/src/sgml/installation.sgml
doc/src/sgml/rangetypes.sgml

- installation.sgml
- rangetypes.sgml

update installation and rangetype for 12.3

---

doc/src/sgml/seg.sgml
doc/src/sgml/textsearch.sgml

以下のファイル2つの12.4対応です。
- seg.sgml
- textsearch.sgml
（URLの変更だけです。）

update seg and textsearch

---

doc/src/sgml/jpug-doc.sgml

不足していたスペースを追記

---

doc/src/sgml/ref/pg_restore.sgml
doc/src/sgml/ref/pgupgrade.sgml
doc/src/sgml/ref/reindexdb.sgml
doc/src/sgml/runtime.sgml

- ref/pg_restore.sgml
- ref/pgupgrade.sgml
- ref/reindexdb.sgml
- runtime.sgml

update for 12.4 - part 2

---

doc/src/sgml/ref/create_database.sgml

ref/create_database.sgml の12.4対応です。

update create_database for 12.4

---

doc/src/sgml/plperl.sgml
doc/src/sgml/plpgsql.sgml
doc/src/sgml/pltcl.sgml

- plperl.sgml
- plpgsql.sgml
- pltcl.sgml

update for 12.4 - part 3

---

doc/src/sgml/install-windows.sgml
doc/src/sgml/intro.sgml
doc/src/sgml/libpq.sgml

- install-windows.sgml
- intro.sgml
- libpq.sgml
URLの更新と削除だけです。

update install-windows etc. for 12.4

---

doc/src/sgml/dfunc.sgml
doc/src/sgml/external-projects.sgml
doc/src/sgml/features.sgml

- dfunc.sgml
- external-projects.sgml
- features.sgml
と言っても、URLの変更と、誤って消されてしまったらしいものの復活だけですが。

update dfunc etc. for 12.4

---

doc/src/sgml/bki.sgml
doc/src/sgml/cube.sgml

- bki.sgml
- cube.sgml
と言っても、今回もURLの更新と削除です。

update bki and cube for 12.4

---

doc/src/sgml/maintenance.sgml

update maintenance for 12.4

---

doc/src/sgml/advanced.sgml

update advanced for 12.4

---

doc/src/sgml/biblio.sgml

biblio.sgml の12.4対応です。
変更点はもっと多いのですが、基本的に訳さないので、修正はURL更新の一か所だけでした。

update biblio for 12.4

---

doc/src/sgml/ref/create_trigger.sgml

ref/create_trigger.sgml の12.4対応です。

update create_trigger for 12.4

---

doc/src/sgml/monitoring.sgml

update monitoring for 12.4

---

doc/src/sgml/acronyms.sgml
doc/src/sgml/earthdistance.sgml

- acronyms.sgml
- earthdistance.sgml

update acronyms etc. for 12.4

---

doc/src/sgml/release-12.sgml

Doc ja 12 4 release

---

doc/src/sgml/fdwhandler.sgml

fdwhandlerの12.4対応

---

doc/src/sgml/ref/create_extension.sgml

ref/create_extension.sgml の12.4対応です。

update create_extension for 12.4

---

doc/src/sgml/extend.sgml

remove an extra space

---

doc/src/sgml/backup.sgml

backupで「意訳としても、ちょっとやりすぎなのでは」という部分を見つけました。

Fix backup 12.4

---

doc/src/sgml/tsm-system-rows.sgml

tsm-system-rows.sgml の 13.1 対応版です。

update tsm-system-rows for 13.1

---

doc/src/sgml/ref/alter_collation.sgml
doc/src/sgml/ref/alter_function.sgml
doc/src/sgml/ref/alter_index.sgml

- ref/alter_collation.sgml
- ref/alter_function.sgml
- ref/alter_index.sgml

update alter_collation etc. for 13.1

---

doc/src/sgml/wal.sgml

update wal for 13.1

---

doc/src/sgml/sslinfo.sgml
doc/src/sgml/storage.sgml

update sslinfo and storage for 13.1

---

doc/src/sgml/ref/commit_prepared.sgml
doc/src/sgml/ref/prepare.sgml
doc/src/sgml/ref/prepare_transaction.sgml
doc/src/sgml/ref/rollback_prepared.sgml

- ref/commit_prepared.sgml
- ref/prepare_transaction.sgml
- ref/rollback_prepared.sgml

update *_prepared for 13.1

---

doc/src/sgml/xoper.sgml

xoper.sgml の13.1対応です。
が、何が書いてあるのか自分でもよく分かっていません(T_T)

update xoper for 13.1

---

doc/src/sgml/xml2.sgml

xml2.sgml の13.1対応です。
「表のマージ云々」と話題になっていたのはこの件だったのか、とようやく分かりました。微妙に文も変わっているので自動は厳しいですね、、、

update xml2 for 13.1

---

doc/src/sgml/ref/values.sgml

update values for 13.1

---

doc/src/sgml/ref/postgres-ref.sgml
doc/src/sgml/ref/truncate.sgml

- ref/postgres-ref.sgml
- ref/truncate.sgml

update postgres-ref and truncate for 13.1

---

doc/src/sgml/btree-gin.sgml
doc/src/sgml/btree-gist.sgml
doc/src/sgml/fuzzystrmatch.sgml
doc/src/sgml/lo.sgml
doc/src/sgml/tcn.sgml
doc/src/sgml/unaccent.sgml

btree-gin.sgml
btree-gist.sgml
fuzzystrmatch.sgml
lo.sgml
tcn.sgml
unaccent.sgml

"trusted 〜"の文のみが追加されたファイルの対応です。

---

doc/src/sgml/ref/alter_view.sgml
doc/src/sgml/ref/create_operator.sgml
doc/src/sgml/ref/create_tablespace.sgml

- ref/alter_view.sgml
- ref/create_operator.sgml
- ref/create_tablespace.sgml

update alter_view etc. for 13.1

---

doc/src/sgml/pgstatstatements.sgml

update pg_stat_statements for 13.1

---

doc/src/sgml/ref/declare.sgml
doc/src/sgml/ref/delete.sgml
doc/src/sgml/ref/drop_index.sgml

- ref/declare.sgml
- ref/delete.sgml
- ref/drop_index.sgml

update declare etc. for 13.1

---

doc/src/sgml/rules.sgml

update rules for 13.1

---

doc/src/sgml/advanced.sgml
doc/src/sgml/bki.sgml

update advanced and bki for 13.1

---

doc/src/sgml/bloom.sgml

update bloom for 13.1

---

doc/src/sgml/citext.sgml

update citext for 13.1

---

doc/src/sgml/ref/create_aggregate.sgml
doc/src/sgml/ref/create_conversion.sgml

- ref/create_aggregate.sgml
- ref/create_conversion.sgml

update create_aggregate/conversion for 13.1

---

doc/src/sgml/docguide.sgml
doc/src/sgml/install-windows.sgml
doc/src/sgml/oid2name.sgml
doc/src/sgml/pgcrypto.sgml

- docguide.sgml
- install-windows.sgml
- oid2name.sgml
- pgcrypto.sgml

update docguide etc. for 13.1

---

doc/src/sgml/mvcc.sgml

Only changed 'Current Lock Mode' to 'Existing Lock Mode'.

update mvcc for 13.1

---

doc/src/sgml/ref/drop_database.sgml
doc/src/sgml/ref/dropdb.sgml

- ref/drop_database.sgml
- ref/dropdb.sgml

update dropdb etc. for 13.1

---

doc/src/sgml/ref/alter_materialized_view.sgml
doc/src/sgml/ref/alter_role.sgml
doc/src/sgml/ref/alter_tablespace.sgml
doc/src/sgml/ref/alter_trigger.sgml

- ref/alter_materialized_view.sgml
- ref/alter_tablespace.sgml
- ref/alter_trigger.sgml

update alter_trigger etc. for 13.1

---

doc/src/sgml/spi.sgml

update spi for 13.1

---

doc/src/sgml/sepgsql.sgml

update sepgsql for 13.1

---

doc/src/sgml/pgbuffercache.sgml

update pgbuffercache for 13.1

---

doc/src/sgml/seg.sgml

update seg for 13.1

---

doc/src/sgml/lobj.sgml

update lobj for 13.1

---

doc/src/sgml/event-trigger.sgml

update event-trigger for 13.1

---

doc/src/sgml/acronyms.sgml

fix GSSAPI's translation

---

doc/src/sgml/ref/pg_receivewal.sgml
doc/src/sgml/ref/pg_recvlogical.sgml
doc/src/sgml/ref/pg_restore.sgml
doc/src/sgml/ref/pg_waldump.sgml

- ref/pg_receivewal.sgml
- ref/pg_recvlogical.sgml
- ref/pg_restore.sgml
- ref/pg_waldump.sgml

update pg_waldump etc. for 13.1

---

doc/src/sgml/dblink.sgml

dblinkの13.1対応です。

---

doc/src/sgml/earthdistance.sgml

update earthdistance for 13.1

---

doc/src/sgml/config.sgml
doc/src/sgml/ref/create_index.sgml
doc/src/sgml/ref/create_table.sgml

索引でconfiguration parameterとstorage parameterの訳し忘れを見つけました。

fix indexterm

---

doc/src/sgml/config0.sgml
doc/src/sgml/config1.sgml
doc/src/sgml/config2.sgml

小泉さんの修正でconfig.sgmlに修正が入ったので、split-config.shを起動し
て分割ファイルを更新しました。

config.sgmlへの修正対応です。

---

doc/src/sgml/plpython.sgml

update plpython for 13.1

---

doc/src/sgml/ecpg.sgml

update ecpg for 13.1

---

doc/src/sgml/tablefunc.sgml

update tablefunc for 13.1

---

doc/src/sgml/adminpack.sgml
doc/src/sgml/dict-int.sgml

以下のファイルの 13.1 対応です。
- adminpack.sgml
- dict-int.sgml

update adminpack and dict-int for 13.1

---

doc/src/sgml/file-fdw.sgml

update file-fdw for 13.1

---

doc/src/sgml/ref/create_view.sgml
doc/src/sgml/ref/createdb.sgml

- ref/create_view.sgml
- ref/createdb.sgml

update create view and db for 13.1

---

doc/src/sgml/ref/pgupgrade.sgml

ref/pgupgrade.sgml の13.1対応です。
e.g.,対応だけかと思ったのですが、、、、、

update pg_upgrade for 13.1

---

doc/src/sgml/ref/create_language.sgml

ref/create_language.sgml の13.1対応です。

update create_language for 13.1

---

doc/src/sgml/fdwhandler.sgml

fdwhandler.sgml の13.1対応です。

---

doc/src/sgml/ref/pgbench.sgml

update pgbench for 13.1

---

doc/src/sgml/ref/create_database.sgml
doc/src/sgml/ref/create_role.sgml

update create_database & role for 13.1

---

doc/src/sgml/intarray.sgml

update intarray for 13.1

---

doc/src/sgml/hstore.sgml

update hstore for 13.1

---

doc/src/sgml/ref/pg_basebackup.sgml

ref/pg_basebackup.sgml の13.1対応です。

update pg_basebackup for 13.1

---

doc/src/sgml/ref/pg_isready.sgml
doc/src/sgml/ref/update.sgml

以下のファイルの 13.1 対応です。
- ref/pg_isready.sgml
- ref/update.sgml

update pg_isready and update for 13.1

---

doc/src/sgml/json.sgml

update json for 13.1

---

doc/src/sgml/amcheck.sgml

update amcheck for 13.1

---

doc/src/sgml/ref/create_extension.sgml
doc/src/sgml/ref/create_index.sgml
doc/src/sgml/ref/create_opclass.sgml
doc/src/sgml/ref/create_publication.sgml

以下のファイルの 13.1 対応です。
- ref/create_extension.sgml
- ref/create_index.sgml
- ref/create_opclass.sgml
- ref/create_publication.sgml

update create_extention - publication for 13.1

---

doc/src/sgml/ref/alter_statistics.sgml

ref/alter_statistics.sgml の13.1対応です。

update alter statistics for 13.1

---

doc/src/sgml/manage-ag.sgml

update manage-ag for 13.1

---

doc/src/sgml/trigger.sgml

update trigger for 13.1

---

doc/src/sgml/syntax.sgml

update syntax for 13.1

---

doc/src/sgml/ref/clusterdb.sgml

ref/clusterdb.sgml の 13.1 対応です。

update clusterdb for 13.1

---

doc/src/sgml/ltree.sgml

update ltree for 13.1

---

doc/src/sgml/textsearch.sgml

update textsearch for 13.1

---

doc/src/sgml/typeconv.sgml

update typeconv for 13.1

---

doc/src/sgml/spgist.sgml

update spgist for 13.1

---

doc/src/sgml/brin.sgml
doc/src/sgml/gin.sgml

update brin and gin for 13.1

---

doc/src/sgml/gist.sgml

update gist for 13.1

---

doc/src/sgml/ref/reindex.sgml

update reindex for 13.1

---

doc/src/sgml/ref/pg_dumpall.sgml

ref/pg_dumpall.sgml の 13.1 対応です。

update pg_dumpall for 13.1

---

doc/src/sgml/ref/select.sgml

update select for 13.1
