- doc/src/sgml/ref/reindexdb.sgml
ref/reindexdb.sgml の 13.1 対応です。
> update reindexdb for 13.1

- doc/src/sgml/maintenance.sgml
> update maintenance for 13.1

- doc/src/sgml/ref/alter_table.sgml
- doc/src/sgml/ref/create_table.sgml
- ref/alter_table.sgml
- ref/create_table.sgml
> update alter/create_table.sgml for 13.1

- doc/src/sgml/ref/pg_basebackup.sgml
> fix typo in pg_basebackup

- doc/src/sgml/ref/pg_dump.sgml
> update pg_dump for 13.1

- doc/src/sgml/plperl.sgml
> update plperl for 13.1

- doc/src/sgml/postgres.sgml
> postgres.sgml の13.1対応です。

- doc/src/sgml/logical-replication.sgml
> logical-replication.sgmlのマージ時に消してしまった箇所の復活

- doc/src/sgml/extend.sgml
> extend.sgmlのマージ時に消してしまった箇所の復活です。

- doc/src/sgml/extend.sgml
> remove extra ws from extend

- doc/src/sgml/intarray.sgml
> 不要なタブを削除しました。

- doc/src/sgml/ref/alter_default_privileges.sgml
- doc/src/sgml/ref/create_table.sgml
- doc/src/sgml/ref/create_trigger.sgml
- doc/src/sgml/ref/ecpg-ref.sgml
- doc/src/sgml/ref/grant.sgml
- doc/src/sgml/ref/prepare.sgml
未翻訳部分を探したら重複していた箇所があったので削除しました。
一部チェックが引っかからないように修正してます。
> マージ等で重複してしまった箇所の削除

- doc/src/sgml/pgtrgm.sgml
> pgtrgm.sgmlの13.1対応のため12.4翻訳を適用したものです。

- doc/src/sgml/func.sgml
- doc/src/sgml/func2.sgml
- doc/src/sgml/func3.sgml
> fix typos in func

- doc/src/sgml/pgtrgm.sgml
pgtrgm.sgml の13.1対応です。
途中版ではなくて最終版のつもりです。もちろん #1934 の結果を使わせてもらっています。
> update pgtrgm for 13.1

- doc/src/sgml/libpq.sgml
https://www.postgresql.org/message-id/flat/alpine.DEB.2.21.1905121032330.27203@lancre
により大量に変換されましたが、そこにあるスクリプトを使用しても
ちゃんと変換できなかったので、別途変換しました。
> functionタグの自動変換

- doc/src/sgml/information_schema.sgml
定形の変換以外に追加の変更はありませんでした。
「INSERT OF」のかなり前からあった間違いを修正しました。
> information_schema.sgml の13.1対応です。

- doc/src/sgml/plpgsql.sgml
https://www.postgresql.jp/document/12/html/plpgsql-porting.html#PLPGSQL-PORTING-APPENDIX
でコメントが見えてたのでCDATAを調整しました。
> plpgsqlの13.1対応です。

- doc/src/sgml/logical-replication.sgml
logical-replication.sgml の 13.1 対応です。
> update logical_replication for 13.1

- doc/src/sgml/ref/alter_opfamily.sgml
- doc/src/sgml/ref/alter_type.sgml
- doc/src/sgml/ref/create_opclass.sgml
- ref/alter_opfamily.sgml
- ref/alter_type.sgml
> update alter type etc. for 13.1

- doc/src/sgml/func.sgml
- doc/src/sgml/func1.sgml
- doc/src/sgml/func2.sgml
- doc/src/sgml/func3.sgml
- doc/src/sgml/func4.sgml
バージョンアップ時に翻訳が消されてしまった部分の復活
タグの変更の追従等です。
> func.sgmlの修正漏れの修正

- doc/src/sgml/libpq.sgml
https://github.com/pgsql-jp/jpug-doc/issues/1967
の修正です。
> Issues1967で指摘いただいたタグミスの修正

- doc/src/sgml/glossary.sgml
glossary.sgmlのUpdateとUserを訳しました。
> translate Update and User in glossary

- doc/src/sgml/plpgsql.sgml
> plpgsql.sgmlのPostgreSQL 13.1対応における追加修正です。

- doc/src/sgml/pageinspect.sgml
pageinspectを使ったことなかったので、自信がないです。
一部表現を統一するように変更してます。
> pageinspect.sgmlの13.1対応です

- doc/src/sgml/charset.sgml
> charset.sgmlの13対応の翻訳

- doc/src/sgml/glossary.sgml
ACID、Aggregate function、Analytic function、Analyzeの翻訳です。
> glossary.sgmlのPostgreSQL 13.1対応です。

- doc/src/sgml/glossary.sgml
> fix typo in glossary

- doc/src/sgml/glossary.sgml
> Schemaの翻訳漏れを修正

- doc/src/sgml/ref/rollback.sgml
- doc/src/sgml/ref/rollback_to.sgml
- doc/src/sgml/ref/savepoint.sgml
- ref/rollback.sgml
- ref/rollback_to.sgml
- ref/savepoint.sgml
> update ref/rollback etc. for 14.0

- doc/src/sgml/typeconv.sgml
- doc/src/sgml/xaggr.sgml
> update typeconv and xaggr

- doc/src/sgml/ref/show.sgml
- doc/src/sgml/ref/start_transaction.sgml
- doc/src/sgml/ref/truncate.sgml
- ref/show.sgml
- ref/start_transaction.sgml
- ref/truncate.sgml
> update ref/show etc. for 14.0

- doc/src/sgml/ref/prepare.sgml
- doc/src/sgml/ref/prepare_transaction.sgml
- doc/src/sgml/ref/reassign_owned.sgml
- doc/src/sgml/ref/refresh_materialized_view.sgml
- ref/prepare_transaction.sgml
- ref/reassign_owned.sgml
- ref/refresh_materialized_view.sgml
> update ref/prepare etc. for 14.0

- doc/src/sgml/ref/security_label.sgml
- doc/src/sgml/ref/set.sgml
- doc/src/sgml/ref/set_session_auth.sgml
- ref/security_label.sgml
- ref/set.sgml
- ref/set_session_auth.sgml
> update ref/set etc. for 14.0

- doc/src/sgml/ref/drop_group.sgml
- doc/src/sgml/ref/drop_owned.sgml
- ref/drop_group.sgml
- ref/drop_owned.sgml
> update ref/drop_group|owned for 14.0

- doc/src/sgml/ref/alter_extension.sgml
- doc/src/sgml/ref/alter_group.sgml
- ref/alter_extension.sgml
- ref/alter_group.sgml
> update ref/alter_extension,group for 14.0

- doc/src/sgml/ref/alter_user.sgml
- doc/src/sgml/ref/alter_user_mapping.sgml
- doc/src/sgml/ref/create_user.sgml
- doc/src/sgml/ref/create_user_mapping.sgml
- doc/src/sgml/ref/createuser.sgml
- doc/src/sgml/ref/drop_user.sgml
- doc/src/sgml/ref/drop_user_mapping.sgml
- doc/src/sgml/ref/dropuser.sgml
- ref/alter_user.sgml
- ref/alter_user_mapping.sgml
- ref/create_user.sgml
- ref/create_user_mapping.sgml
- ref/createuser.sgml
- ref/drop_user.sgml
- ref/drop_user_mapping.sgml
- ref/dropuser.sgml
> update ref/*user* for 14.0

- doc/src/sgml/ref/close.sgml
- doc/src/sgml/ref/comment.sgml
- doc/src/sgml/ref/delete.sgml
- doc/src/sgml/ref/fetch.sgml
- doc/src/sgml/ref/lock.sgml
- ref/close.sgml
- ref/comment.sgml
- ref/delete.sgml
- ref/fetch.sgml
- ref/lock.sgml
> update ref/close etc. for 14.0

- doc/src/sgml/dml.sgml
> update dml for 14.0

- doc/src/sgml/sslinfo.sgml
> update sslinfo for 14.0

- doc/src/sgml/ref/alter_role.sgml
- doc/src/sgml/ref/create_role.sgml
- doc/src/sgml/ref/drop_role.sgml
> update *_role for 14.0

- doc/src/sgml/ref/createdb.sgml
- doc/src/sgml/ref/dropdb.sgml
- ref/createdb.sgml
- ref/dropdb.sgml
> update ref/create|dropdb for 14.0

- doc/src/sgml/ref/alter_aggregate.sgml
- doc/src/sgml/ref/create_aggregate.sgml
- doc/src/sgml/ref/create_cast.sgml
- ref/alter_aggregate.sgml
- ref/create_aggregate.sgml
- ref/create_cast.sgml
> update ref/alter_agg etc. for 14.0

- doc/src/sgml/sepgsql.sgml
> update sepgsql for 14.0

- doc/src/sgml/ref/alter_domain.sgml
- doc/src/sgml/ref/alter_materialized_view.sgml
- doc/src/sgml/ref/create_materialized_view.sgml
- ref/alter_domain.sgml
- ref/alter_materialized_view.sgml
- ref/create_materialized_view.sgml
> update ref/alter_domain etc. for 14.0

- doc/src/sgml/ref/begin.sgml
- doc/src/sgml/ref/end.sgml
- ref/begin.sgml
- ref/end.sgml
> update ref/begin and end for 14.0

- doc/src/sgml/plperl.sgml
- doc/src/sgml/plpython.sgml
- doc/src/sgml/pltcl.sgml
- plperl.sgml
- plpython.sgml
- pltcl.sgml
> update pl* for 14.0

- doc/src/sgml/nls.sgml
- doc/src/sgml/pgrowlocks.sgml
- doc/src/sgml/tsm-system-rows.sgml
- doc/src/sgml/tsm-system-time.sgml
- nls.sgml
- tsm-system-rows.sgml
- tsm-system-time.sgml
> update nls etc. for 14.0

- doc/src/sgml/ref/abort.sgml
- doc/src/sgml/ref/create_opclass.sgml
- ref/abort.sgml
- ref/create_opclass.sgml
> update ref/abort and create_opcls for 14.0

- doc/src/sgml/ref/alter_opfamily.sgml
- doc/src/sgml/ref/create_foreign_table.sgml
- ref/alter_opfamily.sgml
- ref/create_foreign_table.sgml
> update ref/alter_opf etc. for 14.0

- doc/src/sgml/pgcrypto.sgml
> update pgrcypto for 14.0

- doc/src/sgml/file-fdw.sgml
> update file-fwd for 14.0

- doc/src/sgml/ref/create_language.sgml
- doc/src/sgml/ref/create_policy.sgml
- doc/src/sgml/ref/drop_language.sgml
- ref/create_language.sgml
- ref/create_policy.sgml
- ref/drop_language.sgml
ただしref/create_policy.sgmlの原文の変更は今回入ったものではなさそうです。
> update ref/*_lang|policy for 14.0

- doc/src/sgml/ref/pgupgrade.sgml
> update ref/pgupgrade for 14.0

- doc/src/sgml/ref/grant.sgml
- doc/src/sgml/ref/revoke.sgml
- ref/grant.sgml
- ref/revoke.sgml
> update grant and revoke for 14.0

- doc/src/sgml/ref/explain.sgml
> update ref/explain for 14.0

- doc/src/sgml/merge-func.sh
func[0-4].sgmlにレビュー結果を反映させた後、func.sgmlに反映するために使用します。
> split.shで分割されたfunc[0-4].sgmlを結合し、再びfunc.sgmlに戻すスクリプトです。

- doc/src/sgml/pgtrgm.sgml
- doc/src/sgml/syntax.sgml
> update pgtrgm and syntax for 14.0

- doc/src/sgml/ref/set_role.sgml
ref/set_role.sgmlの14.0対応です。
意味不明にコミットが多いのは酒のせいです、多分。
> update set_role for 14.0

- doc/src/sgml/ref/reindexdb.sgml
> update ref/reindexdb for 14.0

- doc/src/sgml/ref/alter_operator.sgml
- doc/src/sgml/ref/create_operator.sgml
- doc/src/sgml/ref/drop_operator.sgml
- ref/alter_operator.sgml
- ref/create_operator.sgml
- ref/drop_operator.sgml
> update ref/*_operator for 14.0

- doc/src/sgml/ref/create_aggregate.sgml
- doc/src/sgml/ref/create_conversion.sgml
ref/create_conversion.sgml の14.0対応です。
ついでに返り値→戻り値もやってます。ref以下では修正したところ以外はすべて戻り値のようでしたので。
> update ref/create_conv etc. for 14.0

- doc/src/sgml/plhandler.sgml
> update plhandler for 14.0

- doc/src/sgml/intarray.sgml
> update intarray for 14.0

- doc/src/sgml/ref/analyze.sgml
- doc/src/sgml/ref/create_database.sgml
- ref/analyze.sgml
- ref/create_database.sgml
> update ref/analyze and create_db for 14.0

- doc/src/sgml/ref/create_transform.sgml
- doc/src/sgml/ref/pg_rewind.sgml
- ref/create_transform.sgml
- ref/pg_rewind.sgml
> update ref/create_trans and pg_rewind for 14.0

- doc/src/sgml/docguide.sgml
> update docguide for 14.0

- doc/src/sgml/query.sgml
> update query for 14.0

- doc/src/sgml/installation.sgml
> update installation for 14.0

- doc/src/sgml/bki.sgml
> update bki for 14.0

- doc/src/sgml/ref/create_view.sgml
- doc/src/sgml/ref/declare.sgml
- ref/create_view.sgml
- ref/declare.sgml
> update ref/create_view and declare for 14.0

- doc/src/sgml/maintenance.sgml
- doc/src/sgml/storage.sgml
- maintenance.sgml
- storage.sgml
> update maintenance and storage for 14.0

- doc/src/sgml/ref/drop_routine.sgml
ref/drop_routine.sgml の14.0対応です。
新しい書き手の方なのでしょうか。（ネイティブでもないのに生意気ですが）今までと違う雰囲気を感じました。
> update drop_routine for 14.0

- doc/src/sgml/ref/copy.sgml
> update ref/copy for 14.0

- doc/src/sgml/ref/alter_publication.sgml
- doc/src/sgml/ref/alter_subscription.sgml
- doc/src/sgml/ref/create_subscription.sgml
- doc/src/sgml/ref/drop_subscription.sgml
- ref/alter_publication.sgml
- ref/alter_subscription.sgml
- ref/create_subscription.sgml
- ref/drop_subscription.sgml
> update ref/*_publication|subscription for 14.0

- doc/src/sgml/user-manag.sgml
> update user-manag for 14.0

- doc/src/sgml/ref/pg_dump.sgml
- doc/src/sgml/ref/pg_dumpall.sgml
- doc/src/sgml/ref/pg_restore.sgml
- ref/pg_dump.sgml
- ref/pg_dumpall.sgml
- ref/pg_restore.sgml
> update ref/pg_dump etc. for 14.0

- doc/src/sgml/ref/drop_statistics.sgml
drop_statistics.sgmlnov14.0対応を行いました。
> drop_statistics.sgmlの翻訳です。

- doc/src/sgml/appendix-obsolete-default-roles.sgml
- doc/src/sgml/appendix-obsolete-pgreceivexlog.sgml
- doc/src/sgml/appendix-obsolete-pgresetxlog.sgml
- doc/src/sgml/appendix-obsolete-pgxlogdump.sgml
- doc/src/sgml/appendix-obsolete-recovery-config.sgml
- doc/src/sgml/appendix-obsolete.sgml
> appendix-obsolete*の14.0対応です。

- doc/src/sgml/ref/alter_type.sgml
alter_type.sgmlのPostgreSQL14.0の対応です。
> alter_type.sgml modified::

- doc/src/sgml/parallel.sgml
diffのほとんどが関係詞whichをthatに修正されたもので、内容の変更を伴うものは1文だけでした。
> parallel.sgmlのPostgreSQL14.0対応です。

- doc/src/sgml/ref/pg_basebackup.sgml
> マージミスによる重複の削除

- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs0.sgml
- doc/src/sgml/catalogs1.sgml
- doc/src/sgml/catalogs2.sgml
- doc/src/sgml/catalogs3.sgml
- doc/src/sgml/catalogs4.sgml
- doc/src/sgml/merge-catalogs.sh
レビューはcatalogs[0-4].sgmlに対して行ってください。
> catalogs.sgmlのPostgreSQL 14.0対応です。

- doc/src/sgml/ref/reindex.sgml
> update ref/reindex for 14.0

- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs0.sgml
- doc/src/sgml/catalogs1.sgml
- doc/src/sgml/catalogs2.sgml
- doc/src/sgml/catalogs3.sgml
- doc/src/sgml/catalogs4.sgml
- doc/src/sgml/pgbuffercache.sgml
- doc/src/sgml/pgstatstatements.sgml
14.0版の修正です。詳細は #2039 のコメントを参照してください。
> references を参照先にする

- doc/src/sgml/ref/alter_index.sgml
- doc/src/sgml/ref/create_index.sgml
- doc/src/sgml/ref/drop_index.sgml
- ref/alter_index.sgml
- ref/create_index.sgml
- ref/drop_index.sgml
> update ref/*_index.sgml for 14.0

- doc/src/sgml/config.sgml
- doc/src/sgml/config1.sgml
- doc/src/sgml/logical-replication.sgml
- doc/src/sgml/ref/create_publication.sgml
- doc/src/sgml/ref/create_subscription.sgml
サブスクライバー（伸ばす）に統一しました。
#2088 で話題になった件です。
> fix translation of subscriber

- doc/src/sgml/ref/set_transaction.sgml
ref/set_transaction.sgml の14.0対応です。
> update ref/set_transaction for 14.0

- doc/src/sgml/acronyms.sgml
"TLS"が追加されていますが、良い和訳が思いつかなかったのでそのままにしています。
> acronyms.sgmlのPostgreSQL 14.0対応です。

- doc/src/sgml/ref/vacuumdb.sgml
> update vacuumdb for 14.0

- doc/src/sgml/install-binaries.sgml
> install-binaries.sgmlのPostgreSQL 14.0対応です。

- doc/src/sgml/btree.sgml
- doc/src/sgml/gin.sgml
- doc/src/sgml/ref/create_trigger.sgml
- doc/src/sgml/runtime.sgml
マージミスにより原文の更新がおかしかった箇所を修正しました。
> マージミスによる重複その他の修正

- doc/src/sgml/install-windows.sgml
install-windows.sgml の14.0対応です。
> update install-windows for 14.0

- doc/src/sgml/ref/alter_statistics.sgml
- doc/src/sgml/ref/create_statistics.sgml
- ref/alter_statistics.sgml
- ref/create_statistics.sgml
> update ref/*_statistics for 14.0

- doc/src/sgml/ref/vacuum.sgml
> update ref/vacuum for 14.0

- doc/src/sgml/ref/alter_collation.sgml
- doc/src/sgml/ref/call.sgml
- ref/alter_collation.sgml
- ref/call.sgml
> update call etc. for 14.0

- doc/src/sgml/pgsurgery.sgml
> pgsurgery.sgmlのPostgreSQL 14.0対応です。

- doc/src/sgml/arch-dev.sgml
> update arch-dev for 14.0

- doc/src/sgml/ref/drop_procedure.sgml
行末の余分な空白の削除
他に先にやるべきことがありそうな気がしますが、気づいてしまったので。
> remove extra ws

- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs2.sgml
- doc/src/sgml/high-availability.sgml
- doc/src/sgml/ref/create_collation.sgml
- doc/src/sgml/ref/psql-ref.sgml
#2166 のバックポートです。
#2165 の修正を含みます。
> 誤字修正 #2166の13へのバックポート

- doc/src/sgml/sources.sgml
> fix mistranslations

- doc/src/sgml/ref/select.sgml
> update ref/select for 14.0

- doc/src/sgml/json.sgml
> update json for 14.0

- doc/src/sgml/ref/create_table.sgml
- doc/src/sgml/ref/drop_table.sgml
- ref/create_table.sgml
- ref/drop_table.sgml
> update create/drop_table for 14.0

- doc/src/sgml/ref/psql-ref.sgml
> update psql-ref for 14.0

- doc/src/sgml/ref/create_procedure.sgml
ref/create_procedure.sgml の１４．０対応です。
> update create_procedure for 14.0

- doc/src/sgml/ref/create_function.sgml
ref/create_function.sgmlの１４．０対応です。
> update create_function for 14.0

- doc/src/sgml/extend.sgml
> fix translation about extension

- doc/src/sgml/ref/create_trigger.sgml
ref/create_trigger.sgml の 14.0 対応です。
> update create_trigger for 14.0

- doc/src/sgml/gist.sgml
> update gist for 14.0

- doc/src/sgml/ref/create_type.sgml
ref/create_type.sgml の14.0対応です。
> update create_type for 14.0 

- doc/src/sgml/spgist.sgml
> update spgist for 14.0

- doc/src/sgml/ref/pgbench.sgml
> remove extra white spaces

- doc/src/sgml/gin.sgml
遅くなりまして申し訳ありません。レビューをお願いいたします。
> gin.sgmlのPostgreSQL 14.0対応です。

- doc/src/sgml/ecpg.sgml
> update ecpg for 14.0

- doc/src/sgml/datatype.sgml
#2228 のMasatoshi Fukunagaさんの指摘に対応しました。
（#2234 のv13へのバックポート）
> fix typo in datatype for v13

- doc/src/sgml/datatype.sgml
#2228 のMasatoshi Fukunagaさんの指摘に対応しました。
（#2234 のv12へのバックポート）
> fix typo in datatype for v12

- doc/src/sgml/datatype.sgml
#2228 のMasatoshi Fukunagaさんの指摘に対応しました。 
（#2234 のv10へのバックポート）
> fix typo in datatype for v10

- doc/src/sgml/datatype.sgml
#2228 のMasatoshi Fukunagaさんの指摘に対応しました。 
（#2234 のv11へのバックポート）
> fix typo in datatype for v11

- doc/src/sgml/monitoring.sgml
> remove extra ws in monitoring

- doc/src/sgml/brin.sgml
brin.sgmlの修正を行いましたのでレビューをお願いいたします。
意味が取りづらい部分も多かったので、気になる部分は指摘いただければと思います。
> brin.sgmlのPostgreSQL 14.0対応です。

- doc/src/sgml/brin.sgml
pull request #2225の斉藤さんの指摘に対応しました。
> brin.sgmlの追加修正です。

- doc/src/sgml/brin.sgml
#2225 で斉藤さんが後回しでもいいかもと言っていた、表の中身の翻訳です。
が、今回は議論の余地がなさそうな部分を先行してやっています。
> translate table contents in brin - part1

- doc/src/sgml/btree.sgml
> remove extra ws in btree of 14.0

- doc/src/sgml/rangetypes.sgml
> rangetypes.sgmlの14.0対応です

- doc/src/sgml/gin.sgml
> 14のマージ時に適用されてなかった修正

- doc/src/sgml/config.sgml
- doc/src/sgml/config1.sgml
「プ」が１つ多いです。
あと
クエリプランナ->問い合わせプランナ
もやってます。少なくともこのファイル内では問い合わせプランナが多数派のようですから。
> fix typos in config of 14.0

- doc/src/sgml/jpug-doc.sgml
> fix sra oss company name typo.

- doc/src/sgml/high-availability.sgml
> タグ数チェック関連で発見箇所の修正

- doc/src/sgml/btree.sgml
> fix indexterm in btree

- doc/src/sgml/ref/release_savepoint.sgml
- doc/src/sgml/ref/savepoint.sgml
以下のファイルの14.5対応です。
- ref/release_savepoint.sgml
- ref/savepoint.sgml
> update *savepoint for 14.5

- doc/src/sgml/ref/create_foreign_table.sgml
ref/create_foreign_table.sgml の１４．５対応です。
> update create f. t. for 14.5

- doc/src/sgml/ref/savepoint.sgml
> remove extra ws in savepoint

- doc/src/sgml/extend.sgml
> extend.sgmlの14.5対応です

- doc/src/sgml/ref/pg_dump.sgml
> pg_dumpの14.5対応です

- doc/src/sgml/plhandler.sgml
> plhandler.sgmlの14.5対応です

- doc/src/sgml/ref/alter_type.sgml
> alter_type.sgmlの14.5対応です

- doc/src/sgml/ref/psql-ref.sgml
> update psql-ref for 14.5

- doc/src/sgml/spi.sgml
> update spi for 14.5

- doc/src/sgml/arch-dev.sgml
arch-dev.sgml の14.5対応です。
が、翻訳には影響しない英語の誤記修正でした。
> update arch-dev for 14.5

- doc/src/sgml/json.sgml
> update json for 14.5

- doc/src/sgml/ref/pg_restore.sgml
> pg_restore.sgmlの14.5対応です

- doc/src/sgml/ref/pg_dumpall.sgml
> pg_dumpallの14.5対応です

- doc/src/sgml/ref/pgupgrade.sgml
> pgupgrade.sgmlの14.5対応です

- doc/src/sgml/textsearch.sgml
> textsearch.sgmlの14.5対応です

- doc/src/sgml/install-windows.sgml
install-windows.sgml の14.5対応です。
> update install-windows for 14.5

- doc/src/sgml/plpgsql.sgml
14.0からの変更は1行ですが、原文とのdiffのために修正を入れています。
> plpgsql.sgmlの14.5対応です

- doc/src/sgml/maintenance.sgml
> update maintenance for 14.5

- doc/src/sgml/ref/analyze.sgml
> update analyze for 14.5

- doc/src/sgml/queries.sgml
> queries.sgmlの14.5対応です

- doc/src/sgml/ref/refresh_materialized_view.sgml
ref/refresh_materialized_view.sgml の 14.5対応です。
> update refresh_mat_view for 14.5

- doc/src/sgml/ref/drop_extension.sgml
ref/drop_extension.sgml の 14.5 対応です。
> update drop_extension for 14.5

- doc/src/sgml/ref/pg_receivewal.sgml
ref/pg_receivewal.sgml の 14.5 対応です。
> update pg_recwal for 14.5

- doc/src/sgml/limits.sgml
> update limits for 14.5

- doc/src/sgml/notation.sgml
> update notation for 14.5

- doc/src/sgml/rules.sgml
しかし、新規の翻訳対象はありませんでした。
既存の修正を入れてます。
> rules.sgmlの14.5対応です。

- doc/src/sgml/gist.sgml
> update gist for 14.5

- src/backend/catalog/sql_features.txt.ja
- src/backend/utils/errcodes.txt.ja
そう言えば以下のファイルも更新しておかないといけないのでした。
> update some ja text files

- doc/src/sgml/ref/reindex.sgml
- doc/src/sgml/ref/reindexdb.sgml
- doc/src/sgml/ref/set.sgml
以下のファイルの14.5対応です。
- ref/reindex.sgml
- ref/reindexdb.sgml
- ref/set.sgml
> update reindex etc for 14.5

- doc/src/sgml/pltcl.sgml
> update pltcl for 14.5

- doc/src/sgml/charset.sgml
複数の点で標準から外れている部分を見つけてしまったので、、、
- 行頭に不要な空白がある
- 「。」で改行していない。
- and soの訳がおかしい
> add new lines in charset

- doc/src/sgml/ddl.sgml
fix #2338
typo修正
分れた説明を原文に近づけて修正
> ddl.sgmlの修正

- doc/src/sgml/high-availability.sgml
indextermの並びを英日に修正。
不要なコメントを削除。
> high-availabilityの14.5（修正漏れを修正）対応です

- doc/src/sgml/ddl.sgml
1点指摘いただいていたポイントを反映していない状態でマージしてしまいました。
反対意見がなければマージをお願いします。
> ISSUES2338で漏れていた修正点の対応。

- doc/src/sgml/ref/alter_subscription.sgml
ref/alter_subscription.sgml の14.5対応です。
> update alter_subscr for 14.5

- doc/src/sgml/ref/comment.sgml
> update comment for 14.5

- doc/src/sgml/advanced.sgml
advanced.sgml で文末で改行していない箇所に気づきましたので。
ついでに見かけた045->45もやってます。
> add new lines in advanced

- doc/src/sgml/xfunc.sgml
対応し忘れる前にPRを上げておきます。
https://github.com/pgsql-jp/jpug-doc/pull/2358
がクローズし次第reviewをお願いします。
> PR2358で話題になったインクルードをincludeに変換

- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs0.sgml
- doc/src/sgml/catalogs4.sgml
> catalogs.sgmlのマッチ度コメント削除

- doc/src/sgml/rangetypes.sgml
翻訳抜けを修正。
indextermの修正漏れを修正。
ハイフンの修正。
> rangetype.sgmlの変更漏れを修正

- doc/src/sgml/config.sgml
- doc/src/sgml/config3.sgml
- doc/src/sgml/datatype.sgml
- doc/src/sgml/func.sgml
- doc/src/sgml/func3.sgml
> add new lines in some files

- doc/src/sgml/release-14.sgml
release-14.sgml の 14.5 対応版です。表現の不統一があったり原文にないプラスアルファなどがありますが、一旦プルリクエストさせてください。
> update release-14.sgml for 14.5

- doc/src/sgml/amcheck.sgml
- doc/src/sgml/pgtrgm.sgml
- doc/src/sgml/plperl.sgml
- doc/src/sgml/ref/prepare.sgml
- doc/src/sgml/ref/select.sgml
- doc/src/sgml/regress.sgml
- doc/src/sgml/sepgsql.sgml
> ブロックが別の文を原文に近い形に修正

- doc/src/sgml/trigger.sgml
- doc/src/sgml/typeconv.sgml
> doc_ja_15と余計な差分を減らすための修正

- doc/src/sgml/release-14.sgml
> remove extra ws in relnote of 14.5

- doc/src/sgml/ref/fetch.sgml
- doc/src/sgml/ref/insert.sgml
> タグチェック関連で文の修正

- doc/src/sgml/installation.sgml
- doc/src/sgml/lobj.sgml
- doc/src/sgml/xfunc.sgml
- doc/src/sgml/xplang.sgml
文を見直して修正が入っています。
#2351の修正を含みます
> ブロックが別の文を原文に近い形に修正２

- doc/src/sgml/ref/values.sgml
> update values for 15.0

- doc/src/sgml/ref/vacuum.sgml
- doc/src/sgml/ref/vacuumdb.sgml
以下のファイルの１５．０対応です。
- ref/vacuum.sgml
- ref/vacuumdb.sgml
> update vacuum and vacuumdb for 15.0

- doc/src/sgml/datetime.sgml
> datetime.sgmlの15.0対応です

- doc/src/sgml/extend.sgml
> extend.sgmlの15.0対応です

- doc/src/sgml/xml2.sgml
xml2.sgml の15.0対応です。
厳密に言うと、↑は正しくなくて、
英語の修正は日本語訳には影響を与えない部分でした。が、日本語訳の改善をしているつもりです。
という状況です。
> update xml2 for 15.0

- doc/src/sgml/ref/set_transaction.sgml
ref/set_transaction.sgml の15.0対応です。
> update set_transaction for 15.0

- src/backend/catalog/sql_features.txt.ja
src/backend/catalog/sql_features.txt.ja の15.0対応です。
（mergeとかありますので）
> update sql_features for 15.0

- doc/src/sgml/ref/alter_collation.sgml
ref/alter_collation.sgml の15.0対応です。
> update alter_collation for 15.0

- doc/src/sgml/ref/set.sgml
> update set for 15.0

- doc/src/sgml/ref/reindex.sgml
> update reindex for 15.0

- doc/src/sgml/tableam.sgml
> tableam.sgmlの15.0対応です

- doc/src/sgml/syntax.sgml
syntax.sgmlの15.0対応です。
原文の変更は訳に影響のないものでしたので、既存の訳の復活です。
> update syntax for 15.0

- doc/src/sgml/ref/lock.sgml
> update lock for 15.0

- doc/src/sgml/ref/create_transform.sgml
- doc/src/sgml/ref/drop_transform.sgml
- ref/create_transform.sgml
- ref/drop_transform.sgml
> update *_transform for 15.0

- doc/src/sgml/ref/postgres-ref.sgml
ref/postgres-ref.sgml の15.0対応です。
> update postgres-ref for 15.0

- doc/src/sgml/plpgsql.sgml
移動したところがありますが、変更したところは多くありません。
> plpgsql.sgmlの15.0対応です

- doc/src/sgml/pgrowlocks.sgml
> update pgrowlocks for 15.0

- doc/src/sgml/ref/move.sgml
- doc/src/sgml/ref/pg_checksums.sgml
- ref/move.sgml
- ref/pg_checksums.sgml
> update for 15.0 - part5

- doc/src/sgml/ref/pg_rewind.sgml
> update pg_rewind for 15.0

- doc/src/sgml/hstore.sgml
> update hstore for 15.0

- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs3.sgml
catalogs2.sgml部分のみの作業で、修正箇所は一箇所だけでした。
catalogs.sgmlの修正はこれが最後のパートです。
> catalogs.sgmlのPostgreSQL 15.0対応です(パート3)

- doc/src/sgml/ref/alter_system.sgml
ref/alter_system.sgmlの15.0対応です。
> update alter_system for 15.0

- doc/src/sgml/json.sgml
> update json for 15.0

- doc/src/sgml/monitoring.sgml
#2476 の田中さんによる指摘に入っていた修正を含みます。
表現の統一も入れています。
> monitoring.sgmlの15.0対応です

- doc/src/sgml/jpug-doc.sgml
参考になる言い回しが無く、ひとまず作成して見ましたが、ご意見いただければと思います。
> みんなの機械翻訳の謝辞

- doc/src/sgml/ref/drop_extension.sgml
- doc/src/sgml/ref/drop_owned.sgml
- ref/drop_extension.sgml
- ref/drop_owned.sgml
> update drop_* for 15.0

- doc/src/sgml/query.sgml
> update query for 15.0

- doc/src/sgml/ref/insert.sgml
> update insert for 15.0

- doc/src/sgml/archive-modules.sgml
> archive-modules.sgmlのPostgreSQL 15.0対応です。

- doc/src/sgml/amcheck.sgml
差分対応と、typo修正、他の箇所との訳語の統一、分かりやすい訳語への変更をしました。
> Update amcheck for 15.0

- doc/src/sgml/high-availability.sgml
> high-availability.sgmlの15.0対応です

- doc/src/sgml/ref/pg_ctl-ref.sgml
https://github.com/pgsql-jp/jpug-doc/pull/2523
で話題になった件をその他の箇所に適用しました。
> 回転をローテーションに変更

- doc/src/sgml/tablesample-method.sgml
> offset numberをオフセット番号へ（PR2520関連）

- doc/src/sgml/maintenance.sgml
> update maintenance for 15.0

- doc/src/sgml/ref/create_index.sgml
ref/create_index.sgml の15.0対応です。
> update create_index for 15.0

- doc/src/sgml/ref/create_policy.sgml
ref/create_policy.sgml の15.0対応です。
> update create_policy for 15.0

- doc/src/sgml/basic-archive.sgml
> basic-archive.sgmlのPostgreSQL 15.0対応です。

- doc/src/sgml/ref/alter_trigger.sgml
- doc/src/sgml/ref/create_trigger.sgml
- ref/alter_trigger.sgml
- ref/create_trigger.sgml
> update *_trigger for 15.0

- doc/src/sgml/user-manag.sgml
> update user-manag for 15.0

- doc/src/sgml/extend.sgml
> 「メークファイル」を"makefile"に変更します。

- doc/src/sgml/pgbuffercache.sgml
- doc/src/sgml/pgfreespacemap.sgml
- doc/src/sgml/pgvisibility.sgml
- pgbuffercache.sgml
- pgfreespacemap.sgml
- pgvisibility.sgml
> update for 15.0 - part 8

- doc/src/sgml/ref/pg_amcheck.sgml
ref/pg_amcheck.sgmlの15.0対応です。
トースト -> TOASTも合わせてやっていますが、余計ならお知らせください。
> update pg_amcheck for 15.0

- doc/src/sgml/ltree.sgml
- doc/src/sgml/manage-ag.sgml
> update for 15.0 - part 9

- doc/src/sgml/lo.sgml
> update lo for 15.0

- doc/src/sgml/custom-scan.sgml
> update custom-scan for 15.0

- doc/src/sgml/pageinspect.sgml
> pageinspect.sgmlの15.0対応です。

- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs1.sgml
- doc/src/sgml/catalogs2.sgml
一部15.0に追随していないところがあったので修正しました。
catalogs1.sgmlは./split-catalogs.sh を実行したら発生しました。
> catalogs.sgmlの修正

- doc/src/sgml/ref/alter_table.sgml
- doc/src/sgml/ref/create_table.sgml
- doc/src/sgml/ref/create_table_as.sgml
- ref/alter_table.sgml
- ref/create_table.sgml
- ref/create_table_as.sgml
> update *_table* for 15.0

- doc/src/sgml/ref/alter_view.sgml
- doc/src/sgml/ref/create_view.sgml
- alter_view.sgml
- create_view.sgml
> update *_view for 15.0

- doc/src/sgml/ref/cluster.sgml
> update cluster for 15.0

- doc/src/sgml/ref/reindex.sgml
リンクの表記が英語のままになっている箇所を、日本語の表記になるように修正しました。
> セクションへのリンクが日本語表示になるよう修正

- doc/src/sgml/ref/initdb.sgml
> update initdb for 15.0

- doc/src/sgml/ref/alter_publication.sgml
- doc/src/sgml/ref/create_publication.sgml
- ref/alter_publication.sgml
- ref/create_publication.sgml
> update *_publication for 15.0

- doc/src/sgml/regress.sgml
> regress.sgmlの15.0対応です

- doc/src/sgml/ref/pg_basebackup.sgml
ref/pg_basebackup.sgml の15.0対応です。
> update pg_basebackup for 15.0

- doc/src/sgml/ref/alter_subscription.sgml
- doc/src/sgml/ref/create_subscription.sgml
- ref/alter_subscription.sgml
- ref/create_subscription.sgml
> update *_subscription for 15.0

- doc/src/sgml/pgwalinspect.sgml
> pgwalinspect.sgmlのPostgreSQL 15.0対応です。

- doc/src/sgml/jit.sgml
> JIT説明の誤記を修正した

- doc/src/sgml/release-15.sgml
遅くなりました。release-15 を一通り対応しました。文末の表現のゆれ(ぶれ)などがあるかと思いますが一度 pull request をしてレビューしていただくことを優先します。
> Update for release-15

- doc/src/sgml/ref/select.sgml
> update select for 15.0

- doc/src/sgml/ref/pg_receivewal.sgml
ref/pg_receivewal.sgml の15.0対応です。
> update pg_receivewal for 15.0

- doc/src/sgml/ref/psql-ref.sgml
ref/psql-ref.sgml の15.0対応です。
すみません。宣言してやったつもりになっていたのですが、やってなかったようです。
> update psql-ref for 15.0

- doc/src/sgml/ref/merge.sgml
> merge.sgmlの15.0対応です

- doc/src/sgml/ref/pgbench.sgml
> pgbench.sgmlの15.0対応です

- doc/src/sgml/jit.sgml
- doc/src/sgml/ref/alter_collation.sgml
- doc/src/sgml/ref/alter_table.sgml
- doc/src/sgml/ref/create_aggregate.sgml
- doc/src/sgml/ref/create_index.sgml
- doc/src/sgml/ref/create_subscription.sgml
- doc/src/sgml/ref/create_table.sgml
- doc/src/sgml/ref/create_type.sgml
- doc/src/sgml/ref/declare.sgml
- doc/src/sgml/ref/insert.sgml
- doc/src/sgml/ref/pg_dump.sgml
- doc/src/sgml/ref/postgres-ref.sgml
- doc/src/sgml/ref/psql-ref.sgml
- doc/src/sgml/ref/select.sgml
> xreflabelの翻訳追加

- doc/src/sgml/advanced.sgml
誤記と思われるものを見つけました。 #2613 とはぶつかってないです。
> fix typo in advanced

- doc/src/sgml/ref/move.sgml
- doc/src/sgml/ref/pg_amcheck.sgml
- doc/src/sgml/ref/prepare.sgml
以下のファイルの15.3対応です。
- ref/move.sgml
- ref/pg_amcheck.sgml
> update for 15.3 - part 1

- doc/src/sgml/ref/alter_role.sgml
- doc/src/sgml/ref/create_subscription.sgml
- doc/src/sgml/ref/fetch.sgml
以下のファイルの15.3対応です。
- ref/create_subscription.sgml
- ref/fetch.sgml
> update for 15.3 - part 2

- doc/src/sgml/ref/explain.sgml
> update explain for 15.3

- doc/src/sgml/pltcl.sgml
> update pltcl for 15.3

- doc/src/sgml/ltree.sgml
> update ltree for 15.3

- doc/src/sgml/spi.sgml
- doc/src/sgml/textsearch.sgml
以下のファイルの15.3対応です。
- spi.sgml
- textsearch.sgml
> update for 15.3 - part 3

- doc/src/sgml/plpython.sgml
> update plpython for 15.3

- doc/src/sgml/backup.sgml
変更が必要ないはずの下訳の修正が入ってしまってましたのを削除しました。
> backup.sgmlの15.3対応です

- doc/src/sgml/ref/create_publication.sgml
ref/create_publication.sgmlの15.3対応です。
> update create_publication for 15.3

- .github/workflows/pr-label.yml
> github-script のバージョンアップ対応修正

- doc/src/sgml/ref/create_role.sgml
ref/create_role.sgml の15.3対応です。
> update create_role for 15.3

- doc/src/sgml/sources.sgml
> sources.sgmlの15.3対応です

- doc/src/sgml/ref/comment.sgml
> update comment for 15.3

- doc/src/sgml/ref/createuser.sgml
ref/createuser.sgml の15.3対応です。
> update createuser for 15.3

- doc/src/sgml/plperl.sgml
> update plperl for 15.3

- doc/src/sgml/install-windows.sgml
・冗長表現の見直し（例：することができます⇒できます）
・（）を全角に統一した
・漢字の開きの見直し（例：の様に⇒のように）
・（）内の句点削除
　　原文にもピリオドがなかったことを踏まえて削除しました。
・助詞の繰り返しの見直し
> 第18章の文章表現を見直しました。

- doc/src/sgml/ref/create_table.sgml
ref/create_table.sgml の15.3対応です。
> update create_table for 15.3

- doc/src/sgml/release-15.sgml
15.3のリリース情報を翻訳しました。とりあえず一通りざっと作業した状態です。
> Update for release-15 (15.3)

- doc/src/sgml/ref/security_label.sgml
ref/security_label.sgml の15.3対応です。
> update security_label for 15.3

- doc/src/sgml/ref/merge.sgml
> update merge for 15.3

- doc/src/sgml/manage-ag.sgml
・冗長表現の見直し（例：できるようなります⇒できます）
・（）を全角に統一した
・助詞の見直し
> 第23章の文章表現を見直しました。

- doc/src/sgml/ref/alter_table.sgml
ref/alter_table.sgml の15.3対応です。
> update alter_table for 15.3

- doc/src/sgml/parallel.sgml
> update parallel for 15.3

- doc/src/sgml/client-auth.sgml
・冗長表現の見直し（例：することができます⇒できます）
・（）を全角に統一した
・漢字の開きの見直し（例：下さい⇒ください）
・助詞の繰り返しの見直し
・送り仮名の見直し（例：行なわれます⇒行われます）
・稼動⇒稼働
・読点の統一（,⇒、）
> 第21章の文章表現を見直しました。

- doc/src/sgml/user-manag.sgml
user-manag.sgml の15.3対応です。
「CREATEROLE権限を持つユーザは」で始まる最後の段落は（機械翻訳で基本的にはいいのではないかと思うのですが）よく分かってないです。
> update user-manag for 15.3

- doc/src/sgml/logical-replication.sgml
logical-replication.sgml の15.3対応です。
> update logical-replication for 15.3

- doc/src/sgml/wal.sgml
> オプション(--wal-segsize)間違い修正

- doc/src/sgml/system-views.sgml
Fixed #2685
#2685 のご指摘の修正と表の中の説明らしくなるように修正しました。
> pg_replication_slots viewの説明修正

- doc/src/sgml/history.sgml
- doc/src/sgml/storage.sgml
以下のファイルの15.4対応です。
- history.sgml
- storage.sgml
> update hstory and storage for 15.4

- doc/src/sgml/custom-scan.sgml
> update custom_scan for 15.4

- doc/src/sgml/ref/create_statistics.sgml
- doc/src/sgml/ref/drop_subscription.sgml
以下のファイルの15.4対応です。
- ref/create_statistics.sgml
- ref/drop_subscription.sgml
> update create_stat and drop_subsc for 15.4

- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs0.sgml
- doc/src/sgml/system-views.sgml
#1980 対応をする予定ですが、こちらは量が多いので、先に明確な間違いを修正しました。
> catalogs.sgmlとsystem-views.sgmlの翻訳漏れとカッコ修正

- doc/src/sgml/catalogs.sgml
- doc/src/sgml/system-views.sgml
#1980対応の途中で見つけたおかしなところを先に修正しました。
> catalogs.sgmlとsystem-views.sgmlの修正

- doc/src/sgml/spi.sgml
> update spi for 15.4

- doc/src/sgml/earthdistance.sgml
- doc/src/sgml/file-fdw.sgml
- doc/src/sgml/intagg.sgml
- doc/src/sgml/lobj.sgml
- earthdistance.sgml
- file-fdw.sgml
- intagg.sgml
- lobj.sgml
> update lobj etc. for 16.0

- doc/src/sgml/ref/alter_aggregate.sgml
- doc/src/sgml/ref/alter_conversion.sgml
- ref/alter_aggregate.sgml
- ref/alter_conversion.sgml
> update alter_agg, conv for 16.0

- doc/src/sgml/ref/alter_domain.sgml
- doc/src/sgml/ref/create_domain.sgml
- ref/alter_domain.sgml
- ref/create_domain.sgml
> update *_domain for 16.0

- doc/src/sgml/ref/alter_opclass.sgml
- doc/src/sgml/ref/alter_operator.sgml
- doc/src/sgml/ref/alter_procedure.sgml
- ref/alter_opclass.sgml
- ref/alter_operator.sgml
- ref/alter_operator.sgml
> update alter_* x 3

- doc/src/sgml/test-decoding.sgml
test-decoding.sgml の16.0対応です。
（というよりも新しいマシンのテストの方が主目的だったりします。）
> update test-decoding for 16.0

- doc/src/sgml/tcn.sgml
- doc/src/sgml/tsm-system-rows.sgml
- doc/src/sgml/tsm-system-time.sgml
- tcn.sgml
- tsm-system-rows.sgml
- tsm-system-time.sgml
> update for 16.0 - new part 2

- doc/src/sgml/sourcerepo.sgml
- doc/src/sgml/sslinfo.sgml
- doc/src/sgml/unaccent.sgml
- doc/src/sgml/uuid-ossp.sgml
- sourcerepo.sgml
- sslinfo.sgml
- unaccent.sgml
- uuid-ossp.sgml
> update for 16.0 - new part 3

- doc/src/sgml/ltree.sgml
- doc/src/sgml/maintenance.sgml
- doc/src/sgml/oldsnapshot.sgml
- doc/src/sgml/passwordcheck.sgml
- doc/src/sgml/pgfreespacemap.sgml
- doc/src/sgml/pgprewarm.sgml
- ltree.sgml
- maintenance.sgml
- oldsnapshot.sgml
- passwordcheck.sgml
- pgfreespacemap.sgml
- pgprewarm.sgml
> update for 16.0 - new part 4

- doc/src/sgml/ref/alter_schema.sgml
- doc/src/sgml/ref/alter_server.sgml
- doc/src/sgml/ref/alter_tablespace.sgml
- doc/src/sgml/ref/create_schema.sgml
- ref/alter_schema.sgml
- ref/alter_server.sgml
- ref/alter_tablespace.sgml
- ref/create_schema.sgml
> update for 16.0 - new part 1

- doc/src/sgml/dict-int.sgml
- doc/src/sgml/dict-xsyn.sgml
- doc/src/sgml/hstore.sgml
- doc/src/sgml/intarray.sgml
- doc/src/sgml/isn.sgml
- doc/src/sgml/lo.sgml
- doc/src/sgml/pgrowlocks.sgml
- dict-int.sgml
- dict-xsyn.sgml
- hstore.sgml
- intarray.sgml
- isn.sgml
- lo.sgml
> update for 16.0 - new part 5

- doc/src/sgml/ref/alter_type.sgml
- doc/src/sgml/ref/create_type.sgml
- ref/alter_type.sgml
- ref/create_type.sgml
> update *_type for 16.0

- doc/src/sgml/ref/alter_foreign_table.sgml
- doc/src/sgml/ref/alter_group.sgml
- doc/src/sgml/ref/alter_large_object.sgml
- doc/src/sgml/ref/alter_materialized_view.sgml
- doc/src/sgml/ref/alter_view.sgml
- ref/alter_foreign_table.sgml
- ref/alter_group.sgml
- ref/alter_large_object.sgml
- ref/alter_materialized_view.sgml
- ref/alter_view.sgml
> update alter_* for 16.0

- doc/src/sgml/ref/analyze.sgml
> update analyze for 16.0

- doc/src/sgml/pgstattuple.sgml
- doc/src/sgml/pgsurgery.sgml
- doc/src/sgml/pgvisibility.sgml
- pgstattuple.sgml
- pgsurgery.sgml
- pgvisibility.sgml
> update for 16.0 - new part 7

- doc/src/sgml/seg.sgml
- doc/src/sgml/sepgsql.sgml
- doc/src/sgml/tablefunc.sgml
- doc/src/sgml/xml2.sgml
- seg.sgml
- sepgsql.sgml
- tablefunc.sgml
- xml2.sgml
> update for 16.0 - new part 8

- doc/src/sgml/auth-delay.sgml
- doc/src/sgml/auto-explain.sgml
- doc/src/sgml/basebackup-to-shell.sgml
- doc/src/sgml/basic-archive.sgml
- doc/src/sgml/bloom.sgml
- doc/src/sgml/btree-gin.sgml
- doc/src/sgml/btree-gist.sgml
auth-delay.sgml
auto-explain.sgml
basebackup-to-shell.sgml
basic-archive.sgml
bloom.sgml
btree-gin.sgml
btree-gist.sgml
> title更新16.0

- doc/src/sgml/ref/pg_dumpall.sgml
- doc/src/sgml/ref/pg_receivewal.sgml
- doc/src/sgml/ref/pg_recvlogical.sgml
- doc/src/sgml/ref/pg_rewind.sgml
- doc/src/sgml/ref/pg_verifybackup.sgml
- ref/pg_dumpall.sgml
- ref/pg_receivewal.sgml
- ref/pg_recvlogical.sgml
- ref/pg_rewind.sgml
- ref/pg_verifybackup.sgml
> update pg_* for 16.0

- doc/src/sgml/ref/alter_statistics.sgml
- doc/src/sgml/ref/create_statistics.sgml
- alter_statistics.sgml
- ref/create_statistics.sgml
> update *_stat for 16.0

- doc/src/sgml/citext.sgml
- doc/src/sgml/custom-rmgr.sgml
- doc/src/sgml/dblink.sgml
- citext.sgml
- custom-rmgr.sgml
- dblink.sgml
> update for 16.0 - new part 9

- doc/src/sgml/pgtrgm.sgml
> update pgtrgm for 16.0

- doc/src/sgml/ref/pgupgrade.sgml
ref/pgupgrade.sgml の 16.0 対応です。
> update pgupgrade for 16.0

- doc/src/sgml/features.sgml
> update feature for 16.0

- doc/src/sgml/contrib-spi.sgml
- doc/src/sgml/fdwhandler.sgml
- doc/src/sgml/json.sgml
- contrib-spi.sgml
- fdwhandler.sgml
- json.sgml
> update for 16.0 - new part 10

- doc/src/sgml/cube.sgml
> update cube for 16.0

- doc/src/sgml/ref/declare.sgml
- doc/src/sgml/ref/lock.sgml
- doc/src/sgml/ref/prepare.sgml
- ref/declare.sgml
- ref/lock.sgml
> update for 16.0 - new part 11

- doc/src/sgml/ref/alter_function.sgml
- doc/src/sgml/ref/create_function.sgml
- ref/alter_function.sgml
- ref/create_function.sgml
> update *_function for 16.0

- doc/src/sgml/ref/pg_basebackup.sgml
ref/pg_basebackup.sgml の 16.0 対応です。
> update pg_basebackup for 16.0

- doc/src/sgml/ref/postgres-ref.sgml
ref/postgres-ref.sgml の 16.0 対応です。
> update postgres-ref for 16.0

- doc/src/sgml/external-projects.sgml
external-projects.sgml の 16.0 対応です。
> update external-project for 16.0

- doc/src/sgml/contrib.sgml
> update contrib for 16.0

- doc/src/sgml/ref/release_savepoint.sgml
ref/release_savepoint.sgml の 16.0 対応です。
> update release_savepoint for 16.0

- .github/workflows/pr-label.yml
レビュー待ちラベルの条件にsteps.re-review.conclusion
がskipされたことを追加しました。
> steps.re-review.conclusion を条件に追加

- doc/src/sgml/split-catalogs.sh
- doc/src/sgml/split-config.sh
- doc/src/sgml/split-libpq.sh
- doc/src/sgml/split.sh
> split-*をBSD sedで動くように修正

- doc/src/sgml/install-windows.sgml
install-windows.sgml の 16.0 対応です。
> update install-windows for 16.0

- doc/src/sgml/ref/alter_sequence.sgml
- doc/src/sgml/ref/create_trigger.sgml
- ref/alter_sequence.sgml
- ref/create_trigger.sgml
> update for 16.0 - new part 12

- doc/src/sgml/ref/vacuum.sgml
> update vacuum for 16.0

- doc/src/sgml/ref/alter_publication.sgml
- doc/src/sgml/ref/create_publication.sgml
- ref/alter_publication.sgml
- ref/create_publication.sgml
> update *_publication for 16.0

- doc/src/sgml/release-16.sgml
ざっと一通り翻訳しました。見直しや手直しが望ましいとは思いますが、長い間持ってい(て飽き)たので pull request させてください。よろしくお願いします。
> update for release-16

- doc/src/sgml/ref/select.sgml
> update select for 16.0

- doc/src/sgml/pgstatstatements.sgml
pgstatstatements.sgml の 16.0 対応です。
> update pgstatstmt for 16.0

- doc/src/sgml/ref/alter_collation.sgml
- doc/src/sgml/ref/create_collation.sgml
- ref/alter_collation.sgml
- ref/create_collation.sgml
> update *_collation for 16.0

- doc/src/sgml/wal.sgml
> update wal for 16.0

- doc/src/sgml/ref/alter_role.sgml
- doc/src/sgml/ref/create_role.sgml
- doc/src/sgml/ref/createuser.sgml
- doc/src/sgml/ref/drop_role.sgml
- doc/src/sgml/ref/dropuser.sgml
- ref/createuser.sgml
- ref/drop_role.sgml
- ref/dropuser.sgml
> update for 16.0 - new part14

- doc/src/sgml/ref/set_role.sgml
ref/set_role.sgml の 16.0 対応です。
> update set_role for 16.0

- doc/src/sgml/runtime.sgml
> update runtime for 16.0

- doc/src/sgml/nls.sgml
> update nls for 16.0

- doc/src/sgml/ref/copy.sgml
> update copy for 16.0

- doc/src/sgml/ref/explain.sgml
> update explain for 16.0

- doc/src/sgml/ref/create_role.sgml
- doc/src/sgml/ref/createuser.sgml
- doc/src/sgml/ref/explain.sgml
> タグのチェックに引っかかったファイルを修正

- doc/src/sgml/ref/pgbench.sgml
> update pgbench for 16.0

- doc/src/sgml/ref/grant.sgml
- doc/src/sgml/ref/revoke.sgml
- ref/grant.sgml
- ref/revoke.sgml
> update for 16.0 - new part 15

- doc/src/sgml/ref/alter_subscription.sgml
- doc/src/sgml/ref/create_subscription.sgml
- doc/src/sgml/ref/drop_subscription.sgml
- ref/alter_subscription.sgml
- ref/create_subscription.sgml
- ref/drop_subscription.sgml
> update for 16.0 - new part 16

- doc/src/sgml/ref/vacuumdb.sgml
ref/vacuumdb.sgml の 16.0 対応です。
> update vacuumdb for 16.0

- doc/src/sgml/indexam.sgml
> indexam.sgmlの16.0対応です

- doc/src/sgml/logicaldecoding.sgml
> logicaldecoding.sgmlの誤字修正

- doc/src/sgml/ref/pg_dumpall.sgml
> fix typo in pg_dumpall

- doc/src/sgml/ref/pg_dump.sgml
> update pg_dump for 16.0

- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs2.sgml
- doc/src/sgml/ref/pg_dump.sgml
- doc/src/sgml/ref/pg_restore.sgml
- doc/src/sgml/ref/pgbench.sgml
. #536 #2716 により統一されましたが、漢字違いがありました。
> 並べ替えの漢字違いがあったので修正

- doc/src/sgml/ref/psql-ref.sgml
ref/psql-ref.sgml の 16.0 対応です。
> update psql-ref for 16.0

- doc/src/sgml/plpgsql.sgml
> update plpgsql for 16.0

- doc/src/sgml/libpq.sgml
- doc/src/sgml/libpq0.sgml
- doc/src/sgml/libpq1.sgml
- doc/src/sgml/libpq2.sgml
- doc/src/sgml/protocol.sgml
> update libpq for 16.0

- doc/src/sgml/installation.sgml
> fix typo in installation

- doc/src/sgml/ecpg.sgml
> fix typo in ecpg

- doc/src/sgml/logical-replication.sgml
logical-replication.sgml の 16.0 対応です。
> update logical-replication for 16.0

- doc/src/sgml/jpug-doc.sgml
すみません、対応がおそくなりました。
本PRがマージされ次第、v16をリリースします。
> v16の貢献者を更新

- doc/src/sgml/monitoring.sgml
. #2879の指摘で対応が漏れた修正
<entry>分の翻訳漏れの修正
インデント修正
> 翻訳対象漏れと原文に戻す修正

- doc/src/sgml/ref/analyze.sgml
- doc/src/sgml/ref/copy.sgml
- doc/src/sgml/ref/create_collation.sgml
- doc/src/sgml/ref/ecpg-ref.sgml
- doc/src/sgml/ref/initdb.sgml
- ref/analyze.sgml
- ref/copy.sgml
- ref/create_collation.sgml
- ref/ecpg-ref.sgml
- ref/initdb.sgml
> update for 16.3 - part 2

- doc/src/sgml/logical-replication.sgml
- doc/src/sgml/nls.sgml
- doc/src/sgml/postgres-fdw.sgml
- doc/src/sgml/uuid-ossp.sgml
- doc/src/sgml/wal.sgml
- logical-replication.sgml
- nls.sgml
- postgres-fdw.sgml
- uuid-ossp.sgml
- wal.sgml
> update for 16.3 - part 3

- doc/src/sgml/ref/pgupgrade.sgml
ref/pgupgrade.sgml の 16.3 対応です。
> update pgupgrade for 16.3

- doc/src/sgml/fdwhandler.sgml
> update fdwhandler for 16.3

- doc/src/sgml/ref/pg_dump.sgml
- doc/src/sgml/ref/pg_dumpall.sgml
- ref/pg_dump.sgml
- ref/pg_dumpall.sgml
> update for 16.3 - part 4

- doc/src/sgml/plpgsql.sgml
> plpgsql.sgmlの16.3対応です

- doc/src/sgml/ref/create_subscription.sgml
ref/create_subscription.sgml の 16.3 対応です。
> update create_subscription for 16.3

- doc/src/sgml/install-windows.sgml
- doc/src/sgml/json.sgml
- install-windows.sgml
- json.sgml
> update for 16.3 - part 6

- doc/src/sgml/ref/create_table.sgml
ref/create_table.sgml の 16.3 対応です。
> update create_table for 16.3

- doc/src/sgml/ref/grant.sgml
> update grant for 16.3

- doc/src/sgml/client-auth.sgml
> update client-auth for 16.3

- doc/src/sgml/libpq.sgml
- doc/src/sgml/libpq0.sgml
- doc/src/sgml/libpq1.sgml
- doc/src/sgml/libpq3.sgml
> update libpq for 16.3

- doc/src/sgml/storage.sgml
> update storage for 16.3

- doc/src/sgml/pgstatstatements.sgml
pgstatstatements.sgml の 16.3 対応です。
> update pgstatstatements for 16.3

- doc/src/sgml/charset.sgml
> charset.sgmlの16.3対応です

- doc/src/sgml/func.sgml
- doc/src/sgml/func1.sgml
- doc/src/sgml/func2.sgml
- doc/src/sgml/func3.sgml
- doc/src/sgml/func4.sgml
"value expression"の訳は「値式」に統一しています。
> func.sgmlのPostgreSQL 16.3対応です。

- doc/src/sgml/ref/create_role.sgml
ref/create_role.sgml の 16.3 対応です。
一箇所、元の英文がおかしいのではないかと思うところがあります。（機械翻訳は忠実に訳してますが。）
> update create_role for 16.3

- doc/src/sgml/ref/create_foreign_table.sgml
- doc/src/sgml/ref/create_operator.sgml
- doc/src/sgml/ref/create_server.sgml
- ref/create_foreign_table.sgml
- ref/create_operator.sgml
- ref/create_server.sgml
> update for 16.3 - part 7

- doc/src/sgml/manage-ag.sgml
- doc/src/sgml/plpython.sgml
- doc/src/sgml/spi.sgml
- manage-ag.sgml
- plpython.sgml
- spi.sgml
> update for 16.3 - part 8

- doc/src/sgml/ref/create_rule.sgml
ref/create_rule.sgml の 16.3 対応です。
> update create_rule for 16.3

- doc/src/sgml/ref/alter_default_privileges.sgml
ref/alter_default_privileges.sgml の 16.3 対応です。
> update alter_default_privileges for 16.3

- doc/src/sgml/syntax.sgml
Change the target of FILTER clause from window function to aggregate function.
> Fix a mistranslation on FILTER clause

- doc/src/sgml/maintenance.sgml
> update maintenance for 16.3

- doc/src/sgml/.gitignore
> Add .gitignore entry

- doc/src/sgml/monitoring.sgml
> update monitoring for 16.3

- doc/src/sgml/ecpg.sgml
int typeとinteger typeを整数型にしています。
> ecpg.sgmlの16.3対応です

- doc/src/sgml/ref/pg_dump.sgml
- doc/src/sgml/ref/pg_restore.sgml
ref/pg_restore.sgml の16.3 対応です。
> update pg_restore for 16.3

- doc/src/sgml/ref/merge.sgml
> update merge for 16.3

- doc/src/sgml/release-16.sgml
作業したファイルの消失がこわいので、作業中ですが一旦コミットしてプルリクエストを送ります。
16.1の前半と、16.2と16.3を訳しました。
16.1の後半が未訳ですので、7/19(金)までに訳してファイルを更新する予定です。
> Update for release-16 (16.3)

- doc/src/sgml/pgtrgm.sgml
discussedの訳語を「説明」に変更しましたが、重複していたので解消しました。
#2984 の対応です。
> discussedの訳語を「説明」に変更して重複を解消

- doc/src/sgml/ref/merge.sgml
> response for 2989

- doc/src/sgml/ref/alter_table.sgml
- doc/src/sgml/ref/select.sgml
また老眼いじめのものを見つけてしまいました。拡大してみてください。
> fix typo of 'option'

- doc/src/sgml/glossary.sgml
cluster: クラス->クラスタ
clause: 節->句
background: バックエンド->バックグラウンド
> typo修正、訳語違い修正

- doc/src/sgml/btree.sgml
- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs2.sgml
> fix typo - 2

- doc/src/sgml/release-16.sgml
ご指摘の通りかと思いましたので修正案を作って見ました。
少し意訳が入りますが、できるだけ原文のままに表現して見ました。
> ISSUES2992の対応（release-16.sgmlの斉藤さんからの指摘を反映）

- doc/src/sgml/config.sgml
- doc/src/sgml/config0.sgml
> remove extra ws from config

- doc/src/sgml/ref/alter_materialized_view.sgml
- doc/src/sgml/ref/create_role.sgml
以下のファイルの 16.4 対応です。
- ref/alter_materialized_view.sgml
> update for 16.4 - part 1

- doc/src/sgml/ref/drop_database.sgml
ref/drop_database.sgml の 16.4 対応です。
> update drop_database for 16.4

- doc/src/sgml/client-auth.sgml
> update client-auth for 16.4

- doc/src/sgml/runtime.sgml
> update runtime for 16.4

- doc/src/sgml/logical-replication.sgml
logical-replication.sgml の 16.4 対応です。
> update logical-replication for 16.4

- contrib/amcheck/verify_nbtree.c
- doc/src/sgml/config.sgml
- doc/src/sgml/installation.sgml
- doc/src/sgml/limits.sgml
- doc/src/sgml/logical-replication.sgml
- doc/src/sgml/release-17.sgml
- doc/src/sgml/wal.sgml
git mergeでのミスを修正し、マッチ度と機械翻訳を再度入れ直し。
> RC1のマージミスを修正

- doc/src/sgml/gist.sgml
- doc/src/sgml/spgist.sgml
doc_ja_16の更新を適用する際に誤って更新されていた箇所の修正です。
> 17.0対応（doc_ja_16の更新適用ミスの修正）

- doc/src/sgml/ref/lock.sgml
- doc/src/sgml/ref/pg_recvlogical.sgml
- doc/src/sgml/ref/set_session_auth.sgml
- ref/lock.sgml
- ref/pg_recvlogical.sgml
- ref/set_session_auth.sgml
> update for 17.0 - part 1

- doc/src/sgml/intro.sgml
> intro.sgmlの17.0対応です。

- doc/src/sgml/ref/drop_subscription.sgml
内容への変更はなく、`ALTER SUBSCRIPTION`へのリンクが追加されています。
> Translate drop_subscription.sgml for PG17

- doc/src/sgml/tableam.sgml
- doc/src/sgml/xact.sgml
> update for 17.0 - part 3

- doc/src/sgml/logicaldecoding.sgml
第2節が完全に新規の内容(スロット同期機能について)だったので、レビューが大変かもしれません。
> Translate logicaldecoding.sgml

- doc/src/sgml/ref/pg_verifybackup.sgml
- doc/src/sgml/ref/pg_waldump.sgml
- ref/pg_verifybackup.sgml
- ref/pg_waldump.sgml
> update for 17.0 - part 4

- doc/src/sgml/Makefile
- src/backend/catalog/sql_features.txt.ja
> sql_features.txt.jaもチェック対象に追加

- doc/src/sgml/oid2name.sgml
- doc/src/sgml/pgrowlocks.sgml
- doc/src/sgml/rowtypes.sgml
- oid2name.sgml
- rowtypes.sgml
> update for 17.0 - part 6

- doc/src/sgml/config.sgml
- doc/src/sgml/config0.sgml
- doc/src/sgml/config1.sgml
- doc/src/sgml/config2.sgml
- doc/src/sgml/config3.sgml
"WAL Summarization"のSummarizationの訳で迷いました。今の所、次のようにしています。
WAL Summarization -> WAL要約
WAL summarizer process -> WAL要約プロセス
WAL summarizer -> WAL要約処理
the summarizer -> 要約処理
summary files -> WALの要約ファイル
WAL summaries -> WAL要約
WAL SummarizationとWAL summariesが同じ「WAL要約」になっているのが気になっています。
> config.sgmlのPostgreSQL 17.0対応です。

- doc/src/sgml/ref/create_event_trigger.sgml
ref/create_event_trigger.sgml の 17.0 対応です。
> update create_event_trigger for 17.0

- doc/src/sgml/ref/pg_createsubscriber.sgml
> pg_createsubscriber.sgmlのPostgreSQL 17.0対応です。

- doc/src/sgml/sepgsql.sgml
> update sepgsql for 17.0

- doc/src/sgml/ref/alter_role.sgml
- doc/src/sgml/ref/create_role.sgml
- doc/src/sgml/ref/set_role.sgml
以下のファイルの 17.0 対応です。
- ref/set_role.sgml
> update for 17.0 - part 9

- doc/src/sgml/indices.sgml
- doc/src/sgml/json.sgml
- doc/src/sgml/manage-ag.sgml
- doc/src/sgml/pageinspect.sgml
- doc/src/sgml/parallel.sgml
- indices.sgml
- json.sgml
- manage-ag.sgml
- pageinspect.sgml
- parallel.sgml
> update for 17.0 - part 5

- doc/src/sgml/ref/alter_statistics.sgml
- doc/src/sgml/ref/refresh_materialized_view.sgml
- ref/alter_statistics.sgml
- ref/refresh_materialized_view.sgml
> update for 17.0 - part 8

- doc/src/sgml/spi.sgml
> update spi for 17.0

- doc/src/sgml/runtime.sgml
> update runtime for 17.0

- doc/src/sgml/maintenance.sgml
> update for maintenance for 17.0

- doc/src/sgml/ref/pg_checksums.sgml
ref/pg_checksums.sgml の 17.0 対応です。
> update pg_checksums for 17.0

- doc/src/sgml/ref/select.sgml
> update select for 17.0

- doc/src/sgml/logical-replication.sgml
3節が完全新規の内容なので、正しく翻訳できているかレビューしていただきたいです。
> Translate logical-replication.sgml for PG17

- doc/src/sgml/ref/pg_amcheck.sgml
ref/pg_amcheck.sgml の 17.0 対応です。
> update pg_amcheck for 17.0

- doc/src/sgml/ref/pgarchivecleanup.sgml
- doc/src/sgml/ref/psql-ref.sgml
- ref/pgarchivecleanup.sgml
- ref/psql-ref.sgml
> update for 17.0 - part 7

- doc/src/sgml/ref/alter_system.sgml
ref/alter_system.sgml の 17.0 対応です。
> update alter_system for 17.0

- doc/src/sgml/ref/create_collation.sgml
ref/create_collation.sgml の 17.0 対応です。
> update create_collation for 17.0

- doc/src/sgml/ref/vacuum.sgml
> update vacuum for 17.0

- doc/src/sgml/ref/delete.sgml
> update delete for 17.0

- doc/src/sgml/ref/analyze.sgml
> update analyze for 17.0

- doc/src/sgml/bgworker.sgml
bgworker.sgmlで17の方に修正が入っていたので16にバックポートしました。
> bgworker.sgmlの17から16へのバックポート

- doc/src/sgml/advanced.sgml
- doc/src/sgml/ddl.sgml
- doc/src/sgml/manage-ag.sgml
- doc/src/sgml/plpgsql.sgml
- doc/src/sgml/ref/alter_role.sgml
- doc/src/sgml/ref/begin.sgml
- doc/src/sgml/ref/ecpg-ref.sgml
- doc/src/sgml/ref/reindex.sgml
- doc/src/sgml/ref/reset.sgml
- doc/src/sgml/ref/show.sgml
- doc/src/sgml/runtime.sgml
- doc/src/sgml/syntax.sgml
- doc/src/sgml/user-manag.sgml
- doc/src/sgml/xfunc.sgml
reference pageが含まれるところはリファレンスページになるように修正しました。
#3051 の対応です。
> reference pageをリファレンスページに統一

- doc/src/sgml/custom-scan.sgml
https://github.com/pgsql-jp/jpug-doc/pull/3196
で１つ指摘をし損ねました。
１文は長くなってしまいますが句点とピリオドの数を合わせた方が良いと思いPRを作りました。
> 句点とピリオドの数を合わせる（custom-scan）

- doc/src/sgml/ref/analyze.sgml
- doc/src/sgml/ref/cluster.sgml
- doc/src/sgml/ref/copy.sgml
- doc/src/sgml/ref/explain.sgml
- doc/src/sgml/ref/reindex.sgml
- doc/src/sgml/ref/vacuum.sgml
> typoを見つけたので段落の共通化もしました。

- doc/src/sgml/func.sgml
- doc/src/sgml/func2.sgml
> suffix prefixを接頭辞と接尾辞にする

- doc/src/sgml/user-manag.sgml
> update user-manag for 17.0

- doc/src/sgml/dblink.sgml
- doc/src/sgml/ecpg.sgml
- doc/src/sgml/ref/do.sgml
- doc/src/sgml/ref/drop_owned.sgml
- doc/src/sgml/ref/drop_user_mapping.sgml
- doc/src/sgml/ref/pg_checksums.sgml
- doc/src/sgml/ref/pg_verifybackup.sgml
- doc/src/sgml/spi.sgml
#3218 のご指摘の修正とrefpurposeが統一されてなかったので見直して修正しました。
#3230 の修正も一部含みます。
> dblink.sgmlの最修正とrefpurposeの見直し

- doc/src/sgml/ref/create_database.sgml
- doc/src/sgml/ref/createdb.sgml
以下のファイルの 17.0 対応です。
- ref/create_database.sgml
- ref/createdb.sgml
> update for 17.0 - part 13

- doc/src/sgml/ref/cluster.sgml
> update cluster for 17.0

- doc/src/sgml/dml.sgml
> update dml for 17.0

- doc/src/sgml/ref/create_function.sgml
ref/create_function.sgml の 17.0 対応です。
> update create_function for 17.0

- doc/src/sgml/fdwhandler.sgml
> update fdwhandler for 17.0

- doc/src/sgml/brin.sgml
- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs0.sgml
- doc/src/sgml/catalogs3.sgml
- doc/src/sgml/ecpg.sgml
- doc/src/sgml/errcodes.sgml
- doc/src/sgml/extend.sgml
- doc/src/sgml/features.sgml
- doc/src/sgml/gin.sgml
- doc/src/sgml/gist.sgml
- doc/src/sgml/isn.sgml
- doc/src/sgml/json.sgml
- doc/src/sgml/limits.sgml
- doc/src/sgml/monitoring.sgml
- doc/src/sgml/pgcrypto.sgml
- doc/src/sgml/pgrowlocks.sgml
- doc/src/sgml/pgstattuple.sgml
- doc/src/sgml/plpgsql.sgml
- doc/src/sgml/ref/copy.sgml
- doc/src/sgml/ref/create_policy.sgml
- doc/src/sgml/ref/create_trigger.sgml
- doc/src/sgml/ref/pg_waldump.sgml
- doc/src/sgml/ref/pgbench.sgml
- doc/src/sgml/runtime.sgml
- doc/src/sgml/spgist.sgml
- doc/src/sgml/system-views.sgml
- doc/src/sgml/tablefunc.sgml
- doc/src/sgml/user-manag.sgml
- doc/src/sgml/xindex.sgml
- doc/src/sgml/xml2.sgml
複数の<entry>をまとめて日本語訳を付けていたのを分割しました。
#3244の対応です。
まず分割だけしてしてから修正は後にまわすことにしました。
> <entry>の分割（1）

- doc/src/sgml/charset.sgml
- doc/src/sgml/config.sgml
- doc/src/sgml/config1.sgml
- doc/src/sgml/config2.sgml
- doc/src/sgml/func.sgml
- doc/src/sgml/func1.sgml
- doc/src/sgml/func2.sgml
- doc/src/sgml/func4.sgml
- doc/src/sgml/storage.sgml
- doc/src/sgml/syntax.sgml
- doc/src/sgml/textsearch.sgml
複数の<entry>をまとめて日本語訳を付けていたのを分割しました。
#3244の対応です。
> <entry>の分割（2）

- doc/src/sgml/ref/pg_receivewal.sgml
ref/pg_receivewal.sgml の 17.0 対応です。
> update pg_receivewal for 17.0

- doc/src/sgml/file-fdw.sgml
> update file-fdw for 17.0

- doc/src/sgml/ref/update.sgml
> update 'update' for 17.0

- doc/src/sgml/ref/create_view.sgml
ref/create_view.sgml の 17.0 対応です。
> update create_view for 17.0

- doc/src/sgml/rules.sgml
> update rule for 17.0

- doc/src/sgml/ref/pg_amcheck.sgml
[#3171#discussion_r2010119594 ](https://github.com/pgsql-jp/jpug-doc/pull/3171#discussion_r2010119594) への対応です。
> deal with missing parts in ref/pg_amcheck.sgml

- doc/src/sgml/ref/copy.sgml
> update copy for 17.0

- doc/src/sgml/trigger.sgml
> update trigger for 17.0

- doc/src/sgml/protocol.sgml
> process the rest of protocol

- doc/src/sgml/charset.sgml
- doc/src/sgml/planstats.sgml
- doc/src/sgml/ref/vacuumdb.sgml
- doc/src/sgml/unaccent.sgml
17側で修正されていたのを16の内容で更新されないようにバックポートしました。
ref/vacuumdb.sgmlは作業中に発覚した箇所の修正です。
> 17の修正のバックポートです

- doc/src/sgml/ref/initdb.sgml
> update initdb for 17.0

- doc/src/sgml/plpgsql.sgml
> update plpgsql for 17.0

- doc/src/sgml/brin.sgml
- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs0.sgml
- doc/src/sgml/catalogs3.sgml
- doc/src/sgml/ecpg.sgml
- doc/src/sgml/errcodes.sgml
- doc/src/sgml/extend.sgml
- doc/src/sgml/features.sgml
- doc/src/sgml/gin.sgml
- doc/src/sgml/gist.sgml
- doc/src/sgml/isn.sgml
- doc/src/sgml/json.sgml
- doc/src/sgml/limits.sgml
- doc/src/sgml/monitoring.sgml
- doc/src/sgml/pgcrypto.sgml
- doc/src/sgml/pgrowlocks.sgml
- doc/src/sgml/pgstattuple.sgml
- doc/src/sgml/ref/create_policy.sgml
- doc/src/sgml/ref/create_trigger.sgml
- doc/src/sgml/ref/pg_waldump.sgml
- doc/src/sgml/runtime.sgml
- doc/src/sgml/spgist.sgml
- doc/src/sgml/tablefunc.sgml
- doc/src/sgml/user-manag.sgml
- doc/src/sgml/xml2.sgml
doc_ja_16で対応した<entry>の分離をフォワードポートしました。
> <entry>の分離のフォワードポート

- doc/src/sgml/installation.sgml
- doc/src/sgml/ref/alter_extension.sgml
- doc/src/sgml/ref/commit.sgml
> インデントや改行の修正

- doc/src/sgml/protocol.sgml
>  #3305 の途中で見つかったtypoの修正

- src/backend/catalog/sql_features.txt.ja
原文にない行を削除。
合わせて、ラッパ -> ラッパー もやっています。
> fix sql_features.txt

- doc/src/sgml/ref/merge.sgml
> update merge for 17.0

- doc/src/sgml/jpug-doc.sgml
抜け漏れ、表記揺れ、など、お気付きのところがあればお知らせください
> v17の貢献者を記載（1名掲載可否確認中）

- doc/src/sgml/libpq.sgml
PostgreSQL 17.0のlibpq.sgmlがマージされたので、再度pull requestを作りました。
> 田中さんの指摘に対応しました。

- doc/src/sgml/ref/pg_walsummary.sgml
> 「pg_walsummary.sgmlの17.0対応です #3309」の続き

- doc/src/sgml/ref/pgbench.sgml
> pgbench: パラメータの選択方法を明確化

- doc/src/sgml/ref/alter_domain.sgml
- doc/src/sgml/ref/create_domain.sgml
以下のファイルの17.5対応です。
- ref/alter_domain.sgml
- ref/create_domain.sgml
> update *_domain for 17.5

- doc/src/sgml/ref/clusterdb.sgml
- doc/src/sgml/ref/reindexdb.sgml
- doc/src/sgml/ref/vacuumdb.sgml
以下のファイルの17.5対応です。
- ref/clusterdb.sgml
- ref/reindexdb.sgml
- ref/vacuumdb.sgml
> update *db for 17.5

- doc/src/sgml/history.sgml
> update history for 17.5

- doc/src/sgml/json.sgml
- doc/src/sgml/maintenance.sgml
以下のファイルの 17.5 対応です。
- json.sgml
- maintenance.sgml
> update for 17.5 - part 5

- doc/src/sgml/ref/alter_table.sgml
- doc/src/sgml/ref/pg_receivewal.sgml
以下のファイルの 17.5 対応です。
- ref/alter_table.sgml
- ref/pg_receivewal.sgml
> update for 17.5 - part 6

- doc/src/sgml/event-trigger.sgml
event-trigger.sgml の 17.5 対応です。
> update event-trigger for 17.5

- doc/src/sgml/ref/pg_createsubscriber.sgml
ref/pg_createsubscriber.sgml の 17.5 対応です。
> update pg_createsubscriber for 17.5

- doc/src/sgml/release-17.sgml
> 17.1/2/3/4/5 release translation 

- doc/src/sgml/catalogs.sgml
- doc/src/sgml/catalogs2.sgml
- doc/src/sgml/cube.sgml
- doc/src/sgml/features.sgml
- doc/src/sgml/func.sgml
- doc/src/sgml/func4.sgml
- doc/src/sgml/hstore.sgml
- doc/src/sgml/intarray.sgml
- doc/src/sgml/ltree.sgml
- doc/src/sgml/seg.sgml
> 原文で?になっているところを日本語訳も？にする

- doc/src/sgml/advanced.sgml
- doc/src/sgml/arch-dev.sgml
- doc/src/sgml/backup.sgml
- doc/src/sgml/config.sgml
- doc/src/sgml/config1.sgml
- doc/src/sgml/plpgsql.sgml
discussが議論以外に論議となっていることろがあったので見直しです。
#2984の残りです。
> discussが論議となっているところの見直し

- doc/src/sgml/config.sgml
- doc/src/sgml/datatype.sgml
- doc/src/sgml/storage.sgml
- doc/src/sgml/xfunc.sgml
微妙に違っていて共通化できていなかったentryの表記を統一しました。
> entryの表記を統一

- doc/src/sgml/plpython.sgml
> コードの中が訳されていました

- doc/src/sgml/btree.sgml
amprocrighttypeや与えらえれた等の明確な間違いと読みやすさの改善を含んでいます。
> btree.sgmlの修正と改善

- doc/src/sgml/maintenance.sgml
> update maintenance for 17.6

- doc/src/sgml/docguide.sgml
今回削除された文書の日本語訳に誤字らしきものがあります。「初心者にとり」は「初心者にとって」ではないでしょうか？
```
<ulink url="http://newbiedoc.sourceforge.net/metadoc/docbook-guide.html">NewbieDoc Docbook Guide</ulink>は初心者にとりとても役に立ちます。
```
> translate docguide.sgml

- doc/src/sgml/ref/psql-ref.sgml
ref/psql-ref.sgml の 17.6 対応です。
> update psql-ref for 17.6

- doc/src/sgml/ref/alter_tablespace.sgml
- doc/src/sgml/ref/create_tablespace.sgml
以下のファイルの 18.0 対応です。
- ref/alter_tablespace.sgml
- ref/create_tablespace.sgml
よく見たら段落まるまる同じでしたので、揃えてみました。
> update *_tablespace for 18.0

- doc/src/sgml/ref/checkpoint.sgml
- doc/src/sgml/ref/cluster.sgml
以下のファイルの 18.0 対応です。
- ref/checkpoint.sgml
- ref/cluster.sgml
> update for 18.0 - part 1
