pgsql-jp/jpug-doc

doc/src/sgml/acronyms.sgml, doc/src/sgml/arch-dev.sgml, doc/src/sgml/bki.sgml, doc/src/sgml/btree-gin.sgml, doc/src/sgml/charset.sgml
Fix typos in the files in which there are no changes from 9.3.2 to 9.4.0. (part 1)[retry]
=> Fix typos (part 1)

doc/src/sgml/Makefile, doc/src/sgml/errcodes.sgml, doc/src/sgml/stylesheet.dsl, src/backend/utils/errcodes.txt.ja
主役はerrcode周りの訳ですが、日本語版features-(un)supported.sgmlを生成するためのMakefileの変更や日本語版errcodes-table.sgmlを生成するためのMakefileの変更、さらには出力されるhtml文字コードの設定変更も入っています。
これで　9.3.2相当のhtml出力が得られるようになるはずです。
=> Make japanese html

doc/src/sgml/libpq.sgml
To avoid the jade error,
at <filename>`pg_config --sysconfdir`/pg_service.conf</filename> or in the directory
is changed to:
at <filename>`pg_config -sysconfdir`/pg_service.conf</filename> or in the directory
(note "--sysconfdir" is changed to "-sysconfdir")
=> Apply changes from PostgreSQL 9.4.0 to 9.4.1.

doc/src/sgml/release-9.4.sgml
9.4.1 のリリースノートを訳しました。
以下の点については意見を貰いたいです。
・エラーメッセージの英文を残しました。これは先例から離れていますがどうでしょうか？
・9.4.0 から revert された修正点について 9.4.0 のリリースノートから項目が消えていますが、訳注を付けたうえで残しました。
=> translate release-9-4 about 9.4.1

doc/src/sgml/stylesheet.css
サイト上で body 直下に埋め込んだ Google Analytics の script が表示されていまうので、script タグはすべて非表示とします。
=> Change to hide <script> contents.

doc/src/sgml/datatype.sgml
=> fix typo (remove extra '(')

doc/src/sgml/ref/create_table.sgml
トップからmakeすると以下のエラーでビルドに失敗するのを修正
'/usr/bin/perl' create_help.pl ../../../doc/src/sgml/ref sql_help
create_help.pl:create_table.sgml: null end tag not supported in synopsis
=> Fixed src build fails

doc/src/sgml/func.sgml
日本語が原文直訳っぽくなって分かりづらかったので、意訳しつつ語順を修正しました。
=> pg_start_backupの第2引数の説明を修正

doc/src/sgml/installation.sgml
余分な「.」が付かないように:を半角に変更。
詳しくは[jpug-doc: 4543] 謎の「.」から始まるやり取りを見てください。
=> remove extra '.'

doc/src/sgml/backup.sgml
<literal>.backup</>、または<literal>.history</>が付いているファイル云々は重複を削除しました。
あとその周辺でファイルが「要求される」という表現に揃えています。
=> fix typos in backup.sgml

doc/src/sgml/syntax.sgml
"both" の訳が抜けていたので修正しました。
SQL:2008 (preliminary) ドラフト版を見ましたが、aggregate function の set quantifier として DISTINCT は指定可能でした。
=> 集約式の注記の翻訳を修正

doc/src/sgml/libpq.sgml, doc/src/sgml/wal.sgml
日本語として明らかにおかしいところを直しました。
（と思ったのですが、片方はタグを誤解したものみたいです）
=> fix typos in libpq.sgml and wal.sgml

doc/src/sgml/config.sgml
autovacuum_vacuum_thresholdの方は、pg_autovacuumについて言及していますが、8.3以前のバージョンについての説明のまま？のようです。
=> autovacuum_{vacuum,analyze}_thresholdのテーブル個別設定方法の記述修正

doc/src/sgml/config.sgml
"index-only-scan plan type"が「インデックス走査計画型のみ」となっていたので、「インデックスオンリースキャン計画型」に修正してみました。
ただ、この節では"scan"を「走査」と訳している箇所が多いので、「インデックスオンリー走査計画型」の方が統一感はあります。
=> enable_indexonlyscanの説明修正

doc/src/sgml/config.sgml
shared_buffersの説明にわかりにくい部分があったので、訳文を修正してみました。
やや意訳気味かもしれません。
=> shared_buffersの説明を修正

doc/src/sgml/plpgsql.sgml
てにをは の修正
結果が返ります としても良かったですが、後に合わせて 結果を返します としました。
=> fix typo in plpgsql

doc/src/sgml/config.sgml
log_truncate_on_rotationの説明で、例を出して説明している箇所がやや分かりづらかったので修正してみました。
=> log_truncate_on_rotationの説明を修正

doc/src/sgml/queries.sgml
[issue の#223（7.8 WITH Query - Recursive Query Evaluation　日本語訳改善案 ）](https://github.com/pgsql-jp/jpug-doc/issues/223)で議論されていた件です。
=> improve Japanese translation

doc/src/sgml/func.sgml, doc/src/sgml/ref/pgbench.sgml
RC1が出た以降にfunc.sgmlに行われた変更分の反映です(2015/12/27現在)。
=> Apply diff to func.sgml since RC1 (as of Dec 27, 2015).

doc/src/sgml/release-9.0.sgml, doc/src/sgml/release-9.1.sgml, doc/src/sgml/release-9.2.sgml, doc/src/sgml/release-9.3.sgml
As pointed out by Michael Paquier, recovery_min_apply_delay didn't exist
in 9.0-9.3, making the release note text not very useful.  Instead make it
talk about recovery_target_xid, which did exist then.
9.0 is already out of support, but we can fix the text in the newer
branches' copies of its release notes.
=> Adjust back-branch release note description of commits a2a718b22 et al.

doc/src/sgml/ref/create_role.sgml
「行レベルセキュリティ」を「行単位セキュリティ」としました。
=> create_role.sgmlでrow-level securityの訳語を変更

doc/src/sgml/hstore.sgml, doc/src/sgml/ltree.sgml
hstore.sgml
ltree.sgml 
ほぼ似たようなものが追加になっていますので、組み合わせてのPRは（他のものより）意味は有るかと。
=> hstore.sgml and ltree.sgml for 9.5.0

doc/src/sgml/indices.sgml, doc/src/sgml/install-windows.sgml
indices.sgml
install-windows.sgml
=> indices.sgml and install-windows.sgml for 9.5

doc/src/sgml/syntax.sgml
syntax.sgmlの9.5.0対応です。
<literal>CASE</> is 以下大量に差分がある（削除された）ように見えますが、
git diff REL9_4_5 REL9_5_0 doc/src/sgml/syntax.sgml
で確認する限り、そのような差分はないと思います。
=> syntax.sgml for 9.5.0

doc/src/sgml/config.sgml
「設定パラメータ」と「コンフィグレーションパラメータ」の混在は、以前か
ら使われている「設定パラメータ」に合せました。
=> 斉藤さんのconfig.sgmlに対する指摘([jpug-doc: 4906])に対応

doc/src/sgml/auto-explain.sgml, doc/src/sgml/backup.sgml, doc/src/sgml/func.sgml
"configuration parameter"の訳を「設定パラメータ」にしました。
=> revise translation of "configuration"

doc/src/sgml/replication-origins.sgml
> 斉藤 登です。
>
> https://pgsql-jp.github.io/jpug-doc/9.5.0/html/replication-origins.html
>
> <link linkend="logicaldecoding">logical decoding</link>
> が日本語訳の方で、
> <link linkend="logicaldecoding"></link>
> になっているので、「???」になってしまっているようです。
=> [jpug-doc: 4922]の指摘に対応

doc/src/sgml/config.sgml
> 斉藤 登です。
>
> 小出しになりまして済みません。
>
> 9.5.0で修正して欲しい箇所で★入れてましたが、★が
> 残ってました。
> https://pgsql-jp.github.io/jpug-doc/9.5.0/html/runtime-config-autovacuum.html
>
> This parameter can only be set in the <filename>postgresql.conf</> file or on the server command line; but the setting can be overridden for individual tables by changing table storage parameters.
>
> このパラメータを有効にすることは、autovacuum活動の追跡に役に立ちます。 このパラメータはpostgresql.confファイル、または、サーバのコマンドラインでのみで設定されます。★★★
>
> の部分です。
=> [jpug-doc: 4921]の指摘に対応

doc/src/sgml/func.sgml
(1) "most trivial ... operators"におけるtrivialの修飾先の誤りを修正
(2) literalタグ内のnullが「NULL値」と翻訳されているのを元に戻した
(3) swapの訳語を「置き換え」から「交換」に変更
(4) andが「または」となっていたのを「かつ」に修正
(5) "not true or false"の掛かり先の誤りを修正
その他、小さな修正が2ヶ所。
=> func.sgmlの既存部分の誤訳の修正と翻訳の改善。

doc/src/sgml/release-9.5.sgml
原文が言っているのは、DOMAIN自体へのコメントではなく、9.5で導入された
「ドメインの制約」にコメントが付けられるようになった、ということ。単に
ポイントしているコミットIDが間違っていただけ。正しいコミットIDをコメン
トに追記しておいた。
=> リリースノートの再訂正

doc/src/sgml/func.sgml
(1) 算術演算子の解説の冒頭の誤訳を訂正
(2) bitwiseの訳語を「バイナリ」から「ビット」「ビットごと」に変更（ファイル内および他のファイルと統一）
(3) degrees()とradians()の説明を改善
(4) round()とtrunc()の説明を改善
(5) padの訳語を「パッドする」から「詰め込む」に変更
(6) needの訳語を「期待」から「必要」に変更
(7) ||演算子の説明の軽微な誤訳を訂正
(8) substringの訳語を「副文字列」から「部分文字列」に変更(他と統一)
(9) trim()の説明の軽微な誤訳を訂正
(10) 動詞の"list"が連続する箇所について、訳語を「列挙する」で統一
(11) chr()の説明の軽微な誤訳を訂正
(12) concat()およびconcat_ws()の説明を他に合わせて「ですます」調にし、また原文に忠実な訳文に変更
(13) convert()の軽微な誤訳を訂正
(14) decode()の軽微な誤訳を訂正
(15) encode()の軽微な誤訳を訂正
(16) initcap()の誤訳を訂正
(17) left()の説明を改善
(18) quote_literal()などでのcoerceの訳語を「強制」から「変換」に変更（coersionの訳語と語感を統一）
(19) quote_nullable()の説明を改善
(20) right()の誤訳を訂正すると同時に説明を改善
(21) translate()の説明を原文に忠実なものに変更
(22) formatstrの解説における"except where..."の誤訳を訂正
(23) introduceの訳語を「始まる」に変更
(24) フォーマット指示子の解説でのoptionalを「任意」から「省略可能」に変更
(25) …
=> func.sgmlのうち、マニュアルの9.3と9.4節に該当する部分の誤訳訂正と訳文の改善。

doc/src/sgml/func.sgml
(1) trim()の説明の誤訳を訂正
(2) decodeの訳語を「復号化」から「復号」に修正
(3) encode()の説明で"zero bytes"を「0バイト」から「0のバイト」に修正
=> func.sgmlのうち、マニュアルの9.5節に該当する部分の誤訳訂正と訳文の改善

doc/src/sgml/config.sgml
"Beggining in ..."は聞かないフレーズで、構文的にはやや不自然ですが、「デフォルトがonになるのが9.1から始まった(begin)」と捉えるべきです。
=> config.sgmlの軽微な誤訳の修正。

doc/src/sgml/func.sgml
列挙型の関数の説明ですが、日本語の意味がわかりにくい部分が多かったので、かなり直しました。
=> func.sgmlのうち、マニュアルの9.10節に該当する部分の誤訳訂正と翻訳改善

doc/src/sgml/brin.sgml, doc/src/sgml/gin.sgml, doc/src/sgml/gist.sgml, doc/src/sgml/spgist.sgml
オペレータ->演算子
ビルトイン->組込み
インデックス付けするデータ型->インデックスされるデータ型
インデックス可能演算子->インデックス可能な演算子
序文->はじめに
=> インデックスの各章で訳語の統一([jpug-doc: 4936])

doc/src/sgml/func.sgml
(1) doubledの訳語を「2倍」から「二重」に修正し、さらに訳文を一部修正
(2) similar toの解説で、succeedを「処理を行う」から「真を返す」に修正
(3) 「0回以上複数の繰り返し」「1回以上複数の繰り返し」の「複数」を削除
(4) anyを「任意の」と訳していた誤りを修正（日本語では不要なので訳出しない）
(5) regexp_replaceの構文説明の括弧とカンマは半角にする
(6) \n, \&の説明がわかりにくいので書き直した
(7) "though not g"の訳が不自然なので修正
(8) regexp_matchの解説で括弧つきの注を原文に合わせて括弧つきにした
(9) 配列を返すパターンの説明がわかりにくいので書き直した
(10) gフラグで複数マッチしたときの、「それら一致の行を返させます」は誤訳なので訂正すると同時に、不自然な使役表現を修正
(11) sub-selectでregexp_matchesを使う例の解説文を訳し直した
(12) regexp_split_to_arrayの説明の最後の文が訳抜けしていたので翻訳した
=> func.sgmlのうち、マニュアルの9.7節に該当する部分の誤訳訂正と訳文の改善

doc/src/sgml/stylesheet.css, doc/src/sgml/stylesheet.xsl
<code>の強調は止める
stylesheet.xslで不要な記述を削除
=> .replaceableをスタイル追加

doc/src/sgml/func.sgml
誤訳訂正の他、意味がとりにくい（誤解を招く）表現を修正する、
なるべく原文に近い意味にする、文体を周りに合わせる、などの変更をしました。
=> func.sgmlのマニュアル9.8節に該当する部分の誤訳訂正と翻訳改善。

doc/src/sgml/rules.sgml
volatile functionは揮発関数と訳されている場合とvolatile関数と訳されているケースがありましたが、
ひとまず個人的に分かりやすかった後者を選択しています。
multiple-assignmentは迷って「複数割当」と訳しています。
=> rules.sgml first translation for pg9.5.0

doc/src/sgml/func.sgml
9.5で追加された部分の修正です。
「一緒」が「一書」になっていた誤変換だけ修正しても良かったのですが、それと同時に「操作」では違和感が強い(実態は関数であって、何かの操作をするわけではない)ことに気付いたので、「演算」に修正しました。
operatorが演算子なので、当然ながらoperationには演算という意味があります。
=> Grouping operationの訳語を「グループ化操作」から「グループ化演算」に変更

doc/src/sgml/func.sgml, doc/src/sgml/xindex.sgml
https://github.com/pgsql-jp/jpug-doc/pull/422
で反映した以外のファイルにグループ化操作があったので、統一しました。
=> グループ化操作をグループ化演算に統一

doc/src/sgml/stylesheet.css, doc/src/sgml/stylesheet.xsl
最初のページのタイトルをcenterに修正
例(div.example)のブロックが効いてなかったのを修正
「簡単なリスト」の表示を改善
原文表示を &lt;br/&gt;ではなくcssのdisplay:blockに変更
=> xhtml版のcss更新

doc/src/sgml/func.sgml
「データベースエンコードが～」は原文にないので削除。
json_populate_record/recordsetが訳文から落ちていたので追加。
=> 訳し過ぎと訳抜けの修正

doc/src/sgml/func.sgml, doc/src/sgml/ref/create_aggregate.sgml, doc/src/sgml/ref/drop_aggregate.sgml
func.sgmlで"hypothetical-set"を「仮定集合」と訳していたのを、他のファイルに合わせて「仮想集合」としました。また、単独の"hypothetical"も「仮定の」から「仮想の」に変更しました。
同時に、ｒｅｆのcreate/drop_aggregate.sgmlで"ordered-set aggregate"と"hypothetical-set aggregate"を「順序集約」「仮想集約」と訳していたのですが、それぞれ「順序集合集約」「仮想集合集約」としました。
=> hypothetical-setの訳語を「仮想集合」で統一

doc/src/sgml/func.sgml
復活行:<secondary>built-in</secondary>
削除行:<entry>aggregates records as a JSON array of objects</entry>
<function>pg_identify_object</function>〜は移動していたため重複していま
した。新しく編集されていたエントリを残しました。
=> func.sgml 原文にない行の削除

doc/src/sgml/config.sgml
「システム・コール」の中黒を削除しました。（ここ以外はすべて「システムコール」と中黒なしのようです。）
あと行頭の空白の削除も。
=> fix system call

doc/src/sgml/stylesheet.css
原文が白地に明るい緑で見づらいと感じましたので、文字色を暗めの緑に変更してみました。
変更箇所は合っていると思うのですが、すこし自信がありません。(間違っていたらすいません)
細かい点で、かつ環境にも左右されるところでもあり、
恐縮ですがご検討いただければと思います。
よろしくお願いします。
=> 原文の文字色を暗めに変更

doc/src/sgml/func.sgml
誤訳訂正と言えるものはほとんどありませんが、不自然な日本語の改善、訳語の改善、
訳文のインデントを削除（そのついでに、複数文がある場合は改行を挿入）などの
修正を行いました。
=> func.sgmlのマニュアル9.15節に該当する部分の翻訳改善

doc/src/sgml/func.sgml
誤訳の訂正、わかりにくい表現の改善、不自然な訳語の変更などを行いました。
=> func.sgmlのマニュアル9.16節に該当する部分の誤訳訂正と翻訳改善。

doc/src/sgml/func.sgml
=> func.sgmlのマニュアル9.17節に該当する部分の誤訳訂正と翻訳改善

doc/src/sgml/catalogs.sgml
原文にない行の削除
5493行 true, the index is currently valid for queries.  False means the
13953行〜       For some data types such as <type>tsvector</>, it can also store some〜
<para>外から<para>内にコメント開始を移動
余分な空行、スペースを削除
=> catalogs.sgml 原文との差分を減らす修正

doc/src/sgml/brin.sgml, doc/src/sgml/datatype.sgml, doc/src/sgml/ddl.sgml, doc/src/sgml/ref/alter_policy.sgml, doc/src/sgml/release-9.5.sgml, doc/src/sgml/replication-origins.sgml
9.5.0->9.5.1では変更無し
brin.sgml
datatype.sgml
ref/alter_policy.sgml
replication-origins.smgl
ddl.sgml
"<<<"行を削除
分割移動されたエントリを参考に復活
Superusers and roles 〜は変更無し
release-9.5.sgml
9.5.0部分に入っていた余計なエントリを削除
=> doc_ja_9_5との差分修正

doc/src/sgml/datatype.sgml
datatype.sgmlの9.5.1対応です。日本語訳には影響しません。
=> datatype for 9.5.1

doc/src/sgml/ddl.sgml
そのついでに、"primary key", "unique constraint"の訳語をそれぞれ、
「プライマリキー」「一意性制約」に統一しました。
個人的には「主キー」「一意制約」の方が良いと思っているのですが、
現在の日本語マニュアルでは前者が圧倒的に多いので、とりあえず、それに統一。
=> ddl.sgmlの9.5.1対応です。

.travis.yml
9.5.0では既にxmllintを実行をしているため再度実行する必要がない。
https://travis-ci.org/pgsql-jp/jpug-doc/builds/107846131#L630
=> .travis.yml 必要ない行の削除

doc/src/sgml/postgres.sgml
パートIIの冒頭部分です。
(1) "refer forward"は、まだ読んでいない先の方のページを参照することを指していると思いますが、「他の入門書など」となっていたので修正しました。同時に"too many times"を訳出しました。
(2) 対象読者について"should know how to connect to a PostgreSQL database and issue SQL commands"なので、「方法を知っていれば良い」としか言っていませんが「慣れ親しんでいる」とかなり高いハードルを設定する訳になっていたので修正しました。続く文の"unfamiliar"を「熟知していない」としているのも、同じくハードルが高いので修正しました。
=> postgres.sgml(sql.html)の誤訳訂正（原文と違うことが書いてある部分を直しました）

doc/src/sgml/planstats.sgml
"is scaled accordingly"を「増大させる」と訳していますが、必ずしも増える
とは限らないのでこの訳は不適切です。ここで言っているのは、プランナが取
得したページ数と、relpagesの比率の差分だけreltuplesの行数を増やすか減ら
すかする、ということです。
また、"In this case"を「この場合」と訳していますが、意味が通じないので
本家に確認したところ、"In this case"は上にある実行例を指していることが
わかったので、訳を修正しています。
"histogram"の訳問題には手を付けていません。
=> planstats.sgmlの訳の改善および誤訳の修正です。

doc/src/sgml/query.sgml
(1) "PostgreSQL language features"で、「PostgreSQL言語の～」はおかしいので修正しました。
(2) カタカナで「コンパイル」とすると、ソースファイルをオブジェクトに変換する操作を指しますが、この"compile"は「同梱する」などの意味なので修正しました。
(3) 関係詞節で、意味的には訳し上げでも訳し下げでも同じですが、文を読む時の理解しやすさの点で、訳し下げる方が良いと感じたので、変更してみました。
=> query.sgmlの翻訳改善

doc/src/sgml/postgres.sgml
「形式的な」という言葉は、表面的で中身がない、という意味になってしまいます。
この場合の"formal"は「正式な」という意味なので、ぴったりした訳語の選択が難しいですが「本格的な」に変更しました。
=> postgres.sgml(tutorial.html)の誤訳修正

doc/src/sgml/datatype.sgml
lineの訳の部分の改善です。
線 -> 直線 は少しやり過ぎの気もしないでもないですが、元々の文でも変更部分の直後で「直線」とやっていますので悪くはないかなと。
=> improve translation of "line"

doc/src/sgml/syntax.sgml
以下、主な変更箇所です。
(1) 2箇所ある"lexical structure"について、lexicalは「語彙」を「字句」に変更、structureは「構造」に統一
(2) 不自然な日本語の言い回しを改善
(3) 「クォートされていない」の注は不要なので削除
(4) "often"を明示的に訳出
(5) 「普段使えない」は原文と意図が違うので修正
(6) variantの訳語を「変異体」から「異形」に変更
(7) 「XXの直前にYY」というタイプの表現を「YYの直後にXX」という表現に変更
(8) "less trivial"が誤訳されていたので修正、「前の例ほど重要度は低くない」という感じの意味ですが「少し意味のある」という訳をひねり出しました。
(9) サロゲートペア関連の説明で、訳し上げているため、文中で前方参照することになっていたのを、訳し下げることで理解しやすい文に修正。
(10) string constantが、なぜか「文字定数」となっていた部分がいくつかあったので「文字列定数」に訂正
=> syntax.sgmlのうち、マニュアルの4.1節の一部の誤訳訂正と翻訳改善

doc/src/sgml/config.sgml
余分なピリオドの削除
be meant to do の訳の改善
訳漏れへの対応
です。
=> fix typos in config.sgml

doc/src/sgml/func.sgml
主な修正点は以下の通りです。
(1) "a set of"を「複数の」と訳していたのを「の集合」に修正。
(2) avg()とbit_and()の引数データの型で、原文中の"or"がそのままになっていたので、翻訳。なお、読点だけにして、"or"は明示的に訳出しないというのもアリだと思うが、他の部分に合わせて「または」とした。
(3) count()の引数データの型で、原文中の"any"がそのままになっていたので「任意の型」と翻訳。なお、"(type)any(/)"という形式のものも多数ある。「any型」というデータ型があるわけではないので、本質的には「任意の型」などと訳すべきだと思うが、これについては現状のままとした。
(4) 「名前／値」でスラッシュが全角のものと半角のものがあったので、全角に統一。
(5) "substitute"の訳語で「交換」は違和感が強かったので「置換」に変更。
(6) "dependent variable"の訳語が「依存変数」となっていたが、より一般的な「従属変数」に変更。
(7) "least-square-fit linear equation"について誤訳訂正。
(8) "square"の訳語で「自乗」と「二乗」が混在していたが、現代的な「二乗」で統一。
(9) 関数引数のfractionについて話をしているときに、「割合」という訳語だけが出てきても意味がわかりにくいので、1つ目は「fraction（割合）」、2つ目は単に「fraction」に変更。
=> func.sgmlのマニュアル9.20節に該当する部分の誤訳訂正と翻訳改善

doc/src/sgml/query.sgml
マニュアルの2.2節から2.4節の翻訳改善です。
(1) 他のファイルではすべて「データベース管理システム」でしたが、この1箇所だけ「データベースマネージメントシステム」だったので統一しました。
(2) alignedの訳の意味がわかりにくかったので、明確になるようにしました。
(3) date型の列名をdateにしているのが、この場だけの話なのに、一般的にそうするものだ、みたいに解釈されかねない訳文になっていたので、修正しました。
(4) considerの訳し方が不適切だったので修正しました。なお、widelyについてはちょっと悩みましたが、文字通りに「広く」としても意味がわかりにくいので、英英辞典にあった"by many people"なども参考に「一般的には」としました。
=> query.sgmlの誤訳訂正と翻訳改善

doc/src/sgml/start.sgml
主な修正点は以下の通りです。
(1) "separate database is used"の訳が誤解を招きかねないものだったので、原文に忠実なものにした。
(2) "should"を義務のように訳していたのを修正。
(3) 「シェルの検索パスに『盛り込む』」は違和感が強かったので、表現を修正。
(4) 「今回は」では意味がわからないので、「joeのところに」と原文にない言葉を入れてわかりやすくしたが、ちょっとやり過ぎかも？
(5) 「管理者であれば」は意味がわからないので、「自身が」を補った。なお、"you"を「あなた」と訳した方がこの文自体はわかりやすくなるが、全体的な見直しが必要になるので避けた。
(6) サイト管理者の義務みたいな表現は違和感があったので、表現を訂正。
(7) "started the server"の部分は「インスタンスを作成したユーザ」を指しているが、違う解釈になっていたのでて訂正。
=> start.sgmlのマニュアル1.3節の誤訳訂正と翻訳改善

doc/src/sgml/query.sgml
2.5節に相当する部分ですが、最後に原文にない文が入っていたのを削除しました。
また、原文に忠実でない翻訳が2箇所あったので訂正しました。
(1) 単なる"expression"を「任意の式」としていたので「任意の」を削除、また、原文に"too"や"also"はありませんが、自然な日本語の文章になるように「を」を「も」に変更。
(2) "Here again"は、前言を繰り返すという意味ではなく、前と同じ現象がここでも発生しますよ、という意味なので、訳文を修正。
=> query.sgmlで、原文にない文があるのを削除

doc/src/sgml/high-availability.sgml
語の途中での改行を削除。
すみません、とってもせこいですが、、、、
日本語訳の途中での改行は好ましくないかな程度で済みますが、流石に語の途中での改行は許せないかな、と。
=> delete inappropriate newlines

doc/src/sgml/catalogs.sgml
catalogs.sgmlの翻訳の改善です。
（読んでいるうちに改善になっているかだんだん自信がなくなってきましたが、とにかくPR）
合わせて、
-  余分な改行の削除
- 「。」の追加
もしています。
=> improve translation of catalogs.sgml

doc/src/sgml/xplang.sgml
xplang の訳の改善です。
libraryは引用符で囲まれていますが、libraryという名前のディレクトリがあるわけではない（あるのはlib）ので、「ライブラリ」としています。
ついでに . -> 。もやってます。
=> improve translation of xplang

doc/src/sgml/func.sgml
9.21節の誤訳訂正と翻訳改善、主な変更点は以下の通りです。
(1) rank(), dense_rank(), cume_dist()の説明の誤訳訂正
(2) ntile()の説明でdivideを「割り算」としていたのを「分割」に修正
(3) lag(), lead()のoffsetに関する説明を改善し、また他の関数の解説に合わせて、である調に統一
(4) "aggregate used with"の掛かり先の解釈が間違っていたのを修正
=> func.sgmlのウインドウ関数の節に関する誤訳訂正と翻訳改善

doc/src/sgml/advanced.sgml
誤訳の訂正、原文と微妙に意味が違うものについて原文になるべく忠実になるような修正を行いました。
(1) "some extensions"はこのままでも良かったかな、と思いつつ、違和感があったので修正しました。
(2) ディレクトリ名で原文には"src/"が付いていなかったので削除
(3) "combined listing"の訳し方を修正、また、ビューの説明を原文に忠実な文に修正
(4) "Making liberal use..."の文の意図が原文と違うように感じたので訳し直し
(5) "place"が「場合」になっていたので「場所」に修正し、ついでに、改行を挿入
=> advanced.sgml(3章)の3.2節(ビュー)までの誤訳訂正と翻訳改善

doc/src/sgml/advanced.sgml
主な修正点は以下の通りです。
(1) "would"を「しなければなりません」と訳していたので、「でしょう」とした上で、原文の意味になるべく近くなるように訳し直しました。(逐語訳とはかなり違う状態ですが)
(2) "new declaration of the tables"で"new"が"tables"ではなく"declaration"に掛かっていることがわかるような日本語にしました。
(3) トランザクションの途中でエラーが起こった時の話が原文とちょっと違っていたので、忠実な訳文にすると同時に、句点で改行しました。
(4) アリスとボブの口座との関係の例を説明した文の訳がおかしかったので、訳し直しました。
(5) "asking"を「警告する」としていたのは違和感が強かったので「ユーザに尋ねる」としました。
その他、細かな翻訳改善がいくつかあります。
=> advanced.sgml(3.3-3.4節)の誤訳訂正と翻訳改善

doc/src/sgml/syntax.sgml
主な修正点は以下の通りです。
(1) 4.2節で"function definition"の訳語を「関数宣言」→「関数定義」とした。
(2) 4.2.1節で"correlation.columnname"の説明をしているときに、"correlation name"を「相関名」としても意味が通じないので、"correlationの名前」とした。
(3) 4.2.3節の訳文を全面的に見直した。
=> syntax.sgml（主に4.2.3節：添え字）の誤訳訂正と翻訳改善

doc/src/sgml/syntax.sgml
主な修正点は以下の通りです。
(1) extractを「展開」と訳していたので、「抽出」に訂正
(2) 行頭にあった空白を削除し、さらに句点で改行。
(3) 4.2.6節の注記の翻訳を全面的に見直し
=> syntax.sgml(主に4.2.6)の誤訳訂正と翻訳改善

doc/src/sgml/stylesheet.css
幅が641以上のときのみ width: 90%; になるようにしました。
=> 端末幅が640px以下の場合は左右のマージンを無くす

doc/src/sgml/ddl.sgml
主な修正点は以下の通りです。
(1) "a consequence of the mathematical model"の訳語に違和感があったので、一般的と思われる「数学的モデルの帰結」としました。
(2) "also"の掛かり先の解釈が誤っていたので、訳文を修正しました。
(3) "naming pattern"の"pattern"が訳出されていなかったので、訳文を修正しました。
(4) "This arrangement is sufficiently common"という節が訳出されていないようだったので、訳出すると同時に、文全体の訳を修正しました。
=> ddl.sgml(主に5.1-5.2節)の誤訳訂正と翻訳改善

doc/src/sgml/func.sgml
主な修正点は以下の通りです。
(1) 言い換えの"or"を「または」と訳していたので訂正
(2) 「評価されると前提して」という言い回しに違和感があったので「評価されることを前提として」と修正
(3) 「それ以外その行は」という言い回しに違和感があったので「それ以外の場合、その行は」と修正し、ついでに句点で改行
(4) "if only unequal subquery rows are found (including the case where the subquery returns no rows)"というパターンの文の訳文を「等しくない副問い合わせの行だけがある（副問い合わせが行を返さない場合を含む）」というパターンに統一
=> func.sgml(9.22節)の誤訳訂正と翻訳改善

doc/src/sgml/advanced.sgml
主な修正点は以下の通りです。
(1) "directly following"の解釈がおかしかったので、訂正しました。
(2) distinctの訳語がおかしかったので、訂正しました。
(3) "if any"の訳として「もし存在するのであれば」は重すぎる上、何が存在するのかわからないので、単に削除しました。頑張って訳出するなら「～句があるなら、それらでフィルターして」などとするところかと思います。"is not seen"が「見つかりません」は違和感があったので、「見えません」としました。そのついでに、改行をいくつか追加しました。
(4) 「割愛」は違和感があったので「省略」としました。
(5) ウインドウフレームの説明がわかりにくかった(構文解釈の誤りもあった)ので、一部、言葉を補って訳し直しました。
(6) elsewhereが訳出されていなかったので、明示的に訳し、そのついでに改行をいくつか追加しました。
=> advanced.sgml(3.5節 ウインドウ関数)の誤訳訂正と翻訳改善

doc/src/sgml/syntax.sgml
主な修正点は以下の通りです。
(1) "represent"の訳語として「意味します」は違和感があったので、「表現します」としました。
(2) NULL入力があったときの説明がおかしかったので、訳し直しました。
(3) optionalの訳語として「省略可能な」がしっくりこなかったので、「オプションの」としました。そのついでに、改行をいくつか挿入しました。
(4) "a PostgreSQL extension"を「PostgreSQLの『独自の』拡張」とするのは言い過ぎの感があるので「独自の」を削除しました。
(5) sensibleの訳語がおかしかったので、訂正しました。
(6) "This is unlike..."の文の意味がわかりにくかったので、訳し直しました。
(7) logicallyの掛かり先の解釈が間違っていたので修正しました。
=> syntax.sgml(4.2.7節 集約式)の誤訳訂正と翻訳改善

doc/src/sgml/advanced.sgml
主な修正点は以下の通りです。
(1) コロンの前後で文を分けているのはわかりにくいので、1文にまとめ、ついでに改行をいくつか挿入しました。
(2) mightの訳語の「するでしょう」は違和感があったので「するかもしれません」としました。
(3) citiesやcapitalsなどテーブル名の後に「（都市）」などの注釈が入っているのを、classnameタグの外側に出しました。また、くどい感じがするので、2回目以降からは注釈を削りました。
(4) "for one thing"の訳語が適切でなかったので訂正しました。また「いくつか複数」は日本語としておかしいので、単に「複数」としました。
(5) 「『行政府所在地を含む』標高500フィート以上の…」は掛かり関係が曖昧なので、修正しました。
(6) "frequently"が訳出されていなかったので、明示的に訳し、また"integrated"の訳語を修正しました。
=> advanced.sgml(3.6節 継承)の誤訳訂正と翻訳改善

doc/src/sgml/syntax.sgml
主な修正点は以下の通りです。
(1) "any"の訳語がおかしかったので、訂正しました。
(2) "number"の訳語がおかしかったので、訂正しました。
(3) "in an unspecified order"の訳し方に違和感があったので修正しました。
(4) frame_clauseの説明で関係詞節が訳抜けしていたので補うと同時に、訳を一部、修正しました。
(5) "a frame_start of UNBOUNDED PRECEDING"などの表現の解釈が間違っていたので修正しました。
(6) "peer"を明示的に訳出されていませんでしたが、「ピア」として訳出しました。適当な日本語がありませんが、初出時に「ORDER BYが現在行と同じ順序とみなす行」との注がついているので、これで良いと思っています。
=> syntax.sgml(4.2.8節 ウィンドウ関数)の誤訳訂正と翻訳改善

doc/src/sgml/ddl.sgml
主な修正点は以下の通りです。
(1) genericを「一般的」は文の意味として不自然だったので、「汎用的」に、修正
(2) majorityを「大多数」は言い過ぎなので「多く」に修正
(3) "in the usual way"を「いつものように」は変なので「通常の方法で」と修正
(4) allが訳出されていなかったので明示的に表現し、また「１行を上回る」は不自然なので「２行以上」に修正
=> ddl.sgml(5.3節 制約 の一部)の誤訳訂正と翻訳改善

doc/src/sgml/dml.sgml
主な修正点は以下の通りです。
(1) "the chapter after this"は単数なので、「本章以降」を「次章」に修正しました。また、"finally"が訳出されていなかったので、明示的に「いよいよ」としました。それに伴い、直前の"now"を「いよいよ」から「今度は」に変更しました。
(2) "appear"が「表示される」となっていましたが、画面に表示されるわけではないので「存在する」としました(もっと良い訳語がありそう)。また「列挙します」とありましたが、説明対象の例がそうなっていることを説明しているものなので、原文通り「列挙されています」としました。
(3) UPDATEの説明をしている部分について、modificationを「修正」とするの「は間違いを正す印象があるので「変更」としました。またupdatingを「更新する」と説明している部分は、さらに注をつけるイメージで"update"を追加しました。
(4) row(s)を「行（複数可）」とするのは訳しすぎで、かえって誤解を招くので、但し書きを削りました。
(5) WHERE条件に"match"する場合については「一致」を「適合」としました。
その他、なるべく原文に忠実な意味になるよう、訳語の変更などを行いました。
=> dml.sgml(6章 データ操作)の誤訳訂正と翻訳改善

doc/src/sgml/func.sgml
主な修正点は以下の通りです。
(1) "most widely used"の掛かり先が明確になるよう訳文を変更しました。
(2) "elsewhere"の訳し方がおかしかったので、訂正しました。
(3) 「シリーズ」は意味がわかりにくいので、「連番」としました。
(4) プログラム例のコメントに構文解釈の誤りがあったので、訳し直しました。
=> func.sgml(9.24節 集合を返す関数)の誤訳訂正と翻訳改善

doc/src/sgml/syntax.sgml
主な修正点は以下の通りです。
(1) 語句の順番を並べ替えて、文の後方にある語句を参照しなくても読めるようにしました。
(2) appendが「加える」となっていましたが、足し算するイメージになってしまうので「追記する」に変更しました。また、句点のところで改行を挿入しました。
(3) "possibly"の解釈が間違っていたので修正しました。"binds tighter"の解釈が間違っていたので修正しました。また句点のところで改行を挿入しました。
(4) "The two common uses"から始まるプログラム例を2つ含む長い文の解釈が間違っていたので、全面的に訳し直しました。
(5) 原文にない語句(「正しくは次の様にします」)を削除(上の例が正しくて、次の例はエラーなので、これは二重に間違っていたことになる)。またその直前の"this"を「これ」とすると曖昧なので「次の例」に訳を変えました。
(6) 理由の説明がわかりにくかったので、関係詞節を訳し下げて、修正しました。
=> syntax.sgml(4.2.9-10節 型キャスト、照合順序式)の誤訳訂正と翻訳改善

doc/src/sgml/func.sgml
主な修正点は以下の通りです。
(1) 拡張と標準準拠の説明の文章がしっくりこなかったので、表現を修正。
(2) "as one might naively expect"の意味が誤解されるような訳文になっていたので訂正。
(3) "including ..."の訳し方を全体的に統一
(4) strictの訳語の「厳密」がしっくりこなかったので、「厳格」に変更
(5) againの訳し方がおかしかったので、訂正
(6) 「比較した結果真(偽)でない値になった場合」は解釈が間違っていたので訂正
(7) 「それ以外その行」は意味がわかりにくかったので、「それ以外の場合、その行」と修正したついでに、改行をいくつか挿入。
(8) コロンを「以下の」として文を分けると、HTMLで改行がなくなると意味がわかりにくいので、訳文を改善。
=> func.sgml(9.23節 行と配列の比較)の誤訳訂正と翻訳改善

doc/src/sgml/ddl.sgml
=> fix typo for ddl.sgml

doc/src/sgml/ddl.sgml
主な修正点は以下の通りです。
(1) "column(s)", "row(s)"など英文法的な都合上、仕方なく"(s)"がついているもので、敢えて「（複数可）」などと訳す必要のないもの（あることで不自然になるもの）は、単に「列」「行」としました。
(2) "essential"の訳語を「本来の」から「本質的な」に変更しました。
(3) コロンの前後で文を分けていて不自然だったので、1文にしました。
(4) "not"が訳出されていなかった（文の意味が反対になっていた）のを訂正しました。
(5) セミコロンがそのまま日本語文に出ていたのを直しました。"has a match"の訳し方を原文に忠実になるように変更しました（前の訳は"does match"みたいだった）。また、「要求する」は文脈上、違和感があったので「必要となる」に変更しました。
=> ddl.sgml (5.3.5節 外部キー)の誤訳訂正と翻訳改善

doc/src/sgml/syntax.sgml
主な修正点は以下の通りです。
(1) 節の冒頭、および２番目のパラグラフは原文に忠実でなかったので全面的に翻訳を見直しました。
(2) "The following examples"で始まる文が原文の意味を取り違えていたので訳し直しました。「本節の例」とするのは、ちょっと訳しすぎですが、実際に指しているのは直後の関数定義より後の4.3.1-3で使われる例のことで、「以下の例」は誤解を招くし、「以降の例」もちょっと不自然な感じなので。
(3) "expression"は「表現」ではなく「式」としました。
(4) "Again"は、前言を繰り返しているのではなく、前と同じことが起きていることを指すので、訳し方を変更し、また句点で改行を入れました。
(5) 「パラメータの前」は意味が曖昧なので「パラメータより前」とし、また句点で改行を入れました。
=> syntax.sgml (4.3節 関数呼び出し)の誤訳訂正と翻訳改善

doc/src/sgml/advanced.sgml
advanced.sgmlとddl.sgmlでチュートリアルのcapitalsテーブルを参照していますが、advancedでは「行政府所在地」、ddlでは「州都」と訳していました。
「州都」の方が一般的だと思っているので、そちらに統一します。
=> advanced.sgml: "capital"の訳語を「州都」に変更

doc/src/sgml/ddl.sgml
主な修正点は以下の通りです。
(1) 「次のようにコマンドを使用」はちょっと違和感があった(原文に忠実でもない)ので「次のよう『な』コマンドを使用」としました。
(2) "see below"は、その直下の記述を参照しているので、「後述」ではなく「下記参照」としました。
(3) "constraints involving the column"のinvolveは「～を巻き込む」という意味なので「列を含む制約」ではなく「列に関連する制約」としました。
(4) 「テーブル制約として記述できない非NULL制約」だと、「テーブル制約として記述できる非NULL制約」もあるような感じがするので、訳し方を変えました。
(5) "Then the command is:"を「コマンドは以下の通りです」とするのは"Then"が訳されていないことを除けば原文に忠実だったのですが、その直前に制約名を調べる「コマンド」の話をしていて、文脈上は大きな誤解を招く表現になっていました。"Then"は「(制約名がわかったので)次は」、"the command"は「(制約を削除する)コマンド」という意味なので、思い切って意訳しました。
(6) "As with"の解釈が間違っていたので、訳を修正しました。
(7) "This"の指すものが「これ」では不明確だったので、「上記」としました。
=> ddl.sgml (5.5節 テーブルの変更)の誤訳訂正と翻訳改善

doc/src/sgml/syntax.sgml
見直したのは4.2.10節以降で、主な修正点は以下の通りです。
(1) "largest city population"の誤訳訂正(SELECT文を見ればわかるように、州の名前と、最大都市の人口しか検索していない)。
(2) 原文が"array ELEMENT type"なので忠実に訳すようにした。
(3) "rectangular"の訳を「四角形」から「長方形」に変更(配列なので、四角形なら長方形に決まっているかも知れないが…)
(4) "more than one"の誤訳訂正
(5) "another"を「別の」としていたが、「(t.*, 42)という行値の中に、"t.*"という"another row value"がある」ということなので、「もう一つの」と訳語を変更(大して変わらないかも知れないが、文脈上、「別の」は、上にある"t.*"とは「異なる」ものである感じがする)
(6) "inner row value"の訳語を変更すると同時に、構文解釈の怪しげな部分を変更。
(7) ダッシュ記号の解釈の誤りを訂正
(8) "as discussed"の参照先が9章なので、訳し方を訂正
(9) 式の値の話なので、determineの訳語を「判断」から「決定」に変更
(10) 「ショートサーキット」を日本語に変更
=> syntax.sgml (4.2節 評価式)の誤訳訂正と翻訳改善

doc/src/sgml/ddl.sgml
主な修正点は以下の通りです。
(1) oid列が作成される場合の説明について、訳文を原文に忠実なものにしました。
(2) tableoidからテーブル名を取得する方法の説明について、自然な日本語になるよう、to不定詞を目的ではなく結果の意味にして訳しました。
(3) "row version"の訳し方がバラバラだったので「行バージョン」に統一しました(が、これが適切かどうか、今一つ、自信はありません）。
(4) ctidの値が変わる場合について、"by VACUUM FULL"の掛かり先の解釈が間違っているように思えたので、修正しました。
(5) "should"を"must"と同じに訳していた文について、訂正すると同時に、自然な日本語になるよう訳を見直しました。
=> ddl.sgml (5.4節 システム列)の誤訳訂正と翻訳改善

doc/src/sgml/queries.sgml
主な修正点は以下の通りです。
(1) "varying"を"various"と誤読していたと思われるので修正
(2) "such as"の掛かり先の解釈が間違っていたので修正
(3) replaceableタグの内側は訳さない
(4) "qualified join"を「修飾付き結合」と訳していたが、これは"cross join"と対比して使っているので、schema-qualifiedから訳語を借りて「修飾付き」とするのは誤り。とりあえず「限定的な」としたが、もっと良い訳語はないか？
(5) "considerably more risky"を単に「かなり危険」と訳していたが、絶対的に危険なのではなく、比較対象に比べると危険度が高いという話なので、原文では省略されている"than..."を訳文では補った。
(6) "That does not matter..."の文が訳抜けしていたので翻訳
(7) その他、原文に忠実でないと思われる訳文や訳語について変更
=> queries.sgml (主に7.2.1.1項 結合テーブル)の誤訳訂正と翻訳改善

doc/src/sgml/queries.sgml
「7.2.1.2 テーブルと列の別名」から「7.2.1.4 テーブル関数」までを見直しました。
主な修正点は以下の通りです。
(1) テーブル別名の説明のニュアンスがちょっと違う感じがしたので、訳し直しました。なお原文は「テーブルや複雑なテーブル参照に別名をつけて、それを派生テーブルの参照に使用できる」で、「派生テーブル」は「複雑なテーブル参照」を指していると思われるますが、後半は「テーブルや派生テーブル」であるべきと考えて、語を補いました。
(2) "More interesting case"で始まる文の構文の解釈が誤っていたので、訳し直しました。
(3) "in the FROM clause"の掛かり先の解釈が間違っていたので、訂正しました。
(4) "ROWS FROM()"に関する説明に間違いが多かったので、ほぼ全面的に訳し直しました。
(5) "This column numbers the rows"の解釈が間違っていたので訂正しました。"number"は動詞で「数える」「番号をつける」といった意味になりますが、「数える」としました。
(6) "a corresponding number of columns"の解釈が間違っていたので訂正しました。"a number of columns"だと「多数の列」ですが、その"number"に"corresponding"という修飾語がついたと考えると理解できると思います。
=> queries.sgml (7.2.1節 FROM句) の誤訳訂正と翻訳改善

doc/src/sgml/datatype.sgml
主な修正点は以下の通りです。
(1) "rounding errors"を「丸め」と訳していたのを「丸め誤差」に変更
(2) 「Aの可能性がありますので、Bを行う必要があります」だと、「Bをすれば、Aの可能性を防げる」ことを示唆するが、原文はそんなことは言っていないので、単に「～可能性があり、また～必要があります」に訂正
(3) 長過ぎる文字列を代入するときの例外の説明がわかりにくかったので、訳文の分け方を変更して、さらに訳を一部修正
(4) "trailing spaces"が訳文に出ていなかったので、明示的に訳した
(5) "include"を「加わります」としていたが、誤解を招く可能性もあるので、「含まれます」に変更
(6) "without a length specifier"の掛かり先の解釈が間違っていたので訂正
=> datatype.sgml (8.2 通貨型、8.3 文字型)の誤訳訂正と翻訳改善

doc/src/sgml/ddl.sgml
(1) applicableを原文に忠実に「適用可能な」としました。
(2) "only"が訳文に出ていませんでしたが、重要な意味を持っているので、明示的に訳しました。
=> ddl.sgml (5.6 権限)の翻訳改善

doc/src/sgml/func.sgml, doc/src/sgml/func0.sgml, doc/src/sgml/func1.sgml, doc/src/sgml/func2.sgml, doc/src/sgml/func3.sgml, doc/src/sgml/func4.sgml
変更があるのはfunc4.sgmlだけですが、split.shの変更に伴い、func[0-4].sgmlの冒頭の注意書きのインデントが変わってしまったようです。このPRでマージすれば、次回以降はdiffにならなくなるので、このままとします。
それ以外の変更点は以下の通りです。
(1) "these functions"がなぜか「ここの関数」となっていたので「これらの関数」に修正しました。
(2) "using the output plugin"が訳抜けしていたので、訳しました。
(3) pg_replication_origin_session_is_setup関数の説明は原文に忠実なのですが、表の中でこの関数の説明だけ他と文体が違うので、「かどうかを返します」を補いました。
(4) 9.5.0の時に指摘された「補修」が残っている部分があったので、「保守」に訂正しました。
=> func.sgml (9.26.6, 9.26.8)の誤訳訂正と翻訳改善

doc/src/sgml/ddl.sgml
主な修正点は以下の通りです。
(1) "one or more"を「複数」と訳している箇所があったので、訂正しました。
(2) "conflict"の訳語を、「矛盾」から「競合」に変更しました。
(3) "For brevity"の訳し方がおかしかったので、修正しました。
(4) "other kinds"が「全種類」となっていたので訂正しました。
(5) 「形式上」の掛かり先がわかりにくかったので、移動した上で「形式的に」と修正しました。
(6) "first schema in the search path that exists"の訳文の意味が、日本語だけだと誤解されかねないものだったので、語を補ってわかりやすくしました。
その他、原文の意図が正しく伝わらない可能性があるように思えた訳文について、なるべく原文に忠実になるように訳を修正しました。
=> ddl.sgml (5.8 スキーマ)の誤訳訂正と翻訳改善

doc/src/sgml/storage.sgml
"for the statistics subsystem"の訳語が、「統計サブシステムのための」と
「統計用サブシステム用の」となっていて統一感がなかったので、簡潔性を重
視して「統計サブシステム用の」としました。
=> storage.sgmlの訳語を揃えました。

doc/src/sgml/logicaldecoding.sgml
9.5.1からの変更は、原文のtypo修正だけなので、日本語には変更はありません。
=> logicaldecoding.sgmlの9.5.2対応です。

doc/src/sgml/runtime.sgml
9.5.2対応分です。
合わせて、「コマンド」文言の位置、shouldの修正を入れてます。
=> runtime.sgmlの9.5.2対応

doc/src/sgml/queries.sgml
"not as portable"の解釈が間違っていたので修正しました。
=> queries.sgml (7.2.2 WHERE句)の誤訳訂正

doc/src/sgml/datatype.sgml
主な修正点は以下の通りです。
(1) 「μ秒」はすべて「マイクロ秒」に表記を変更しました(他のファイルは、調査した限り、すべて「マイクロ秒」でした)。
(2) "operations"が「演算子」となっていたので、「演算」に訂正しました。
(3) 「導入される前の年」は、その1年だけと解される可能性があるので、「導入される『より』前の年」としました。
(4) 「許容される」はかなり仰々しい感じがするので、単に「できる」としました。
(5) "PostgreSQL extension"を「PostgreSQL独自の拡張」と訳していましたが、「独自の」は訳し過ぎなので削除しました(他のファイルでも同じ表現がありそうですが)。
(6) 「オプションの精度値であるp」は意味がわかりにくかったので、修正しました。
(7) "explicit"の掛かり先がおかしかったので修正しました。
(8) "datetimes"を翻訳し、また"allow"の訳語を改善しました。
=> datatype.sgml (8.5 日付/時刻データ型)の誤訳訂正と翻訳改善

doc/src/sgml/ddl.sgml
主な修正点は以下の通りです。
(1) "any particular state"の"any"は重要な意味を持っているので、明示的に訳出(逆にparticularはあまり重要ではないので「特定の」は削除)しました。
(2) "extra"の訳語で「余分」だと不要な感じがするので「追加」に変更しました。
(3) 「500フィートより上に位置している」の掛かり先が誤解されるような訳文になっていたので、修正しました。
(4) 「あなたが」は日本語に出したくないので、削除し、それに合わせて語順を一部変更しました。
(5) データの伝搬についての訳文を、原文に忠実なものにしました。
(6) "exactly the table specified"の"exactly"を「テーブル『それ自体』」として明示的に訳出しました。
(7) "during CREATE TABLE"の掛かり先の解釈が間違っていたので訂正しました。
その他、表現がわかりにくいと思った部分をいくつか修正しています。
=> ddl.sgml (5.9 継承) の誤訳訂正と翻訳改善

doc/src/sgml/func.sgml, doc/src/sgml/func4.sgml
差分のレビューにはfunc4.sgmlを参照してください。
主な修正点は以下の通りです。
(1) 訳文がインデントされていたものを行頭から開始するようにしました。
(2) "with size units"を「サイズ単位」としていたのは意味が理解できないので、訳を修正しました。「kBやMBなどのサイズをつけて表現する」という意味なのですが、直前に「バイト単位」という語句もあり、ちょっと苦心しました。
(3) pg_table_sizeの説明を、なるべく原文に忠実になるように修正しました。
(4) "any"の訳し方がおかしかったので、訂正しました。
(5) 「（デフォルトで付与されている）」のカッコ書きの位置に違和感があったので移動しました。
(6) "size", "number"の訳抜けがあったので修正しました。
=> func.sgml (9.26.7 データベースオブジェクト管理関数) の翻訳改善

doc/src/sgml/datatype.sgml
主な修正点は以下の通りです。
(1) ”For some formats"の解釈が間違っていたので、訳し直しました。
(2) "handling", "exact"の訳語に違和感があったので、修正しました。また"input"を明示的に訳出しました。
(3) 「テキスト文字列のように」の掛かり先がわかりにくかったので、語順を変更しました。
(4) "It defaults to..."の解釈がおかしかったので、訳し直しました。
(5) "date of year"の訳語を「年間通算日」に変更しました。
(6) "except when"の解釈が間違っていたので、訳し直しました。また、"In this case"を素直に「この場合」と訳すと、どういう場合を指しているのかまったく理解不能なので、具体的に意訳しました。
(7) specialの訳語を「特殊」から「特別」に変更しました。
(8) midnightの訳語を「午前０時」としました。
=> datatype.sgml (8.5.1 日付/時刻の入力) の誤訳訂正と翻訳改善

doc/src/sgml/release-9.1.sgml
藤井です。
9.1のリリースノートで、一部タイトルのバージョン番号が
間違っていました。修正を取り込んでいただければと思います。
=> Doc ja 9 5

doc/src/sgml/queries.sgml
主な修正点は以下の通りです。
(1) "combining tables, views, eliminating rows..."で"combining"は"tables"のみに掛かっているという解釈になっていましたが、"tables (and/or) views"に掛かっていると見なして訳を変更しました。
(2) 「表示に使うように」は普通に読むと例示ではなく目的に解釈されそうなので、例示であることを明確にするため「表示での使用など」としました。
(3) "that done in the FROM clause"の解釈がおかしかったので、修正しました。
(4) "can be used to specify the default behavior"の解釈が間違っていたので修正しました。
(5) "sorted on enough columns"の解釈が間違っていたので修正しました。
その他、いくつか原文のみに存在する語句を明示的に訳出しました。
=> queries.sgml(7.3 選択リスト)の誤訳訂正と翻訳改善

doc/src/sgml/release-old.sgml
斉藤さんのメール（[jpug-doc: 5110] 「リリースx.x.x」のスペースの有無）に刺激を受けて https://pgsql-jp.github.io/jpug-doc/9.5.2/html/release.html を眺めたら、また別のところが気になってしまったので、直しています。
すべてrelease-oldの修正なので、あまり力を入れるべき所ではないとは思うのですが。
- 移行方法 → 移行に統一　（←これが目次で見える）
- バージョンx.y.zの前後の空白も削除（ただし、削除した結果、バージョン情報と前後の半角文字がくっついてしまうような場合には削除しない）
- 逆に言うと、削除した結果、半角文字と全角文字がくっつく程度なら積極的に空白を削除。
- 原則一文一行に
- out-of-the-boxの訳が明らかにおかしいので修正
=> improve translation of release-old.sgml

doc/src/sgml/datatype.sgml
8.5.2-8.5.5を見直しました。
変更箇所が多いので、一部の説明だけで、個別の変更箇所の説明は省略します。不明点などあれば、遠慮なく、コメントをください。
(1) 節のタイトルに「の」を補いました。8.5.1節のタイトルが「時刻/日付『の』入力」なので、それに体裁を合わせるのも1つの理由です。またインデントを原文に合わせて調整しました。
(2) オリジナルの3721-3行目および3756行目の変更は、改行の挿入をしたため、変更部分がハイライトされていませんが、翻訳を大幅に見直しているので、注意してレビューしてください。
(3) オリジナルの3914-6行目は、別々の文にすると意味が理解できないので、1つの文につなげましたが、接続詞を補っただけで、訳自体は変更していません。
=> datatype.sgml(8.5節 日付/時刻データ型)の誤訳訂正と翻訳改善

doc/src/sgml/queries.sgml
(1) "this is the order in which the rows are actually returned"について、「実際に行が返された順序である」という訳文では、「UNIONを構成する各SELECT文が返した順序「と解釈してしまうが、正しくは「UNIONされたSELECT文全体が返す順序」である。「返された」を「返される」と修正するだけでも十分だが、"there is no guarantee that"と組み合わせて意味が明確になるように「この順序で返される保証はない」とした。
(2) "union compatible"の訳語の「和両立」は全く意味が理解できないので「union互換」とした。本節では"union"を「和」と訳しているが、この段落はunion, intersect, exceptに共通の話をしているので、unionのまま残した方が良いと判断。
=> queries.sgml(7.4 問い合わせの結合)の誤訳訂正と翻訳改善

doc/src/sgml/func.sgml, doc/src/sgml/func3.sgml
レビューにはfunc3.sgmlを使用してください。
元の訳では"dimension(s)"の訳語が「次元」「次数」でかなり揺れており、修正でも迷ったところはありますが、"number of dimensions"は「次元数」、"(requested) dimension"は「次数」、"dimensions"は「次元」と訳してみました。
配列の"upper(lower) bounds"について「上限」「下限」が使われていましたが、わかりにくいと思ったので、原文に"subscript"という語がなくても、それを補って「添字の上限(下限)」と訳してみました。
"string"が「文字」と訳されていた部分が多かったので、気づいたものはすべて「文字列」に訂正しました。
=> func.sgml(9.18 配列関数と演算子)の誤訳訂正と翻訳改善

doc/src/sgml/config.sgml
statement_timeoutの訳が日本語的におかしいのを修正、また句読点で文を分けました。
=> config.sgmlの訳がおかしいのを修正しました。

doc/src/sgml/logicaldecoding.sgml
マージに変更点を反映して頂いているので、★印のコメントを削除しただけです。
=> logicaldecoding.sgmlの9.5.3対応です。

doc/src/sgml/queries.sgml
(1) "if the query itself yields less rows"の"yields less rows"の部分を明示的に訳出しました。
(2) "before beginning to return rows"の訳を原文に忠実にしました。
(3) "unpredictable"の掛かり先が誤解されるような訳文になっていたので訂正しました。
(4) "in what ordering?"の訳を原文に忠実にしました。
(5) "very likely"を明示的に訳出し、また"(yielding different row orders)"の主語が"different plans"であることが明快にわかるような訳文にしました。
(6) "inconsistent"の訳語として「矛盾した」は違和感が強かったので「一貫しない」としました。
=> queries.sgml(7.6 LIMITとOFFSET)の誤訳訂正と翻訳改善

doc/src/sgml/queries.sgml
(1) "actual data type"の"actual"の掛かり先が明確になるようにしました。
(2) 「実質以下と同じ」は誤読される可能性が高いので、修正しました。
(3) "the column names"の"the"を明示的に訳出しました（そうしないと誤読される可能性が高い）。
(4) "different"を「他の」と訳すのはおかしいので、修正しました。
(5) "VALUES followed by expression lists"の訳が間違っていた（順序が逆だった）ので訂正しました。
(6) "anywhere"を明示的に訳出しました。
(7) "attach ～ to it"の訳が間違っていた（主客が逆だった）ので訂正しました。
=> queries.sgml(7.7 VALUESリスト)の誤訳訂正と翻訳改善

doc/src/sgml/queries.sgml
(1) 「並び替え」を全面的に「並べ替え」に書き換えました。なお「並び替えする」については「並べ替える」としました。
(2) "would be valid in select list"の訳がわかりにくかったので修正しました。なお、元の訳が「選択リスト内で有効な」としていたのは、原文に忠実なように見えますが、仮定法の"would"が無視されており、正確には「選択リスト内で(もし使用されたなら)有効な」ということなので、「選択リスト内で使用可能な」と変更しました。
(3) 「前の値と同じ値を持つ行」は意味が理解できないので訳文を修正しました。
(4) "consider"の解釈が間違っていたので、文全体の訳を見直しました。直訳すると「個別に考慮される」ですが、わかりやすくなるよう「適用される」としました。
=> queries.sgml(7.5 行の並べ替え)の誤訳訂正と翻訳改善

doc/src/sgml/queries.sgml
主な変更点は以下の通りです。
(1) CTEとだけ書かれると何の略かわからないので、直前の「共通テーブル式」に注を追加しました。
(2) "substitute A for B"の解釈が間違っていたので訂正しました。
(3) "this query"の"this"を明示的に訳出しました（そうしないと誤読される可能性が高いので）。
(4) "eventually...or else"の解釈が間違っていたので、ブロック全体にわたって翻訳を見直しました。
(5) "the optimizer is less able to"で始まる文の訳文がおかしかったので、訳し直しました。
(6) "the WITH clause is attached to the INSERT, not the sub-SELECT within the INSERT"の解釈が間違っていたので訂正しました。なお、文頭の"fine"は「細かい」の意かも、という気がちょっとだけしているのですが、元の訳のままにしています。
(7) "It is the output of ... that ..."の強調構文を、教科書通りの「(that ...)であるのは(it is ...)である」という形式の訳にしました。
(8) "only as far as"の"only"を明示的に訳出しました。
(9) "one of the modifications"を原文に忠実に「変更の1つ」とし、文末の"which one"については、わかりやすくなるよう、その後に省略されている動詞を補って訳しました。
(10) "only the update is performed"が訳抜けしていたので、訳しました。
その他、不自然な感じがした言い回しや訳語を修正しました。
=> queries.sgml(7.8 WITH問い合わせ)の誤訳訂正と翻訳改善

doc/src/sgml/func.sgml, doc/src/sgml/func3.sgml
func3.sgmlは9.5.3の原文の変更部分がマージされていなかったので、原文の変更と合わせて確認できます。
=> func.sgmlの9.5.3対応：レビューはfunc3.sgmlを使用してください

doc/src/sgml/datatype.sgml
(1) "lexeme"の訳語が「字句単位(要素)」となっていたのを「語彙素」に変更しました。
そもそも「語彙素」が一般的な訳語のようですし、
https://ja.wikipedia.org/wiki/%E8%AA%9E%E5%BD%99%E7%B4%A0
この節と、12章は密接に関連していて訳語を合わせるべきですが、12章では「語彙素」としていて、かつ出現数も圧倒的に多いです。
他に、func.sgml、unaccent.sgml、release-9.4.sgmlでも「語彙素」でした。catalogs.sgmlにも2箇所"lexeme"があり、こちらは「字句」としていますが、これは別にPRを作りたいと思います。全体がそういう状態なので、MLでの議論やIssuesへの登録は不要と判断しました。
(2) "which are words"の解釈が間違っていたので訳し直しました。
(3) "having to double quote marks"の解釈が間違っていたので訳し直しました。
(4) "is not shown on output:"の解釈がちょっと違っていたので、修正しました。
(5) "for the application"の解釈がちょっと違っていたので、修正しました。
(6) "to normalize the words appropriately for searching"の解釈が間違っていたので、修正しました。
(7) "Again"の訳語を直しました。
(8) "which restricts..."の訳がおかしかったので、修正しました。
=> datatype.sgml (8.11 テキスト検索に関する型)の誤訳訂正と翻訳改善

doc/src/sgml/ref/create_tablespace.sgml
#603 
"define"と"can"の訳抜けを訂正し、さらに日本語としてわかりやすくなるように、訳文の構造を変更しました。
=> CREATE TABLESPACEの説明を改善(Issues #603)

doc/src/sgml/ref/drop_conversion.sgml
#607 
DROP CONVERSIONとDROP TRANSFORMの概要がいずれも「変換の削除」となっていたので、CREATE CONVERSIONの説明に合わせて、DROP CONVERSIONを「符号化方式変換の削除」としました。
説明の中でも繰り返し、「変換」が出てくるので、ちょっとやり過ぎかも知れませんが、最初の「変換」についてだけ、「符号化方式変換」とし、さらに訳注をSGMLコメントとして入れました。
=> DROP CONVERSIONの概要の修正(Issues #607)

doc/src/sgml/stylesheet-custom.xsl, doc/src/sgml/stylesheet.xsl
xslthtmlの変更に伴いセクション内の目次の出力が変わっていたため修正。
修正前 https://pgsql-jp.github.io/jpug-doc/9.5.2/html/spi-interface.html
修正後 https://pgsql-jp.github.io/jpug-doc/9.5.3/html/spi-interface.html
変わってしまっていたのはsect1/refentryという構成の場合。
=> sect1の目次にrefentryの一覧が出るようにする #586

doc/src/sgml/extend.sgml, doc/src/sgml/ref/pg_xlogdump.sgml
subdirectoryの訳を「サブディレクトリ」に統一しました。
=> fix translation of 'subdirectory'

doc/src/sgml/release-9.1.sgml, doc/src/sgml/release-9.2.sgml, doc/src/sgml/release-9.3.sgml, doc/src/sgml/release-9.4.sgml
release-9.[1-4] の9.5.3対応です。恒例のスクリプトを使った作業以外に、以下のようなこともついでにやってます。
- 原文と対応しない空行の削除。
- 文途中での改行の削除。その逆も。
- バージョンもしくはリリースとその番号の間の空白の削除。
- back-patchの訳の見直し。（「バックパッチ」とやるとコンパイラの用語になるっぽいです。）
=> update release-9.[1-4] for 9.5.3

doc/src/sgml/release-9.5.sgml
原文に合わせ Verite を V&eacute;rit&eacute; に変更。
作業コメントを削除。
=> 作業途中とみられる記述が残っていたものを修正。

doc/src/sgml/catalogs.sgml, doc/src/sgml/ref/create_table.sgml, doc/src/sgml/ref/insert.sgml
「exclusion constraint」が「除外制約」となっていた箇所を「排他制約」に修正しました。
対訳集に合わせています。
よろしくお願いします。
=> 「exclusion constraint」の訳を「排他制約」に修正

doc/src/sgml/datatype.sgml
多くは軽微な修正です。
(1) 使用例のタイトルで「～を使って」は違和感があったので「～の使用」に変更しました(2箇所)。
(2) "build"の訳語で「構築」は意味が曖昧(別の意味に取られる)ので、より意味が限定的だと思われる「ビルド」に変更しました。
(3) entryタグのインデントを慣例に従って原文に合わせました。
(4) "(be) reordered"の訳を「並べられる」から「並べ替えられる」に変更しました。
(5) サブネットの説明、アドレスの入力形式の説明を、なるべく原文に忠実になるように訳し直しました。
(6) "visualize"の訳語として「顕在化」は違和感が強かったので「可視化」としました(もっと良い訳語がありそう)。
(7) セミコロンで訳文を2つに分けることで、文と文のつながりがわかりにくくなっていた箇所について、1文に統合しました。
(8) "as explained"の訳語がおかしかったので、訂正しました。
=> datatype.sgml(8.6-8.10)の誤訳訂正と翻訳改善

doc/src/sgml/datatype.sgml
どうしても直したかったのは、"adding a hyphen after any group of four digits"の"any"が「すべて」になっていた部分です。「すべて」だと4桁ごとにハイフンを挿入することになるけど、正しくは、4桁ごとに区切った場所であれば、どこでもハイフンを挿入可能（挿入しなくても良い）なので、訂正しました。
合わせて、その前後も、意味が明確になる（誤解されない）ように訳文を修正しました。
=> UUIDの別形式の説明の訳を修正

doc/src/sgml/high-availability.sgml
同じ "Application of a vacuum cleanup record from WAL" に対する訳語が、
その一つ上の文と違っていたので、一つ上の文に合せました。
=> high-availability.sgmlのタイポ修正です

doc/src/sgml/release-9.1.sgml
「後方に移動」や「後方に移る」ではまったく意味が通じないので、より適切なものに変更しました。
=> 9.1のリリースノートの文言を修正しました。

doc/src/sgml/ddl.sgml
1箇所を除き、原文の変更箇所の対応のみです。
原文の変更箇所の周辺で、"テーブルをconsiderした"が「テーブルを作成した」としているのがあり、文脈的には大きな間違いではないのですが、原文に忠実になるよう「検討」に変更しました。
=> ddl.sgmlの9.5.4対応

doc/src/sgml/func.sgml, doc/src/sgml/func1.sgml, doc/src/sgml/func4.sgml
差分のマージはfunc.sgmlに対してのみ実行されているため、func1.sgmlおよびfunc4.sgmlでは、原文の変更点も差分として表示されています。
=> func.sgmlの9.5.4対応

doc/src/sgml/release-9.1.sgml, doc/src/sgml/release-9.2.sgml, doc/src/sgml/release-9.3.sgml, doc/src/sgml/release-9.4.sgml
release-9.5.sgmlがマージされましたのでrelease-9.[1-4].sgmlの9.5.4対応です。
クォート、クオートは気にはなっていますが、9.5そのままです。
=> update for 9.5.4

doc/src/sgml/auth-delay.sgml, doc/src/sgml/bki.sgml, doc/src/sgml/brin.sgml, doc/src/sgml/catalogs.sgml, doc/src/sgml/datatype.sgml, doc/src/sgml/ecpg.sgml, doc/src/sgml/external-projects.sgml, doc/src/sgml/func.sgml, doc/src/sgml/indexam.sgml, doc/src/sgml/indices.sgml
原文が9.6RC1とdiffがあるものを修正（一部は以前のバージョンからも含む）
func.sgmlのみfunctions-comparison-tableがfunctions-comparison-op-tableに
変更されていたためエラーとなっていた箇所を修正
=> 9.6RC1の差分チェック

doc/src/sgml/ref/grant.sgml
明示的には訳出されない"his"→"their"などの変更のみなので、訳文は変更していません。
=> grant.sgmlの9.6対応です。

doc/src/sgml/mvcc.sgml
=> 9.5以前からあるmvcc.sgmlの誤訳を修正しました。

doc/src/sgml/mvcc.sgml
本来過去のバージョンは修正しないポリシーですが、完全な誤訳の修正なので重要度が高いと思い、PRしました。
=> doc_ja_9_6でマージいただいたmvcc.sgmlの誤訳修正の doc_ja_9_5 への back patch です。

doc/src/sgml/auto-explain.sgml, doc/src/sgml/install-windows.sgml
auto-explain.sgml
install-windows.sgml
install-windowsで段落がまるまる無くなっているように見えますが、対応する訳は（その直前に）既にありますので問題ないはずです。
=> update auto-explain and install-windows to 9.6.0

doc/src/sgml/pgstandby.sgml, doc/src/sgml/plpython.sgml
plpython.sgml
pgstandby.sgml
plpythonの方はPythonに詳しい人に見て頂けると助かります。(私個人はPythonを良く知っている訳ではないので、、、)
=> update pgstandby and plpython to 9.6.0

doc/src/sgml/func.sgml, doc/src/sgml/func1.sgml, doc/src/sgml/func2.sgml
パターンマッチの9.6対応時に気になってしまったので、Issues #480 のmatchの訳語を一括で対応しました。
そのため、9.6の変更が埋もれてしまっている感じですが、9.7節（パターンマッチ）の変更は、6143行目からの"positive/negative lookbehind"のみです。
9.8節（データ型書式設定関数）は分割ファイルがfunc2.sgmlになっているので、そちらをレビューしていただければ良いかと思います。
=> func.sgmlの9.7節（パターンマッチ）および9.8節（データ型書式設定）の9.6対応です。

doc/src/sgml/high-availability.sgml
一部旧訳の誤訳を修正しています。特に、以下の訳は、スタンバイが待つとしていますが、正しくは待つのはスタンバイではなくてコミットの方です。重大な誤訳なので、バックパッチしたい気もしますが...
-<varname>synchronous_commit</>を<literal>remote_write</>に設定することで、スタンバイサーバはコミットされたレコードをスタンバイサーバがメモリ上に受け取ったことを確認するまでコミットを待つようになります。しかし
=> high-availability.sgmlの9.6対応です。

doc/src/sgml/ref/pg_xlogdump.sgml
literalタグがreplaceableタグに修正されただけです。
=> pg_xlogdump.sgmlの9.6対応です。

doc/src/sgml/gin.sgml, doc/src/sgml/sslinfo.sgml
=> update gin and sslinfo to 9.6.0

doc/src/sgml/sources.sgml
おかしな英文が2箇所あったので、訳注をSGMLコメントとして入れました。
=> sources.sgmlの9.6対応です。

doc/src/sgml/gist.sgml
=> update gist to 9.6.0

src/backend/catalog/sql_features.txt.ja, src/backend/utils/errcodes.txt.ja
doc/src以外のところにある（のだけれども翻訳が必要な）以下のファイルの9.6.0対応です。
src/backend/catalog/sql_features.txt.ja
src/backend/utils/errcodes.txt.ja
=> update files not in doc/src to 9.6.0

doc/src/sgml/runtime.sgml
9.6.0をスキップして、9.6.1の原文変更のマージと翻訳を一気に行ったため、原文変更も差分として出ています。
=> runtime.sgmlの9.6.1対応です。

doc/src/sgml/config.sgml
9.4/9.5については修正されましたが、9.6がまだだったので、修正しました。
=> [pgsql-jp: 41911] maintenance_work_memのデフォルト値を修正

doc/src/sgml/logicaldecoding.sgml
作業用の目印である「★変更あり」が残っているのを見つけました。
=> remove place holder? (logicaldecoding.sgml )

doc/src/sgml/maintenance.sgml
maintenance.sgmlに★が残っていましたのでその対応です。
1つ目は対応漏れのようですが、2つ目はよく分かりません。対応する原文は変わっているようには見えませんので、★を付ける場所が間違っているのかもしれません。
=> fix typos?

doc/src/sgml/ref/alter_trigger.sgml, doc/src/sgml/ref/create_function.sgml, doc/src/sgml/ref/create_sequence.sgml, doc/src/sgml/ref/select.sgml
alter_triggerとcreate_sequenceは翻訳漏れなので、訳しました。
create_sequenceとselectは、該当する原文が2重に入っていたので、単純に削除しました。
=> ★が残っていたファイルについて修正(jpug-doc:5292)

doc/src/sgml/config.sgml
"directive"が「コマンド」と訳されていますが、これは無理がある感じがしますし、対訳表では「ディレクティブ」になっているのでそのように変更しました。
後は細かな訳抜けや、不自然な訳を修正しました。
=> 9.6のconfig.sgmlの細かな誤訳や訳抜けを修正しました。

doc/src/sgml/ddl.sgml, doc/src/sgml/isn.sgml, doc/src/sgml/lobj.sgml, doc/src/sgml/problems.sgml, doc/src/sgml/ref/clusterdb.sgml, doc/src/sgml/ref/create_aggregate.sgml, doc/src/sgml/ref/create_conversion.sgml, doc/src/sgml/ref/createlang.sgml, doc/src/sgml/ref/droplang.sgml, doc/src/sgml/ref/fetch.sgml, doc/src/sgml/ref/initdb.sgml, doc/src/sgml/ref/insert.sgml, doc/src/sgml/ref/lock.sgml, doc/src/sgml/ref/pg_config-ref.sgml, doc/src/sgml/ref/pg_ctl-ref.sgml, doc/src/sgml/ref/pg_dump.sgml, doc/src/sgml/ref/pg_dumpall.sgml, doc/src/sgml/ref/unlisten.sgml, doc/src/sgml/ref/update.sgml, doc/src/sgml/release-7.4.sgml, doc/src/sgml/release-8.0.sgml, doc/src/sgml/release-8.1.sgml, doc/src/sgml/release-8.2.sgml, doc/src/sgml/release-8.3.sgml, doc/src/sgml/release-old.sgml, doc/src/sgml/tablefunc.sgml
「－－」のコメントアウトについて、「－」を「＆＃０４５；」とすべきものが、＃や；が欠落していたり、０４５ではなく０５５になっているものがあったので、grepで見つかったものをすべて置換しました。
なお、grepで探した後、grep -v で正しいパターンがある行を除外したので、１行内に正しいパターンと誤ったパターンが混在している場合は、見落としている可能性を排除できません。
=> Issues #788 （ハイフンのコメントアウトの誤り）の修正

doc/src/sgml/config.sgml
いくつか修正すべき点（誤訳、わかりにくい訳）があったので、まとめてPRします。
改行を入れる・消すべき箇所、インデントを消すべき箇所も多数ありますが、訳を直したブロック以外は放置しています。
Issues #810 のoverrideの該当箇所も多数ありますが、それについてはごく一部しか直していません。
=> 19.1節 パラメータの設定(config.sgml)の誤訳訂正と翻訳改善

doc/src/sgml/config.sgml
以下の修正を行いました。
(1) カッコ内の文の訳し方と外側の文章への修飾関係が間違っていたので修正しました。また、elsewhereの訳語がおかしかったので修正しました。
(2) "should create for use by..."の解釈が間違っていたので修正しました。
(3) "and/or"を「そして/もしくは」とするのは不自然なので、単純に読点で置換しました。原文の意味を厳密に残すなら「～のうちの1つ以上」などとすることになりますが、意味的に考えて、そこまでする必要はないでしょう。
(4) "any of"の訳し方が不自然だったので、修正しました。
=> 19.2節（config.sgml ファイルの場所）の翻訳改善

doc/src/sgml/config.sgml
Wheneverの解釈が間違っていて、意味の通じない日本語になっていたのを修正しました。
そのついでに、当該段落についてのみ、インデントを削除しました。
=> superuser_reserved_connectionsの説明に関する誤訳訂正

doc/src/sgml/stylesheet.xsl
本家のHEADからバックポート
#541 の対応です。本家xslthtmlに移行する関係で索引ページの対応がされていたので、バックポートしました。
これを入れてビルドした結果が以下です。
http://noborus.github.io/pgsql-jp/jpug-doc/9.6.1/html/bookindex.html
=> 索引のクイックリンクの追加 

doc/src/sgml/ref/alter_table.sgml
960のマージの時に、原文が重複して挿入されてしまっていたようです。
同じものが翻訳部分にコメントアウトされて残っているので、重複する英文のブロックを丸ごと削除しました。
=> 原文が残っていた部分を削除 ( #821 )

doc/src/sgml/logicaldecoding.sgml
Issuesで報告された"replica identity"が「レプリカエンティティ(replica entity)」となっているのは、どう見ても単純ミスのようなので修正しました。
実は該当の文を読み返してちょっと気になった箇所があります。その直前の「UPDATEとDELETEによって古いバージョンの行へのアクセスが可能かどうか」は"The availability of old row versions for UPDATE and DELETE"を訳したもので、構文解釈的にはこれが正しいように思いますが、言いたいことは「UPDATEとDELETEが古い行バージョンにアクセスできるかどうか」ではなく、「UPDATEあるいはDELETEによって削除された古い行バージョンを、プラグインが参照できるかどうか」ではないかと思うのです。
=> Fix typo for issues #823

doc/src/sgml/config.sgml
"after which"の解釈が間違っていて、全くおかしな説明になっていたので修正しました。
"number of seconds of inactivity"は、直訳すると「活動のない秒数」、従前の訳は「待機状態となっている時間」ですが「クライアントとのやり取りがなくなった後（の時間）」としてみました。
=> tcp_keepalives_idleの誤訳訂正

doc/src/sgml/config.sgml
notが訳抜けして反対の意味になっていたので修正しました。
ついでにインデントを削除しました。
=> ssl_ecdh_curveの説明の誤訳訂正（notの訳抜け）

doc/src/sgml/config.sgml
unix_socket_directories, unix_socket_group, unix_socket_permissionsの説明に関する誤訳訂正と翻訳改善です。
翻訳部分のインデントの削除、句点での改行の挿入をした部分以外については、別途、変更部分にコメントを入れます。
=> 設定パラメータ unix_socket_* に関する誤訳訂正と翻訳改善

doc/src/sgml/config.sgml
"simultaneously"が"set"に掛かるように訳されていましたが、正しくは"can be in the prepared state"に掛かっているので、訳を修正しました。
そのついでに、少し、軽微な修正をしました。
(1) 「トランザクション機能を無効にします」は主語が存在せず、不自然な感じがするので、「トランザクション機能が無効になります」に変更しました。
(2) should, want, at leastの訳し方を変更しました。
=> max_prepared_transactionsの誤訳訂正

doc/src/sgml/Makefile
HEADではformatをしないように修正されていたのでバックポート。
formatをするとwrapのblockで改行がされない場合がありました。
またmake INSTALLのエラー修正も入れています。
=> PDF作成の --format を止める

doc/src/sgml/config.sgml
変更点は以下のとおりです。
(1) 「データベースサーバが使用する共有メモリバッファのために使用するメモリ量」の1つ目の「使用する」を削除しました。
(2) カッコ付きの「initdbの過程で決定されます」の訳出位置が不自然だったので、移動しました。
(3) カッコ内の「デフォルト値以外のBLOCKSZでこの最小値は変化します」がわかりにくいので、訳し直しました。
(4) 「1GBまたはそれより多い」を、より自然な「1GB以上」に変更しました。
(5) "less than 1GB"が「1GB以下」になっていましたが、より正確に「1GB未満」としました。
(6) "Also, on Windows"の訳し方を「同様にWindowsでは」から「また、Windowsでも」と修正しました。
(7) "not as effective"を「有効ではありません」と訳していましたが、"as"は「Unix系と比較して、それほど」のニュアンスなので「『あまり』有効ではありません」としました。
(8) "The useful range of"の"useful"が訳出されていなかったので、「有効な」を追加しました。
=> shared_buffersの説明の翻訳改善

doc/src/sgml/mvcc.sgml
MVCCのRead Committedの動作例、およびその前後の説明が、意味の通らないものになっていたので、訳し直しました。
=> Read Committedの説明の誤訳訂正

doc/src/sgml/config.sgml
「コストに基づくVacuum遅延」の説明において、"to allow administrators to reduce..."および"for manually issued VACUUM command"の構文解釈に誤りがあったので、それぞれ訳し直しました。
=> Cost-based vacuum delayの説明に関する誤訳訂正

doc/src/sgml/config.sgml
(1) 「読み取り専用問い合わせの情報」は"required to run"が訳抜けしているので、訳し直しました。
(2) "can be safely skipped, which can make those operations much faster"の解釈がおかしかったので修正しました。
=> wal_levelの説明の誤訳訂正

doc/src/sgml/config.sgml
"when it commits"の掛かり先の解釈が間違っていたので、訳し直しました。
そのついでに、その2つ後の文の「単一の複数文トランザクション(single multistatement transaction)」がわかりにくいと思ったので、"single"を副詞的に訳して「一つだけ」としました。
=> synchronous_commitの説明の誤訳訂正

doc/src/sgml/maintenance.sgml
#854 で報告があった翻訳漏れです。
"forensic"をどうしようかと思いましたが、IT用語ではカタカナで使われているので、ここでもそうしました。
また、一読しただけでは、(2)と(1)の意味がわからなかったのですが、どうやらFrozenTransactionIdとBootstrapTransactionIdがいずれも定数で、その実際の値のようです。もうちょっとわかりやすい訳し方があるかも…と思いつつ、良いアイデアが浮かばないので、そのままにしてあります。
=> 注記に翻訳漏れがあったので翻訳しました

doc/src/sgml/config.sgml
'PostgreSQL expects "can" be executed'の"can"が訳出されておらず、意味的に重要だと思うので、訳し直しました。
そのついでの 細かな修正ですが、'I/O operation'の訳を「I/O作業」から「I/O操作」に変更しましたが「I/O処理」の方が良いかも、とも思っていますので、ご意見がありましたら、遠慮なく、コメントください。
また、"affect"を「有効です」と訳していたのを、「影響します」に変更しました。
=> effective_io_concurrencyの説明の翻訳改善

doc/src/sgml/config.sgml
fsyncを停止して良い状況の例、およびその次の段落については、大幅に訳し直しました。
それ以外についても、おかしな表現を訂正しました。
=> fsyncの説明の誤訳訂正

doc/src/sgml/config.sgml
"it might be necessary..."の文の構文解釈を誤っていたので、訳し直しました。
そのついでに、オプションを列挙している部分の説明の括弧書きが連用形になっているのが不自然だったので、終止形に変更しました。
「ライトスルー」が気になったのですが、目をつぶってしまいました。良い訳語の案があれば、追加修正します。
=> wal_sync_methodの説明の誤訳訂正

doc/src/sgml/config.sgml
好みで言えば、"WAL replay"は「WAL再生」、"decompression"は「解凍」と訳したいのですが、すぐ次の段落にも同じ用語があったので、そちらに訳語を合わせました。
=> wal_compressionの説明で訳抜けしていた文を翻訳しました

doc/src/sgml/config.sgml
修正点は以下の通りです。
(1) 「いかなる%pは」はわかりにくいので、「すべての%pは」としました。
(2) 原文が"path"なのに「絶対パス」と訳されていた(しかも実際には相対パス)のを、単に「パス」としました。
(3) 「実際の%文字」はわかりにくいので「%文字そのもの」としました。
(4) archive_commandに/bin/trueのようなコマンドを設定する場合のくだりがわかりにくかったので、訳し直しました。
=> archive_commandの説明の誤訳訂正と翻訳改善

doc/src/sgml/config.sgml
"more probable"を「確実にします」と訳していたので、正確に「確率が高くなります」としました。
そのついでに、より自然な日本語にするために、「commit_delay遅延」に『の』を補う、"before"を(原文に忠実に)「前に」としていたのを、(意味的に適切と考えられる)「ときに」に変更しました。
=> commit_siblingsの説明の誤訳訂正

doc/src/sgml/mvcc.sgml
シリアライザブルの説明における「述語ロック」の説明がわかりにくかったので、大幅に訳を直しました。
主な誤訳のポイントは以下の通りです。
(1) "had it run first"は"if it had run first"と同じで、仮定法過去完了の仮定部分ですが、そのように解釈されていなかったので訳し直しました。
(2) "which could block other users"は、仮定法の結論部分で、「（テーブルロックを取得するなら）他のユーザをブロックすることになりますよ」という意味なので、カッコ書きの位置を移動して、訳を少し変えました。
(3) pg_locks/mode/SIReadLockの関係がわかりにくかったので、訳し直しました。
(4) "past transaction commit"はわかりにくいですが、構文的には"past"は前置詞で「transaction commitの後」と解釈すべきなので、そのように訳し直しました。
それ以外にも、いくつか細かく修正しています。
=> 述語ロックの説明の誤訳訂正と翻訳改善

doc/src/sgml/mvcc.sgml
誤解を招くと思える表現2箇所を修正しました。
(1) 「ロックを強制的に獲得する」は、他のトランザクションがロックを保持していてもそれを奪い取るような印象さえ受けます。"obtains an exclusive lock ... to enforce that"のenforceが強制するのは、「TRUNCATEを安全な場合にしか実行しないようにすること」であって、そのためにロックを獲得する、と言っているので、そういう意味になるよう、訳し直しました。
(2) "outstanding lock"を「重要なロック」と訳していましたが、"outstanding"には"extremely good"の他に"not yet done"の意味があり、ここは後者の意味で使っていると思うので、「残っている」に変更しました。
=> 明示的ロックの説明の翻訳改善

doc/src/sgml/runtime.sgml
(1) "and then create the data directory within that"が訳されていなかったので、翻訳しました。
(2) "This avoids permissions problems"の解釈が間違っていたので、訳し直しました。
(3) そのついでの翻訳改善として、インストールは」→「インストールでは」、「ファイルシステム上でのデータベースクラスタを作成」→「ファイルシステム上にデータベースクラスタを作成」、「データディレクトリを～最上位ディレクトリを使用」→「最上位ディレクトリをデータディレクトリとして使用」などの修正をしました。
=> セカンダリファイルシステムの説明の訳抜け部分の翻訳、誤訳訂正と翻訳改善

doc/src/sgml/mvcc.sgml
"in which"は"the contexts"だけに掛かると解釈すべきだと思いますが、"the available lock modes and the contexts"に掛かるとして訳されていて、不自然な文章になっていたので、訳し直しました。
=> テーブルレベルロックの説明の翻訳改善

doc/src/sgml/func.sgml, doc/src/sgml/func3.sgml
"Partial Mode"がなぜか「並列モード」と訳されていたので、「部分モード」に変更しました。
=> Partial Modeの誤訳訂正

doc/src/sgml/sources.sgml
=> sources.sgmlの9.6.2対応

doc/src/sgml/runtime.sgml
18.3節についての比較的軽微な翻訳改善です。
(1) "source distribution"の訳語を、他のファイルで主に使われている「ソース配布物」に変更しました（2箇所）。
(2) "server"がなぜか「＜command＞postmaster＜／command＞」となっていたのを「サーバ」に変更しました。
(3) カッコ内にパラメータ名だけが記述されているものを「～を使用して」と訳しているのが不自然だったので、「を使用して」を削除し、訳出箇所を変更しました。
(4) quoteタグ内は原則として訳すべきなので、"illegal system call"を翻訳し、また、その後の日本語を微修正しました。
=> 「データベースサーバの起動」についての翻訳改善

doc/src/sgml/config.sgml, doc/src/sgml/release-8.3.sgml, doc/src/sgml/release-8.4.sgml, doc/src/sgml/release-9.0.sgml, doc/src/sgml/release-9.1.sgml
[jpug-doc:5346]で提起した件で、"logging collector"の訳語を「ログ収集機構」に統一しました。
=> "logging collector"の訳語を「ログ収集機構」に統一

doc/src/sgml/xaggr.sgml
9.6.2対応に加えて以下の修正を入れています。
overloadingをオーバーライドからオーバーロードに修正
不要なスペースの除去
=> xaggr.sgmlの9.6.2対応です。

doc/src/sgml/release-9.2.sgml, doc/src/sgml/release-9.3.sgml, doc/src/sgml/release-9.4.sgml, doc/src/sgml/release-9.5.sgml
以下のファイルの9.6.2対応です。
- release-9.2.sgml
- release-9.3.sgml
- release-9.4.sgml
- release-9.5.sgml
すべて9.6.2由来で、こちらで新しく訳したところはありません。
=> update release-9.[2-5] for 9.6.2

doc/src/sgml/logicaldecoding.sgml
Generic Message Callbackの訳についてはおまかせします。
=> Translate about generic message callback in logicaldecoding.sgml

doc/src/sgml/Makefile
原因は不明ですが、osx -x comment によりコメントを残してbuildすると
一部（Appendix L,K)がprevのリンクからとばされてしまう。
とりあえず最初の doc/src/sgml/〜.sgml は不要なので削除するスクリプト
を追加しました。
=> 前へ(prev)がAppendix L,Kとばしてしまう問題の修正

doc/src/sgml/release-9.6.sgml, doc/src/sgml/textsearch.sgml
マージ時の目印である★が残っているのを見つけましたので、対応しました。
release-9.6.sgmlでは単に削除しただけです。
=> remove zenkaku-star

doc/src/sgml/release-old.sgml
ちょっとした修正です。
PL/pgSQLと書くのが正しいようなので。
=> fix 'PL/pgSQL'

doc/src/sgml/acronyms.sgml
頭文字のところで、本文中に対応する日本語訳があるものを（）に書いてみました。
（他にもあるかもしれませんがとりあえず私が気になったものだけ）
=> tiny improvement of acronyms.sgml

doc/src/sgml/config.sgml
重大な誤訳の #961 を修正するついでに #960 も修正しました。
また、これに関連した部分でmustを単に「する」と訳していたのを「しなければならない」に変更しました。
その他、インデントの削除、句点での改行を挿入しています。改行を入れたため、差分がハイライトされていませんが、訳の修正は上記の3箇所だけです。
=> Issues #960 と #961 の修正

doc/src/sgml/advanced.sgml, doc/src/sgml/docguide.sgml
advanced.sgmlとdocguide.sgmlの9.6.4対応です。
http -> https だけでした。
=> update advanced.sgml and docguide.sgml to 9.6.4 (http -> https (part 1))

doc/src/sgml/info.sgml, doc/src/sgml/problems.sgml, doc/src/sgml/release.sgml
以下のファイルの9.6.4対応です。
- info.sgml
- problems.sgml
- release.sgml
こちらも #967 同様、http -> https のみでした。
=> http -> https (part 2)

doc/src/sgml/ref/psql-ref.sgml
原文に変更があった部分の直後の"This is purely a convenience measure"の訳の違和感が強かったので、ついでに修正しました。
=> psql-ref.sgmlの9.6.4対応

doc/src/sgml/dfunc.sgml
dfunc.sgml の9.6.4対応です。
主な作業はpicを大文字にすることでした。
=> capitalize pic

doc/src/sgml/sourcerepo.sgml
sourcerepo.sgml の9.6.4対応です。
恒例のhttp -> https が主です。
=> update sourcerepo.sgml to 9.6.4

doc/src/sgml/release-old.sgml
release-old.sgml の 9.6.4 対応です。
と言っても、（英文に合わせて）リリース日 → リリース日: なだけです。
=> update release-old to 9.6.4

doc/src/sgml/release-7.4.sgml, doc/src/sgml/release-8.0.sgml, doc/src/sgml/release-8.1.sgml, doc/src/sgml/release-8.2.sgml, doc/src/sgml/release-8.3.sgml, doc/src/sgml/release-8.4.sgml
release-7.4.sgml とrelease-8.*.sgml の 9.6.4対応です。
リリース日 → リリース日: だけです。基本的には。
=> update release-7.4 and 8.x for 9.6.4

doc/src/sgml/release-9.0.sgml, doc/src/sgml/release-9.1.sgml
release-9.[01].sgml の 9.6.4 対応です。
ここまでは新しいバージョンが出た訳ではありませんので
リリース日 → リリース日:
だけです。
=> update release-9.[01] for 9.6.4

doc/src/sgml/release-9.2.sgml, doc/src/sgml/release-9.3.sgml, doc/src/sgml/release-9.4.sgml, doc/src/sgml/release-9.5.sgml
以下のファイルの9.6.4対応です。
- release-9.2.sgml
- release-9.3.sgml
- release-9.4.sgml
- release-9.5.sgml
=> update release-9.[2-5].sgml for 9.6.4

doc/src/sgml/release-9.0.sgml, doc/src/sgml/release-9.1.sgml, doc/src/sgml/release-9.2.sgml, doc/src/sgml/release-9.3.sgml, doc/src/sgml/release-9.4.sgml, doc/src/sgml/release-9.5.sgml
release-9.[2-5]の9.6.5対応です。
```
```
以外はrelease-9.6からスクリプトで持ってきました。
あと、どさくさにまぎれてRelease 9.5.8の間違いを直しています。
=> update release-9.[2-5] for 9.6.5

doc/src/sgml/release-7.4.sgml, doc/src/sgml/release-8.1.sgml, doc/src/sgml/release-9.5.sgml, doc/src/sgml/release-9.6.sgml, doc/src/sgml/release-old.sgml
バージョンの書き方でいろいろありましたので、纏めて修正しました。
=> fix typos in 'release version'

doc/src/sgml/release-old.sgml
release-oldに10.0対応の必要はなかったのですが、その確認の過程で誤記をみつけました。
=> fix typo in release-old

doc/src/sgml/release-8.0.sgml, doc/src/sgml/release-8.1.sgml
- release-8.0.sgml
- release-8.1.sgml
前者は9.6の最近の変更を取り込んだだけですが、後者はそれにプラスαがあります。
=> update release-8.[01] for 10.0

doc/src/sgml/release-9.6.sgml
少し気になったので。古いリリースノートに対する修正なので、無視していただいても構いません。
=> Add missing authors of an item in release note 9.6.

doc/src/sgml/release-8.2.sgml, doc/src/sgml/release-8.3.sgml, doc/src/sgml/release-8.4.sgml
- release-8.2.sgml
- release-8.3.sgml
- release-8.4.sgml
9.6の差分の取り込みだけだと思います。
=> update rel8.[2-4] for 10.0

doc/src/sgml/release-9.0.sgml, doc/src/sgml/release-9.1.sgml
- release-9.0.sgml
- release-9.1.sgml
基本的には9.6の差分の取り込みですが、一括置換に失敗したらしいところも直しています。
=> update rel9.[01] for 10.0

doc/src/sgml/ref/pg_ctl-ref.sgml
pg_ctl-ref.sgml で原文が見えてしまう（であろう）ところを見つけました。
=> fix exposed English sentences - 2

doc/src/sgml/func.sgml, doc/src/sgml/func1.sgml
func.sgmlは変更部分が多いので、節ごとに分割してPRを出します。
本PRは9.4（文字列関数）および9.7.3（POSIX正規表現）に関するもので、新規に追加されたregexp_matchに関する記述と、従来からあるregexp_matchesに関する記述の変更です。
=> func.sgmlの9.4節&9.7節の10.0対応

doc/src/sgml/ref/pg_receivewal.sgml, doc/src/sgml/ref/pg_resetwal.sgml, doc/src/sgml/ref/pg_waldump.sgml
xlog->walに名前が変わった3つのファイルです。
大半は、xlog→wal、トランザクションログ→先行書き込みログ、の機械的置換です。
=> pg_receivewal,sgml, pg_reset_wal.sgml, pg_waldump.sgmlの10.0対応

doc/src/sgml/installation.sgml
installation.sgml の10.0対応です。
The ＜envar＞COPT</> and ＜envar＞PROFILE</>云々やorを削除していますが、マージのときに誤って多重に取り込まれたものを削除しただけです。あるべきものは残っているはずです。
=> update installation to 10.0

doc/src/sgml/config.sgml
#1145 絡みでdead tupleをざっと見ていたら、訳が抜けているところを見つけました。
周辺の行頭の空白の削除も合わせてやっているので分かりにくくなっていますが、訳が漏れていたのは
> An aggressive scan differs from ...
で、対応する訳は
> 積極的な走査は、無効タプルを含む可能性のあるページだけではなく、 ...
です。
=> translate an untranslated sentence

doc/src/sgml/typeconv.sgml
"The parser learns from the pg_cast catalog that..."で"learn"を「パー
サはpg_castカタログから...を*学習*します」と訳していますが、単に「知る」
とした方がわかりやすいと思います。「学習」と直訳してしまうと、混乱して
しまいます。
=> typeconv.sgml訳の改善提案です。

doc/src/sgml/stylesheet.css
HTML4版対応だった部分の削除
消えていた強調部分を再度対応
目次等リンクで強調部分が入っていたのを無効化
=> CSSの10.0対応です。

doc/src/sgml/stylesheet-fo.xsl
REL_10_0との差分を後半に集約
ヘッダに章番号を表示
ヘッダ、フッタのカスタマイズ用にコメントを追加
ページマージン削除用設定をコメントとして残す
タイトル表示位置調整
=> PDF用スタイルシートの10.0対応＆整理

doc/src/sgml/datatype.sgml
MAC (Media Access Control) はMAC (メディアアクセスコントロール)と訳されていましたが
頭文字が表記されており理解しやすいため、英文のままとしました。
また、6497行目は少し分かりにくく感じたので、This isの箇所を明示的に訳出しました。
=> datatype.sgmlのPostgreSQL10対応

doc/src/sgml/config.sgml
#1172 の dead tuple 対策で漏れていたのを見つけました。あとinの意味を読み違えているように思います。
ついでに行頭の空白の削除もしています。
=> fix typos in config

doc/src/sgml/acronyms.sgml, doc/src/sgml/bgworker.sgml, doc/src/sgml/config.sgml, doc/src/sgml/release-9.6.sgml, doc/src/sgml/release-old.sgml, doc/src/sgml/sepgsql.sgml
#953 で提案されていたinterfaceの訳語の統一です。
それなりに自信のあるところだけしかやってませんので、全部ではありません。
=> unify translation of 'interface'

doc/src/sgml/ref/pg_ctl-ref.sgml
pg_ctl-ref.sgml の 10.3 対応です。
厳密には10.3 対応は以下の部分だけで、それ以外はおまけです。
ー起動処理を待機している場合、
＋待機している場合
=> update pg_ctl-ref for 10.3

doc/src/sgml/datatype.sgml, doc/src/sgml/func.sgml, doc/src/sgml/func1.sgml, doc/src/sgml/ref/create_trigger.sgml
索引の参照がリンクになっていない所を見つけました。
たとえば
> 論理値
>    演算子 (参照 演算子、論理)
です。原因となっていると思われる所を修正してみました。
（が、それで直っているかどうかは未確認です。）
=> fix see and seealso

doc/src/sgml/release-9.1.sgml
release-9.1.sgmlの10.4対応です。
他のrelease-9.?.sgmlとは異質なようですので、これだけ単独で出します。
=> update 9.1 relnote for 10.4

doc/src/sgml/logical-replication.sgml
replica identityの訳が「レプリカアイデンティ」になっているところがありました。
=> fix typo of replica identity

doc/src/sgml/release-9.3.sgml, doc/src/sgml/release-9.4.sgml, doc/src/sgml/release-9.5.sgml, doc/src/sgml/release-9.6.sgml
以下のファイルの10.4対応です。
- release-9.3.sgml
- release-9.4.sgml
- release-9.5.sgml
- release-9.6.sgml
=> update relnote 9.3-9.6 for 10.4

doc/src/sgml/client-auth.sgml
「ケルベロス」でしょう。（Kerberosのままでも良いかもしれません。）
ケルベルスだとかつてあった（ヘビの？）星座に、、、、
=> fix typo of Kerberos

doc/src/sgml/release-10.sgml, doc/src/sgml/release-9.6.sgml
リリースの番号関連でいくつか間違いを見つけました。
10は間違いとは言えないのですが、他のところでは空白を入れていないのでそちらに合わせています。
9.6は訳し忘れと番号間違いです。
=> fix typos around version number

doc/src/sgml/plpgsql.sgml
plpgsql.sgml の10.5対応です。
Exampleが追加されているように見えますけど、これはマージ時の削除し過ぎを戻しているということだと思います。
=> update plpgsql for 10.5

doc/src/sgml/config.sgml, doc/src/sgml/config0.sgml, doc/src/sgml/config1.sgml, doc/src/sgml/config2.sgml, doc/src/sgml/config3.sgml, doc/src/sgml/split-config.sh
split-config.shを起動することにより、config.sgmlはconfig[0-3].sgmlに分割されます。
また、config.sgmlに分割用のマーカーを追加しました。
split-config.shは分割用のスクリプトです。
=> config.sgmlが大きくなりすぎたので、レビュー用に分割ファイルを作成しました。

doc/src/sgml/standalone-install.xml
standalone-install.xmlの訳です。
ファイルとしては以前のstandalone-install.sgmlに対応するもののようですが、対応する英文はほとんどなかったため、一から訳す形になっています。
=> translate standalone-install for 11.1

doc/src/sgml/func.sgml, doc/src/sgml/func1.sgml, doc/src/sgml/func2.sgml, doc/src/sgml/func3.sgml, doc/src/sgml/func4.sgml
レビューは、func[1-4].sgmlで行ってください。
27,531行からの文は原文に文法的な誤りがあったため、本家に報告、修正を
PostgreSQL 11の安定ブランチにコミットしています。訳は修正後の原文に基
づいています。詳細はコミット "Doc: fix typo in "Generic File Access
Functions" section." (84fcc2ce56962a82e4da633b5ba2bd68c4960cd8) を参照。
=> func.sgmlのPostgreSQL 11対応です。

doc/src/sgml/catalogs.sgml
most_common_elem_freqs列の訳が分かりづらかったため他の列の説明文に合わせて修正しました。
=> pg_statsのmost_common_elem_freqs列の説明を修正

doc/src/sgml/catalogs.sgml
これから凍結されるのではなく、既に凍結されているという点が重要なので、
原文の現在完了時制を尊重しました。
=> pg_class.relfrozenxid に関して、以前からの訳文について修正です。

doc/src/sgml/pgstattuple.sgml
pgstatindex についての説明のところで、「pgstattuple では」となって
いることに違和感
英語では "As with" とあるので「〜同様」となるべきかと思います。
=> pgstattuple 内 pgstatindex に関する説明の微修正

doc/src/sgml/release-9.3.sgml, doc/src/sgml/release-9.4.sgml, doc/src/sgml/release-9.5.sgml, doc/src/sgml/release-9.6.sgml
9.3.25、9.4.20、9.5.15.、9.6.11 リリース ノートの翻訳です。
大部分は 10.6 リリースノート（pr1360）と同じです。
=> Translate release note 9.3.25 to 9.6.11

doc/src/sgml/stylesheet-speedup-xhtml.xsl
xsl:template name="href.target" で時間がかかっていた箇所を回避
=> html作成の速度改善 #1463

doc/src/sgml/btree.sgml
btreeの意味の間違いが11.3で修正されたところ以外は変わっていません。
=> btree.sgmlのPostgreSQL 11.3対応です。

doc/src/sgml/installation.sgml
installation.sgmlの11.3対応です。
コンフリクト解消のときに日本語訳が消されてしまっているものがあるようですが、その部分の復旧も含んでいます。
=> update installation for 11.3

doc/src/sgml/perform.sgml
perform.sgmlでコメントタグを忘れている部分を見つけましたので、その対応です。
=> uncommented English in perform

doc/src/sgml/runtime.sgml
runtime.sgml で原文のコメント化に失敗しているところを見つけました。
=> comment-out failure in runtime

doc/src/sgml/ddl.sgml
ddl.sgmlの11.3対応です。
修正箇所の3分の2は、翻訳文が落ちていたのを戻したものとなります。
=> update ddl for 11.3

doc/src/sgml/pgtrgm.sgml
似ている文が追加されたため、マージのときにズレてマージされていたのを修正しています。
実際に追加したのは「厳密な」と「デフォルト値」を修正したものを追加しただけです。
=> pgtrgm.sgmlの11.4対応です。

doc/src/sgml/bloom.sgml
Authorsの訳がbloomだけ「著者」になっていましたので、周りに合わせました。
=> fix 'authors'

doc/src/sgml/func.sgml, doc/src/sgml/func2.sgml, doc/src/sgml/lobj.sgml, doc/src/sgml/release-11.sgml, doc/src/sgml/spi.sgml
func.sgml: 元々コメント化されていてversion 11で削除されたが、マージ時に
コメント化の方を消してしまっていたのを修正
lobj.sgml: 不要行の削除
release-11.sgml: 原文のインデントが変更されていたのを戻した
spi.sgml: ここだけ間違って日本語訳の方をコメントアウトしていたのを修正
=> REL_11_5との差分チェックによりみつかった問題修正

doc/src/sgml/func.sgml
以前は、round関数の説明として「四捨五入」と記載されていました。
しかし、double precision型の少数を引数にround関数を実行すると、
四捨五入の動きにはなりません。例えば、round(0.5::double precision)の
結果は0です。このため、「四捨五入」との記述は正確ではないようです。
この修正では、英語での記述「round to nearest integer」の日本語訳である
「最も近い整数への丸め」を訳として採用します。下記のWikipediaの
記事によると、四捨五入も偶数への丸め(引数の型がdouble precisionの場合の
round関数の動き)も、広義の最近接丸めとのことで、
「最も近い整数への丸め」との訳は間違いではないようです。
https://ja.wikipedia.org/wiki/端数処理
=> round関数の説明の日本語訳を修正します。

doc/src/sgml/isn.sgml, doc/src/sgml/plpgsql.sgml, doc/src/sgml/ref/create_table.sgml, doc/src/sgml/ref/initdb.sgml, doc/src/sgml/ref/pg_dump.sgml, doc/src/sgml/ref/pg_recvlogical.sgml, doc/src/sgml/ref/pgbench.sgml, doc/src/sgml/regress.sgml, doc/src/sgml/spi.sgml, doc/src/sgml/uuid-ossp.sgml
2つのハイフン(--)がコメント化されるときに&#045;に置き換えられるため、
差分チェック時に除外されている。
そのため、原文の変更による差分が見逃されれていたので、 &#045;を-に再置換えして
差分が無くなるように修正した。
=> ハイフンの置き換えで見逃されていた差分を再チェック

doc/src/sgml/func.sgml, doc/src/sgml/func0.sgml, doc/src/sgml/func1.sgml, doc/src/sgml/func2.sgml, doc/src/sgml/func3.sgml, doc/src/sgml/func4.sgml
例によってレビューはfunc[0-4].sgmlに行ってください。
「欲張り」→「貪欲」への置き換えはこのコミットではまだ行っていません。
=> func.sgmlのPostgreSQL 12.0対応です。

doc/src/sgml/func.sgml
このため次の行に表示されていました。
https://pgsql-jp.github.io/current/html/functions-formatting.html#FUNCTIONS-FORMATTING-DATETIME-TABLE
=> テーブルの一つ余分な/row,rowを削除

doc/src/sgml/func.sgml, doc/src/sgml/func4.sgml, doc/src/sgml/indices.sgml
除外制約→排他制約
インデクス→インデックス
です。どちらも前者は1つだけしかなくて、それ以外のところでは後者でした。
=> fix 'alone' word

doc/src/sgml/textsearch.sgml
textsearch.sgml の12対応です。
Included columns と Included attributes の訳は全く自信がありません。
=> update textsearch for 12

doc/src/sgml/libpq.sgml
libpq.sgmlの12対応です。
PGGSSENCMODEの原文を削除してしまっているように見えますが、その直後の差分に全く同じものがありますので、マージ時の手違いだと思います。
あと、訳していて
if there are GSSAPI credentials present (i.e. in a credentials cache),
という部分が、i.e.ではなくe.g.と書きたかったのではないかという気がするのです（「認証情報が(たとえば認証情報キャッシュに)存在」の方が流れとしてきれいなような、、、）が、そこまで自信がないので、本家への報告とかはしていません。
=> update libpq for 12

doc/src/sgml/libpq.sgml
libpq で気になる部分をいくつか見つけましたので、その修正案です。
パラメーター → パラメータ も同時にやっています。
（パラメーターと伸ばしているのはlibpqしかないようです。）
=> fix typos in libpq

doc/src/sgml/logicaldecoding.sgml
前からの漏れですが、一部マージ時に消えてしまっていた箇所がありました。
=> logicaldecoding.sgml の12.0対応修正漏れ

doc/src/sgml/monitoring.sgml
=> 原文が消えていたのを復帰

doc/src/sgml/ref/create_role.sgml
ref/create_role.sgml の12.3対応です。
原文ではコメントが増えただけですので、その旨追記しました。
=> update create_role for 12.3

doc/src/sgml/config.sgml, doc/src/sgml/config1.sgml
=> fix translation of "cluster"

doc/src/sgml/monitoring.sgml
pg_stat_activityの説明を改善してみました。
原文 (https://www.postgresql.org/docs/12/monitoring-stats.html)
　One row per server process, 
修正前
　サーバ当たり１行の形式で、
修正後
　サーバプロセスあたり１行の形式で、
=> monitoring.sgml内の表27.1 動的統計情報ビューの改善です

doc/src/sgml/hstore.sgml, doc/src/sgml/ltree.sgml
- hstore.sgml
- ltree.sgml
追加されたのがほぼ同じ文章でしたので、一緒にやりました。
=> update hstore and ltree for 12.4

doc/src/sgml/pgstatstatements.sgml
翻訳のご対応ありがとうございます。
pg_stat_statementsのドキュメントを確認時に誤記と思われる記述を見つけましたので、ご報告いたします。
=> pg_stat_statementsの説明文の文言修正・統一

doc/src/sgml/wal.sgml
辞書を引くと、industry standard → 業界標準、industrial standard → 工業規格となっているようです。
=> 翻訳の改善、誤訳の修正

.github/workflows/pr-label.yml
fix #1397
メンテナンス性を考えて github-script にしました。
=> pull requestに対して自動でラベルを付ける

.github/workflows/pr-label.yml
ラベルが無い状態の判定がうまく出来なかったので、厳密な方法に変更しました。
=> ラベルの判定方法を修正した

doc/src/sgml/indices.sgml
ほとんどはマージに失敗した箇所の復活で、新しく翻訳したところは最後のtipです。
=> indices.sgml の13.1対応です。

doc/src/sgml/xindex.sgml
xindex.sgmlの13.1対応です。
13での目玉機能の1つだと思いますが、ここでは「B-tree重複排除最適化」と訳してしまいました。
決まった訳があれば指摘いただきたく。
=> update xindex for 13.1

doc/src/sgml/ref/execute.sgml
ref/execute.sgml の13.1対応です。
＃すみません、色々やらないといけないことはあるはずなんですが現実逃避です。
=> update execute for 13.1

doc/src/sgml/parallel.sgml
「シングルユーザ」の訳が、一ヶ所だけ「シングルユーザー」となっていたのに気づいたので。
=> fix translation of "single user"

doc/src/sgml/ref/vacuumdb.sgml
新規追加の並列バキュームの訳追加と、過去のバージョンで訳していない箇所も一応訳を追加しました(削除は簡単なので)。
=> update ref/vacuumdb.sgml for 13.1

doc/src/sgml/isn.sgml
更新された部分以外に以下の変更をしました。
「弱め」→「weak」
「検査桁」→「チェックディジット」
weakは「isn_weak」のために使用していて「弱め」と表現する例が他に無さそうなので、
そのままweakに変更しました。
「チェックディジット」は既に広く使われている様なので変更しました。
=> isn.sgmlの13.1対応です。

doc/src/sgml/ref/explain.sgml, doc/src/sgml/ref/pg_checksums.sgml
- ref/explain.sgml
- ref/pg_checksums.sgml
=> update explain and pg_checksums for 13.1

doc/src/sgml/postgres-fdw.sgml
postgres-fdw.sgml の 13.1 対応です。
最後の一文（They can also use any trust...）の意味がよく分かっていません。
=> update postgres-fwd for 13.1

doc/src/sgml/catalogs.sgml, doc/src/sgml/split-catalogs.sh
=> catalogs.sgmlを5分割するマーカーをコメントで入れました。

doc/src/sgml/backup.sgml, doc/src/sgml/bki.sgml, doc/src/sgml/charset.sgml, doc/src/sgml/config.sgml
para内でコメント化と翻訳の形式が一部違っているために未翻訳のチェック
を掛けると引っかかってしまうので、形式を修正しました。
para内で
```
＜para＞
＜！ーー原文のコメント化ーー＞
翻訳
＜／para＞
```
の形式になっていると、抽出と未翻訳のチェックが簡単になります。
=> para内のコメント-翻訳の形式を修正

doc/src/sgml/acronyms.sgml, doc/src/sgml/advanced.sgml, doc/src/sgml/charset.sgml, doc/src/sgml/docguide.sgml, doc/src/sgml/info.sgml, doc/src/sgml/plperl.sgml, doc/src/sgml/textsearch.sgml
現在変換とチェックをするツールを作成中の関係で、日本語訳中の英語表記が原文に含まれているかをチェックしてます。
そのためURLが完全に一致するように修正しました。
=> 変更漏れがあった日本語側のURLを修正

doc/src/sgml/adminpack.sgml, doc/src/sgml/config.sgml, doc/src/sgml/config3.sgml, doc/src/sgml/ddl.sgml, doc/src/sgml/logical-replication.sgml, doc/src/sgml/pltcl.sgml
"superuser"の訳を多数派の「スーパーユーザ」に揃えました。
=> fix "superuser"

doc/src/sgml/pgbuffercache.sgml
元々、表に 「列」と「型」があったのをスペースで区切って一行に入るようにしたので、スペース区切りにしました。
表なので、「します」を取って統一しました。
https://pgsql-jp.github.io/current/html/pgbuffercache.html
=> pgbuffercache.sgml の表を他にあわせて修正

doc/src/sgml/config.sgml, doc/src/sgml/config1.sgml, doc/src/sgml/config2.sgml
log_line_prefixの表です。
なお、config1.sgmlの差分は、今回の修正とは無関係で、前回config.sgmlの修正が反映されていなかったようです。
=> config.sgmlの未翻訳箇所を見つけました。

doc/src/sgml/monitoring.sgml
monitoring.sgml の 13.1 対応です。
既存の訳を再利用できた部分も多かったのですが、そのためには結局全体を見ないといけないことになって、その時気になった統一感のなさにも同時に対応してます。 #1955 や #1957 もこの作業からの派生です。
=> update monitoring for 13.1

doc/src/sgml/libpq.sgml, doc/src/sgml/split-libpq.sh
libpq.sgmlがGithubの制限を超えたようなので、config.sgmlなどと同様にファイル分割します。
分割コマンドはsplit-libpq.shです。
=> libpq.sgmlを4分割にします。

doc/src/sgml/split-catalogs.sh, doc/src/sgml/split-libpq.sh
翻訳には影響しないのですが、ファイル分割スクリプトのコメントに間違いを見つけたので。
=> fix comments in split shells

doc/src/sgml/glossary.sgml
"epoch"はうまい訳語が思いつかず、原文のママにしてあります。
=> glossary.sgmlのPostgreSQL 13.1対応です。(Transaction ID)

doc/src/sgml/glossary.sgml
glossary の grant を訳しました。
あと、＜glossterm＞で訳すべきところもついでに訳しています。（grantは訳すべきではないと考えています。）
=> translate grant in glossary

doc/src/sgml/glossary.sgml
Atomic, Atomicity, Autovacuumを訳しました。(Aの項完了）
=> glossary.sgmlのPostgreSQL 13.1対応です。

doc/src/sgml/glossary.sgml
"MVCC"が抜けていたのを修正しました。
「必須とは言えない」と仰ってくださったのですが、やはり気になるので。
=> 斉藤さんの指摘に対応しました。

doc/src/sgml/glossary.sgml
日本語訳がついているところは「英語【日本語】」にするのを試しにやってみました。  #2021
=> glossaryの見出しの形式を英語【日本語】（補足）に変更

doc/src/sgml/glossary.sgml
「 This is one of the <acronym>ACID</acronym> properties.」は同じ文言なので統一。
ACIDのIsolationの場合は「独立性」に変更。
末尾の「。」の抜け修正。
「.」が残っていたミスの修正。
=> ACIDの文言の統一（調整）

doc/src/sgml/merge-config.sh
以下のワークフローを想定しています。これにより、config[0-3].sgmlのレ
ビューによる修正箇所をconfig.sgmlから探す手間が省け、作業効率が上がり
ます。
1. config.sgmlを変更 (従来手順)
2. split-config.shでconfig.sgmlをconfig[0-3].sgmlに分割 (従来手順)
3. config.sgml config[0-3].sgmlをcommit/push (従来手順)
4. config[0-3].sgmlのレビュー結果を受けてconfig[0-3].sgmlを修正 (新手順)
5. cat config[0-3].sgml > config.sgml (新手順)
6. patch -p0 config.sgml < config-merge.patch (新手順)
7. config.sgml config[0-3].sgmlをcommit/push (従来手順)
=> config[0-3].sgmlからconfig.sgmlを生成するパッチです。

doc/src/sgml/ref/postgres-ref.sgml
ref/postgres-ref.sgmlの14.0対応です。
ちょっと差分があるな、と思って取り掛かったのですが、ほとんどが削除でした、、、、orz
が、熟成させる意味はないのでとりあえずPR。
=> update ref/postgres-ref for 14.0

doc/src/sgml/ref/alter_foreign_table.sgml
ref/alter_foreign_table.sgml の14.0対応です。
基本的にはxref -> linkの変更なのですが、トリガーとかスーパーユーザーに気づいてしまったので、合わせてそちらも直しています。
=> update ref/alter_foreign_table for 14.0

doc/src/sgml/test-decoding.sgml, doc/src/sgml/textsearch.sgml
- test-decoding.sgml
- textsearch.sgml
=> update test-decoding and textsearch for 14.0

doc/src/sgml/high-availability.sgml
翻訳ありがとうございます。いつもお世話になっております。
ドキュメントで修正した方が良いと思われる個所を見つけましたのでご報告いたします。
・「クエリが中断される受け入れがたいほど多い」という表現の修正
・「クエリ」は他に合わせて「問い合わせ」に変更
・「解決」は「改善」の方が適切かと思われるので変更
=> high-availability.sgmlの翻訳文の修正

doc/src/sgml/high-availability.sgml
・「クエリが中断される受け入れがたいほど多い」という表現の修正
・「クエリ」は他に合わせて「問い合わせ」に変更
・「解決」は「改善」の方が適切かと思われるので変更
=> high-availability.sgmlの翻訳文の修正（#2096の13へのバックポート）

doc/src/sgml/catalogs.sgml, doc/src/sgml/catalogs0.sgml, doc/src/sgml/catalogs1.sgml, doc/src/sgml/catalogs2.sgml, doc/src/sgml/catalogs3.sgml, doc/src/sgml/catalogs4.sgml, doc/src/sgml/pgbuffercache.sgml, doc/src/sgml/pgstatstatements.sgml
元々「参照」列だったのが（）で表記されるように変更されました。
そのため未対応でした。
pgstatstatements.sgml は全体をあわせるために変更しました。
=> 「references」を「〜を参照」に変更

doc/src/sgml/wal.sgml
翻訳のご対応ありがとうございます。
いつも大変お世話になっております。
「リスタートポイント」と「再開始点」が統一されておらず、ブラウザ上での検索が出来ず、少し困りましたので、本PRを作成致しました。どちらに統一するか迷いましたが、本PRでは「チェックポイント」と同様にカタカナ表記で統一しています。
具体的に困った点は、CHECKPOINT(1)の記載から、「リスタートポイント」についてのリンクに飛ぶと、そのページ(2)では、「再開始点」との記載になっており、ブラウザ上での検索でヒットせず、リンクが張られているのに詳細が記載されていないと誤解してしまいました。
(1) https://www.postgresql.jp/document/13/html/sql-checkpoint.html
(2) https://www.postgresql.jp/document/13/html/wal-configuration.html
不足点などありましたら、ご指摘頂ければと思います。
=> 再開始点をリスタートポイントに統一（wal.sgml翻訳文の修正)

doc/src/sgml/textsearch.sgml
Issue #2184 の対応
『全文検索のためにインデックスが必須だと言うわけではないことを言っておかなければなりませんが』を『全文検索でインデックスが必須ではありませんが』に修正しました。
=> Issue #2184 の対応

doc/src/sgml/indexam.sgml
#2213 で取り上げたものの一部です。
- ここだけ「不可逆」となっている（他のところでは「非可逆」）
- #2206 と同じ"lossy representation(s)"の訳
ということで、これだけ先走って対処します。
（原文がlossyとrepresentationの間に改行が入っており、単純に検索すると見落としそう、というのもあります。）
=> fix translation of "lossy"

doc/src/sgml/information_schema.sgml
指摘された #2210 の修正です。
If <literal>data_type</literal> identifies 〜を「〜識別された場合」
に統一しました。
viewの「識別します」を「示します」に変更しました。
=> identifiesの修正

doc/src/sgml/indexam.sgml
include columnなどをどう訳すか悩んだのですが、「include列」としました。
"include"のうまい日本語訳があればよいのですが、思いつきませんでした。
=> indexam.sgmlのPostgreSQL 14.0対応です。

doc/src/sgml/plpgsql.sgml
plpgsql.sgml の14.0対応です。
volatilityですが、「変動性」となっていたものを「揮発性」にしました。
「変動性」も悪くないのですが、他のところでは「揮発性」となっていたためです。
=> update plpgsql for 14.0

doc/src/sgml/query.sgml
ファイル名が原文と違うところを見つけました。
おそらく追従漏れでしょうね。
=> fix typo in query of 14.0

doc/src/sgml/ddl.sgml
日本語訳の方がコメントアウトされていましたので修正しました。
=> fix typo in ddl of 14.0

doc/src/sgml/config.sgml, doc/src/sgml/config1.sgml
config.sgmlで原文と日本語のコメントアウトが逆、あと訳がされていないところを見つけました。
=> fix typo in config of 14.0

doc/src/sgml/datatype.sgml, doc/src/sgml/func.sgml, doc/src/sgml/func4.sgml, doc/src/sgml/high-availability.sgml, doc/src/sgml/xfunc.sgml
=> fix typos in term index for 14.0

doc/src/sgml/installation.sgml
All of PostgreSQL successfull...の表記は無くなっているので削除。
configureは原文にないため(configure以外でも指定可能なため)削除。
ダイアローグをダイアログに修正。
原文の並びに合わせても違和感なかったため修正。
=> 最新の記述に訳も合わせた

doc/src/sgml/fdwhandler.sgml
3点の対応です。
・翻訳もれの対応
・改行位置の修正
・「クエリ」を「問い合わせ」に変更
=> fdwhandlerの残りの指摘箇所を対応

doc/src/sgml/fdwhandler.sgml
=> fix typos in fdwhandler of 14.0

doc/src/sgml/syntax.sgml
syntaxを見ていて気になったところがあったので、手を入れています。
基本的には改行の追加や修正ですが、「とします。」の削除もしています。
次のようにします。
SQLの例
とします。
は、これ単体ならそれほど悪くはないのですが、そのすぐ上では
次のようにします。
SQLの例
（次の文）
となってますので、揃えてみました。
=> cosmetics!

doc/src/sgml/config.sgml, doc/src/sgml/pgtrgm.sgml
英語の索引でまだコメントアウトされているところがいくつかありましたので、コメントアウトを解除しました。
（＜primary＞＜varname＞となっていると対象外と判断してしまっている、ということかな、と思いました）
あと、それ以外にも変なところを直しています。（「設定ファイルにおける」は変ではなかったのですが、周辺と調子を合わせました。）
で、シェルスクリプトで分割すればいいのですが、手元にはBSD系のものしかなくてBSD系だとシェルスクリプトが動かないので（多分sedがGNU sed依存）分割ファイルはコミットしてないです。誰かお願い。（やってやれなくはないはずですが、酒が入った状態でやると事故に繋がりそうなので、、、、）
=> fix typos in index for 14.0

doc/src/sgml/ref/set_transaction.sgml
索引を眺めていて気づいたので。
読み取りのみ -> 読み取り専用
単独であれば「読み取りのみ」が悪いとは思わないのですが、「読み取りのみ（の）トランザクション」としているのがこのファイルだけのようでしたので、「読み取り専用」に揃えました。indexterm内だけのつもりでしたが、地の文でもそうなっていたので、地の文の方も修正しています。
=> fix translation of 'read-only'

doc/src/sgml/config.sgml, doc/src/sgml/config0.sgml, doc/src/sgml/config1.sgml, doc/src/sgml/config2.sgml, doc/src/sgml/config3.sgml
config.sgmlだけインデントが独特でチェックと自動置き換えの
障害になっていたため修正しました。
また、行内コメントも差分チェックに引っかかるため変更しました。
一部indextermの修正も含みます。
=> config.sgmlのインデント修正

doc/src/sgml/array.sgml, doc/src/sgml/datatype.sgml, doc/src/sgml/gin.sgml, doc/src/sgml/gist.sgml, doc/src/sgml/indices.sgml, doc/src/sgml/plperl.sgml, doc/src/sgml/queries.sgml, doc/src/sgml/ref/declare.sgml, doc/src/sgml/ref/fetch.sgml, doc/src/sgml/ref/move.sgml, doc/src/sgml/rules.sgml, doc/src/sgml/xfunc.sgml
secondaryやsee等が英語の方に必要だったのを誤って日本語側のみにしてしまったミスの修正。
indextermの差分がちゃんとブロックになるように修正。
indextermの差分は
```
<indexterm>
+</indexterm>
+<indexterm>
<indexterm>
```
ではなく
```
<indexterm>
</indexterm>
+<indexterm>
+<indexterm>
```
になるようにするとミスが判明しやすくなるためインデントも含めて修正しました。
=> indextermのミス修正

doc/src/sgml/legal.sgml, doc/src/sgml/xindex.sgml
14.5でコメントのタグが閉じていないことに気づきました。
訳の時に合わせてやればいいのですがその時には忘れてそうなので。
=> fix missing comment tags

doc/src/sgml/stylesheet-custom.xsl
#2298 がマージされたので、
https://github.com/pgsql-jp/jpug-doc/issues/ へのリンクを変更しました。
単なるリンクなので、
```
make ORIGINAL=1 html
```
でできたhtmlをブラウザで見て、リンクをクリックすれば確認できます。
=> issueへのリンクを変更

doc/src/sgml/ecpg.sgml
ecpg.sgml の14.5対応です。
が、初めの方は気がついてしまったのでついでに行頭の空白を削除しただけで、ラスボスは2631行以降です。
=> update ecpg for 14.5

doc/src/sgml/pgprewarm.sgml
=> update pgprewarm for 14.5

doc/src/sgml/ref/create_index.sgml
ref/create_index.sgml の14.5対応です。
最後の部分は新規訳ではなく、既存の訳の（一部）復活です。
=> update create_index for 14.5

doc/src/sgml/xindex.sgml
=> xindex.sgmlの14.5対応です。

doc/src/sgml/ref/insert.sgml
ref/insert.sgml の 14.5 対応です。
後半の２つの文は既存の訳の復活です。
=> update insert for 14.5

doc/src/sgml/plpgsql.sgml
余分な改行が含まれてしまうので、CDATAの終わり部分を元に戻す。
追加で以下を修正。
* typo
* タグ不足
=> plpgsql.sgmlを再修正

doc/src/sgml/config.sgml, doc/src/sgml/config0.sgml, doc/src/sgml/config1.sgml, doc/src/sgml/config2.sgml, doc/src/sgml/config3.sgml
以下の修正が含まれます。
原文が同じ文の箇所を同じ訳に統一。
コメント内ハイフンの表記変更。
indextermのコメントになっていた漏れを修正。
タグチェックによる修正。
=> config.sgmlの変更漏れを修正

doc/src/sgml/spi.sgml
コメントの開始位置がミスっていたのを修正。
同じ文言の統一。
ハイフンの修正。
=> spi.sgmlのコメント位置ミスを修正

doc/src/sgml/charset.sgml
訳の方に＆＃045;が入っているのを見つけました。
実害はないと思いますけど、気になったので。
=> remove &#045;

doc/src/sgml/ref/update.sgml
ref/update.sgml の15.0対応です。
変更量がそれなりにありましたが、salesman -> salesperson絡みのものがほとんどです。なので、この差分では訳を大きく変えているように見えますが、実は14.5をちょっと改変して持ってきているだけです。
あと、日本語はセールスマンで変えてませんけど、皆さん、気にしますか。
=> update 'update' for 15.0

doc/src/sgml/catalogs.sgml, doc/src/sgml/catalogs3.sgml, doc/src/sgml/catalogs4.sgml, doc/src/sgml/merge-catalogs.sh, doc/src/sgml/split-catalogs.sh
- マージミスで、catalogs.sgmlの"split-catalogs3"マークが消えていたのを復活
- view関係がcatalogs.sgmlからsystem-views.sgmlに移動したことにより、分割ファイルのcatalogs4.sgmlが不要になったので削除
- catalogs4.sgmlが削除されたのでそれに合わせてsplit-catalogs.sgmlを調整
- PostgreSQL 15.0の変更に合わせてmerge-catalogs.shを調整
=> catalogs.sgmlをPostgreSQL 15.0対応するための準備です。

doc/src/sgml/catalogs.sgml, doc/src/sgml/catalogs0.sgml, doc/src/sgml/catalogs1.sgml, doc/src/sgml/catalogs2.sgml, doc/src/sgml/catalogs3.sgml, doc/src/sgml/merge-catalogs.sh
斉藤さんに刺激を受けて:-)私も分割修正を試みています。
このPRではcatalogs0.sgmlの部分のみを対応しました。
今後、catalogs[1-3].sgmlについても別PRで対応していきます。
また、pull request 2441のmerge-catalogs.shのミスを修正
catalogs[1-3]は本文内容の変更はありませんが、分割処理で追加されたコメントにcatalogs4.sgml についても言及されているのが間違いだったので修正しています。
=> catalogs.sgmlのPostgreSQL1 15.0対応です(パート1)

doc/src/sgml/monitoring.sgml
レビューしやすい単位でPRを分割して送る実験です。
monioring.sgmlの対応を全部終わらせてから送ろうとすると時間がかかり、レビューもまた時間がかかります。
分割することで、できそうなところから先行し、スキマ時間でもレビューできる単位にする試みです。
=> monitoring.sgmの15.0対応の第1弾です

doc/src/sgml/glossary.sgml
free space mapの訳を揃えました。
「フリースペースマップ」と「空き領域マップ」があったのですが、「空き領域マップ」が多数派でしたので、「空き領域マップ」に。
今回の修正は glossary.sgml のみですが、#2442 で一つ「空き領域マップ」にしています。これで「フリースペースマップ」はなくなったはず。
=> fix 'free space map'

doc/src/sgml/ddl.sgml
https://github.com/pgsql-jp/jpug-doc/pull/2465
で話題になった件です。
忘れないうちにPRを出しておきます。
=> ブーリアン値を論理値に変更

doc/src/sgml/acronyms.sgml
リンク先の変更のみで、訳の部分は変えていません。
変える必要がないので。
=> acronyms.sgmlのPostgreSQL 15.0対応です。

doc/src/sgml/ref/pg_recvlogical.sgml
ref/pg_recvlogical.sgmlの15.0対応です。
prepared transactionは「プリペアドトランザクション」としましたが、最初に機械翻訳が提示してきた「準備されたトランザクション」の方が良かったでしょうか。
=> update pg_recvlogical for 15.0

doc/src/sgml/catalogs.sgml, doc/src/sgml/catalogs1.sgml
"part2"を誤ってcatalogs2.sgmlの訳に使ってしまったので「catalogs1.sgml部分」としています。
=> catalogs.sgmlのPostgreSQL 15.0対応です(catalogs1.sgml部分)

doc/src/sgml/client-auth.sgml
前から気になっていたsearch/bindをsearch+bindに変更したものです。
LDAPに詳しくないのですが、変更して良いでしょうか？
さらにtypo修正
=> client-auth.sgmlのPR2480にsearch+bindの変更を追加

doc/src/sgml/func.sgml
tieは端数ではなく同値という意味なので、同値と訳していいかと思います。
「小数点以下を切り上げて端数を処理します。」の説明を読んで、例えば
SELECT round(CAST(42.5 AS numeric));
は42を返すのかと思いましたが、実際は43が返ってきます。
英文のいわんとするところは、0.5や1.5のように、最も近いintegerが2つ存在する場合…同値(tie)が存在する場合の処理について、numericの場合は切り上げて処理される、とのことなのかと思います。
これを日本語に訳す場合、自分はいい言葉が思いつきませんでしたが、端数ですと意味が違ってしまうので、同値がいいかと思いました。
=> round関数の訳を修正

doc/src/sgml/stylesheet-custom.xsl, doc/src/sgml/stylesheet.css
他バージョンの文書のリンクを追加してみました。
https://noborus.github.io/test/index.html
のように右上に表示します。公式サイトを模してボタンのようにしていますが、単なるリンクです。
#2467 の対応です。
=> 他バージョンの文書として公式サイトへのリンク

doc/src/sgml/legal.sgml
legal.sgmlの見直し。
翻訳の著作権についてがそのままになっていたので修正。#363
日本語訳がそのまま続くと見づらかったので、別に分けた。
PostgreSQL Global Development Groupを日本語表記から元のままに修正。
=> 翻訳の著作権表記について見直し

doc/src/sgml/backup.sgml
1453-1454行あたりで、原文の間違いでarchive_commandが繰り返されているのは訳からは削除しています。 なお、原文の間違いについては修正パッチを本家に投稿済みです。
=> backup.sgmlのPostgreSQL 15.0対応です。

doc/src/sgml/trigger.sgml
trigger.sgmlの15.0対応です。
新規で対応すべきところは《機械翻訳》で始まる2段落だけだったのですが、参考に確認したところで「トリガー」を見つけ、さらに「文/行単位」と「文/行レベル」の原文との不一致を見つけてしまったので、そちらも合わせて対応しています。
（「文/行単位」と「文/行レベル」は原文でも「どちらの言い方もあるよ」とは言っているので、そこまでこだわらなくてもいいのかもしれませんが、（気づいた範囲で）より原文に忠実にしています。）
=> update trigger for 15.0

doc/src/sgml/func.sgml
`pg_event_trigger_ddl_commands()`関数と`pg_event_trigger_dropped_objects()`関数の`objsubid`列の説明だけ翻訳が抜けていたので翻訳してみました。
=> イベントトリガ関数のSub-object IDを翻訳

doc/src/sgml/pgcrypto.sgml
pgcrypto.sgml の15.0対応です。
差分の量が多いように見えたのですが、ほとんどがOpenSSLを必須にしたことによる削除でした。
=> update pgcrypto for 15.0

doc/src/sgml/earthdistance.sgml
earthdistance.sgml の15.0対応です。
reasonablyの訳もドサクサに紛れて変えています。
=> update earthdistance for 15.0

doc/src/sgml/rules.sgml
rules.sgml で原文に追従できていなかった部分を見つけました。
具体的にはrelationに対して「テーブル」と訳している部分がありました。おそらくviewはテーブルに限らずリレーションに対して作れるよということで、原文が変わったのだと思いますが、それに追従できていませんでした。15で変更されたものではないので、今回の翻訳でも更新の対象にならなかったのだろうと思います。
=> fix oversight in rule.sgml

doc/src/sgml/plpython.sgml
plpython.sgmlの15.0対応です。
差分が大きいように見えたのですが、ほとんどがバージョン2系統のサポートをやめたことによる削除ですね。
=> update plpython for 15.0

doc/src/sgml/syntax.sgml
・冗長表現の見直し（例：使用することができます⇒使用できます）
・助詞の繰り返しの見直し
・漢字の開きの見直し（例：下さい⇒ください）
・数字を半角に統一した
・（）を全角に統一した
上記修正と合わせて、文章を見直した箇所もあります。
意味を変えずに読みやすさの向上を意図しました。
=> 第4章の文章表現を見直しました。

doc/src/sgml/dml.sgml
・助詞の見直し（例：完全な行ではないものを⇒完全な行でないものを）
・冗長表現の見直し（例：することができます⇒できます）
　　ただし、原文のニュアンスを踏まえて、修正していない箇所もあります。
・数字を半角に統一した
・column names を「列名」と訳した
　　他の章の訳を参考にしました。
=> 第6章の文章表現を見直しました。

doc/src/sgml/typeconv.sgml
・漢字の開きの見直し（例：して下さい⇒してください）
・（）を全角に統一した
・句点を「。」に統一した
・助詞の見直し（例：行わないようすべきです⇒行わないようにすべきです）
・冗長表現の見直し（例：検証することができます⇒検証できます）
　　ただし、原文のニュアンスを踏まえて、修正していない箇所もあります。
・送り仮名の修正（例：行なうには⇒行うには）
=> 第10章の文章表現を見直しました。

doc/src/sgml/installation.sgml
・漢字の開きの見直し（例：元々⇒もともと）
・冗長表現の見直し（例：することができます⇒できます）
・送り仮名の見直し（例：組合せ⇒組み合わせ）
・表記の見直し（例：充分⇒十分）
・必要性⇒必要
・稼動⇒稼働
・助詞の繰り返しの見直し
・（）を全角に統一した
・数字を半角に統一した
・：を全角に統一した
=> 第17章の文章表現を見直しました。

doc/src/sgml/ref/set_transaction.sgml
ref/set_transaction.sgmlの15.3対応です。
基本的にはMERGEの追加なのですが、
> これは読み取り専用の高レベルの概念であり、ディスクへの書き込みをすべて防ぐわけではありません。
は機械翻訳のほうが自然な気がしたので、機械翻訳に近づける形で変更しました。が、内容をよく分かっているわけではないので、前のほうが正確だとかありましたらお知らせください。
=> update set_transaction for 15.3

doc/src/sgml/release-15.sgml
"123 abc" という記載がありますが、正しくは "123abc" でしたので、修正しました。
=> #2681 の対応です。

doc/src/sgml/func.sgml, doc/src/sgml/func2.sgml, doc/src/sgml/func3.sgml, doc/src/sgml/func4.sgml
Result:が結果としているところとそのままのとろころがあったので、
Resultに統一しました。
=> func.sgmlの15.3対応です

doc/src/sgml/pgstatstatements.sgml
PostgreSQL 15.4固有の修正ではなく、以前からあった、ASCII "()"を、全角に置き換える修正です。
=> pgstatstatements.sgmlでの括弧の修正です。

doc/src/sgml/ref/psql-ref.sgml
ref/psql-ref.sgml の15.4対応です。
と言っても、差分は大きいように見えたのですが、実態は移動であり（マージの段階で対応されていました）、唯一あった変更も
none of -> neither of
であり、「いずれも〜ない」という既存の訳で対応できると考えたので、結果的に訳には影響がありませんでした。
=> update psql-ref for 15.4

doc/src/sgml/pgcrypto.sgml
pgcrypto.sgml の16.0対応です。
機械翻訳のところを書き換えているように見えますが、実際は15.4のものに戻しただけです。（原文の変更がI can showからcan be shownという訳に影響しないものでしたので。）
=> update pgcrypto for 16.0

doc/src/sgml/ref/pg_waldump.sgml
ref/pg_waldump.sgml の 16.0 対応です。
=> update pg_waldump for 16.0

doc/src/sgml/rules.sgml
=> update rules for 16.0

doc/src/sgml/pageinspect.sgml
=> update pageinspect for 16.0

doc/src/sgml/syntax.sgml
=> update syntax for 16.0

doc/src/sgml/config.sgml, doc/src/sgml/config2.sgml
https://github.com/pgsql-jp/jpug-doc/issues/2802
のご指摘を修正しました
=> issues 2802の対応

doc/src/sgml/config.sgml, doc/src/sgml/config0.sgml, doc/src/sgml/config2.sgml, doc/src/sgml/plpython.sgml, doc/src/sgml/ref/pg_waldump.sgml, doc/src/sgml/ref/release_savepoint.sgml, doc/src/sgml/xfunc.sgml
原文がないところに日本語翻訳を追加している箇所を
「原文」、「翻訳」の形式に修正しました。
コメント閉じタグのハイフン数を修正
原文が削られていた箇所の復活
=> 翻訳形式を統一するための修正

doc/src/sgml/func.sgml, doc/src/sgml/func1.sgml, doc/src/sgml/func2.sgml, doc/src/sgml/func3.sgml, doc/src/sgml/func4.sgml
タグの数があってなかったのでタグを補完
timestampが足りてなかったのを補完
不要な改行を削除
類似文が上にあったためにツールが上の類似文を出してしまったのが原因の修正。
→テキスト形式の演算子名をOIDに変換します。
=> func.sgmlのチェックで見つけた問題の修正です

doc/src/sgml/ref/alter_database.sgml, doc/src/sgml/ref/create_database.sgml, doc/src/sgml/ref/createdb.sgml, doc/src/sgml/ref/initdb.sgml
-  ref/alter_database.sgml
-  ref/create_database.sgml
-  ref/createdb.sgml
-  ref/initdb.sgml
=> update for 16.0 - new part 13

doc/src/sgml/config.sgml, doc/src/sgml/config1.sgml, doc/src/sgml/config3.sgml, doc/src/sgml/release-16.sgml
パブリッシャーとサブスクライバーの長音を統一。
split-config.shの実行（前回漏れがあった）。
=> commandは訳さないように修正

doc/src/sgml/config.sgml, doc/src/sgml/config0.sgml, doc/src/sgml/config1.sgml, doc/src/sgml/datatype.sgml, doc/src/sgml/jit.sgml, doc/src/sgml/pltcl.sgml, doc/src/sgml/ref/alter_collation.sgml, doc/src/sgml/ref/alter_database.sgml, doc/src/sgml/ref/alter_default_privileges.sgml, doc/src/sgml/ref/alter_table.sgml, doc/src/sgml/ref/create_aggregate.sgml, doc/src/sgml/ref/create_index.sgml, doc/src/sgml/ref/create_subscription.sgml, doc/src/sgml/ref/postgres-ref.sgml, doc/src/sgml/ref/psql-ref.sgml, doc/src/sgml/ref/select.sgml, doc/src/sgml/ref/vacuumdb.sgml, doc/src/sgml/regress.sgml, doc/src/sgml/runtime.sgml, doc/src/sgml/spgist.sgml, doc/src/sgml/storage.sgml
. #2845の対応です。
タイトルの統一とインデントの統一を含みます。
=> 翻訳の分割単位を厳格化

doc/src/sgml/ref/alter_table.sgml, doc/src/sgml/ref/create_table.sgml
- ref/alter_table.sgml
- ref/create_table.sgml
=> update *_table for 16.0

doc/src/sgml/Makefile
git 2.43からgit grep -f のパスがトップから現在のパスに変更されたため、
.ng.listが見つからずにエラーになっていました。
それより古いgitバージョンと非互換対応のため、
シンボリックリンクを作成するようにしました。
=> make check-ngのパス変更対応の修正

doc/src/sgml/func.sgml, doc/src/sgml/func3.sgml
indextrmが追加されたときに近いところに同一行が追加されるため
diffが中身のみになってしまうのを防ぐためにインデントを変更しました。
ここだけ連続しているので、diffが以下のように`</indexterm>`始まりの追加のようになってしまってしまいます。
これが解析の妨げになっているので変更させてください。
```diff
<indexterm zone="functions-json">
<primary>JSON</primary>
<secondary>functions and operators</secondary>
+  </indexterm>
+  <indexterm zone="functions-json">
+   <primary>JSON</primary>
+   <secondary>関数と演算子</secondary>
</indexterm>
<indexterm zone="functions-json">
<primary>SQL/JSON</primary>
<secondary>functions and expressions</secondary>
</indexterm>
+  <indexterm zone="functions-json">
+   <primary>SQL/JSON</primary>
+   <secondary>関数と式</secondary>
+  </indexterm>
```
=> indextermのインデントを変更

doc/src/sgml/wal.sgml
wal.sgml でいくつか気になった点があったので修正しました。
213-224: 主に文が途中で改行されていたのを修正。あとregainの訳もより原文に忠実にしています。
1114: こちらが気になったところで上のは実は副産物です。
●バッテリー・バックアップ -> バッテリバックアップ
「・」は不要だろう、と思ったのですが、同じファイル内で「バッテリバックアップ」としていたのでそちらに揃えました。
●RAIDアレー -> RAIDアレイ
Googleで""で括って検索すると100倍「RAIDアレイ」が多いです。
=> fix typos in wal

src/backend/catalog/sql_features.txt.ja, src/backend/utils/errcodes.txt.ja
copartitionだったのでパーティションと区別するため。
Copyrightの年の更新漏れを修正。
=> copartitionの訳見直し

doc/src/sgml/runtime.sgml
ファイアーウォール -> ファイアウォール
Googleさん今回は検索数を表示してくれませんでしたが、Geminiさんに尋ねたところ
> 「ファイアウォール」の方が一般的によく使われています。
>
> インターネット上での検索結果や、書籍、論文などを調べたところ、「ファイアウォール」が約2倍、「ファイアーウォール」が約1倍という結果が出ています。
>
>    「ファイアウォール」：約6億件
>    「ファイアーウォール」：約3億件
とのことでした。PostgreSQL文書中では他にはlibpqの一箇所しかなくて、そちらはファイアウォールでした。
=> fix "firewall"

doc/src/sgml/syntax.sgml
=> update syntax for 16.3

doc/src/sgml/xoper.sgml
「交代演算子」を「交換演算子」と訳しているところを見つけました。
誤字の指摘としては以上なのですが、もやもやしているのでここで吐き出しておきます。
●「交代演算子」
一般的な言葉ではないと思いますが、以下で定義しているようですから、よし、とすべきなのだと思います。
https://www.postgresql.jp/document/16/html/xoper-optimization.html#XOPER-COMMUTATOR
●「交換演算子」
exchange operator の訳語として物理の界隈で使われている言葉です。なので、もし使うのであればPostgreSQLとしては〜な意味で使うという説明が必要でしょう。
●commutator
「交代演算子」と訳している単語です。数学的には「交換子」という訳があるようです。ただ、交換子というと https://www.postgresql.jp/document/16/html/xoper-optimization.html#XOPER-COMMUTATOR にある定義とは異なり（そこにある定義の記号を使って書くなら）「 (x A y) - (y A x)」のことを言います。
=> fix traslation of 'commutator'

doc/src/sgml/datetime.sgml
ユリウス日は本文では訳されていますが、タイトルが訳されていませんでした。
=> ユリウス日のタイトル翻訳

doc/src/sgml/pgcrypto.sgml
pgcrypto.sgml の 16.3 対応です。
差分がたくさんあるように見えたのですが、参考資料の削除がほとんどでした、、、
=> update pgcrypto for 16.3

doc/src/sgml/indices.sgml
indices.sgml の 16.3 です。
他の人に以下のコメントに気付け、というのも酷なので自分でやってしまいました。
https://github.com/pgsql-jp/jpug-doc/pull/2929#issuecomment-2133765694
=> update indices for 16.3

doc/src/sgml/protocol.sgml
`Boolean option`をどのように訳すのかで迷いました。
file-fdw.sgmlには以下のような記載がありますが、9年前のcommitなので現在も参考にしてよいのか分かりませんでした。
```
これはbooleanオプションです。
```
とりあえず「ブールオプション」と翻訳しています。
=> protocol.sgmlの16.3対応です

doc/src/sgml/information_schema.sgml
information_schema.sgml の 16.3 対応です。
character repertoireの訳は「文字レパートリ（ー）」とすべきなのでは、という議論がありましたが、今回はそこには手をつけていません。
=> update information_schema for 16.3

doc/src/sgml/ref/create_table.sgml
timestamp,など一部の要素型では、
と見えますので、「,」を削除しました。
=> remove extra ","

doc/src/sgml/user-manag.sgml
=> update user-manag for 16.3

doc/src/sgml/ecpg.sgml
「デスクリプタ」が使われているのが1箇所のみで「ディスクリプタ」にしようかと思いましたが、
他では「SQL記述子」だったので統一しました。
=> SQL descriptorをSQL記述子に統一

doc/src/sgml/config.sgml, doc/src/sgml/config3.sgml, doc/src/sgml/ddl.sgml, doc/src/sgml/event-trigger.sgml, doc/src/sgml/func.sgml, doc/src/sgml/func2.sgml, doc/src/sgml/mvcc.sgml, doc/src/sgml/parallel.sgml, doc/src/sgml/protocol.sgml, doc/src/sgml/ref/alter_table.sgml, doc/src/sgml/ref/create_table.sgml, doc/src/sgml/spgist.sgml
discusedでマニュアルを指している場合等は「説明」に変更しました。
#2984 の対応です。
=> discussedの訳語を「説明」に変更

doc/src/sgml/advanced.sgml, doc/src/sgml/datatype.sgml, doc/src/sgml/ref/create_domain.sgml, doc/src/sgml/ref/delete.sgml, doc/src/sgml/ref/update.sgml
=> sub-SELECTを副SELECTにする

doc/src/sgml/file-fdw.sgml
boolean optionの訳をprotocol.sgmlに合わせました。
https://github.com/pgsql-jp/jpug-doc/pull/2966#issuecomment-2228467870 で書いた件です。
=> match translation of 'boolean option' with one in protocol

doc/src/sgml/archive-modules.sgml, doc/src/sgml/backup.sgml
「アーカイブ・モジュール」など「アーカイブ」の前後に「・」があるものについて、「・」を削除しました。
例えば「アーカイブ・モジュール」だと「アーカイブモジュール」と「・」がない方が多数派でしたので。
=> remove 'nakaten' around 'archive'

doc/src/sgml/logicaldecoding.sgml
streaming replicationの訳が「ストリームレプリケーション」になっていたので、「ストリーミングレプリケーション」に修正しました。
「ストリームレプリケーション」というのは他には見当たらないですし、原文も"streaming"なので原文に忠実な「ストリーミング」で良いと思うのですが、もし意図的に「ストリーム」としているのならご指摘ください。
=> fix translation of 'streaming replication'

doc/src/sgml/isn.sgml
元の訳は流石に、ねぇ。
（直後に記号が書いてあるので誤解は生じないとは思いますが、、、、）
=> fix translation of 'exclamation mark'

doc/src/sgml/func.sgml, doc/src/sgml/func3.sgml, doc/src/sgml/ref/ecpg-ref.sgml
question markの訳が
- クェスチョンマーク
- クエスチョンマーク
でぶれていたのですが、「疑問符」にすれば問題解決！ということで。
ecpg.sgmlでも「疑問符」としているので整合性は取れていると思います。
=> fix translation of 'question mark'

doc/src/sgml/func.sgml, doc/src/sgml/func1.sgml, doc/src/sgml/func3.sgml, doc/src/sgml/func4.sgml
func.sgmlではサーチパスは修正箇所だけで他は検索パスでした。
boundは後述と書いてありましたが、後述では「バウンド」と訳していました。
third argumentは別の箇所にありますが、修正箇所にはありませんでした。
=> 更新されてなかった訳の修正

doc/src/sgml/bgworker.sgml, doc/src/sgml/docguide.sgml, doc/src/sgml/monitoring.sgml
=> マッチ度文と機械翻訳文の追加

doc/src/sgml/oid2name.sgml, doc/src/sgml/ref/clusterdb.sgml, doc/src/sgml/ref/createdb.sgml, doc/src/sgml/ref/createuser.sgml, doc/src/sgml/ref/dropdb.sgml, doc/src/sgml/ref/dropuser.sgml, doc/src/sgml/ref/initdb.sgml, doc/src/sgml/ref/pg_basebackup.sgml, doc/src/sgml/ref/pg_checksums.sgml, doc/src/sgml/ref/pg_controldata.sgml, doc/src/sgml/ref/pg_dump.sgml, doc/src/sgml/ref/pg_dumpall.sgml, doc/src/sgml/ref/pg_isready.sgml, doc/src/sgml/ref/pg_receivewal.sgml, doc/src/sgml/ref/pg_recvlogical.sgml, doc/src/sgml/ref/pg_resetwal.sgml, doc/src/sgml/ref/pg_restore.sgml, doc/src/sgml/ref/pg_rewind.sgml, doc/src/sgml/ref/pg_waldump.sgml, doc/src/sgml/ref/pgarchivecleanup.sgml, doc/src/sgml/ref/pgbench.sgml, doc/src/sgml/ref/pgtestfsync.sgml, doc/src/sgml/ref/psql-ref.sgml, doc/src/sgml/ref/reindexdb.sgml, doc/src/sgml/ref/vacuumdb.sgml, doc/src/sgml/vacuumlo.sgml
段落の文の共通化で関連している文を共通化しました。
. #2983の出し直しです。
uses the environment variables と
also uses the environment variables の文があったため、
「も」と「を」を変えるだけで共通化しました。
The environment variable <envar>PG_COLOR</envar>が入る文と入らない文で、 その後共通の文があったため、共通化しました。
=> 段落の文の共通化（１）

doc/src/sgml/config.sgml, doc/src/sgml/config1.sgml, doc/src/sgml/logicaldecoding.sgml
consumersの訳にコンシューマとコンシューマーが一つづつありましたが、他は「消費者」だったので統一しました。
=> consumerの訳を消費者に統一

src/backend/catalog/sql_features.txt.ja, src/backend/utils/errcodes.txt.ja
以下のファイルの 17.0対応です。
- src/backend/catalog/sql_features.txt.ja
- src/backend/utils/errcodes.txt.ja
sql_features.txt.jaですが、YES/NOについては対応済みだったので、それ以外の部分の対応です。
=> update for 17.0 - part 2

doc/src/sgml/config.sgml, doc/src/sgml/config0.sgml, doc/src/sgml/config1.sgml, doc/src/sgml/config2.sgml, doc/src/sgml/config3.sgml, doc/src/sgml/pgstatstatements.sgml, doc/src/sgml/plperl.sgml, doc/src/sgml/sepgsql.sgml
fileの訳でファイルが入っていない #3123 関連で、共通化の修正が関連しているため、
This parameter can only be set in the
<filename>postgresql.conf</filename> file or on the server command line. の入っている文を共通化しました。
関連して、改行の関係で修正する必要があったため、
but the setting can be overridden for
individual tables by changing table storage parameters. の入っている文も共通化しました。
また、一箇所重複していた文を削除しました。
=> 段落の文の共通化（４）

doc/src/sgml/ref/create_subscription.sgml
以下の文章の`failover`の語訳に少し迷いました。
> To initiate replication, you must manually create the replication slot, enable
> the failover if required, enable the subscription, and refresh the subscription.
ここで言及しているのは、サーバを切り替える行為ではなく、新たに追加されたスロットおよびサブスクリプションオプションに関してです。
そのため「フェイルオーバーオプション」と訳しています。
=> Translate create_subscription.sgml for PG17

doc/src/sgml/datetime.sgml
datetime.sgml の 17.0 対応です。
が、マッチ度をとっただけです。（原文では the が追加されただけのため。）
=> update datetime for 17.0

doc/src/sgml/config.sgml, doc/src/sgml/config1.sgml
wal_writer_delay と wal_writer_flush_after の説明に一部誤りがある（または誤読の可能性がある）ように見受けられたので PR いたしました。
現状は「最後のフラッシュが wal_writer_delay 未満に行われ、かつ wal_writer_flush_after 相当の出力がある場合はフラッシュされない」という説明に読めますが、wal_writer_flush_after 相当の出力がある（つまり wal_writer_flush_after を越えるような出力がある）場合はフラッシュされると認識しております。
README にもそのような説明がございました。
https://github.com/postgres/postgres/blob/master/src/backend/access/transam/README#L804-L806
```
If more than wal_writer_delay has
passed, or more than wal_writer_flush_after blocks have been written, since
the last flush, WAL is also flushed up to the current location.
```
=> wal_writer_delay と wal_writer_flush_after の説明を修正

doc/src/sgml/config.sgml, doc/src/sgml/config1.sgml
doc_ja_16の内容で上書きされてしまうのでdoc_ja_16にバックポート
=>  #3147のバックポート

doc/src/sgml/dfunc.sgml
dfunc.sgml の 17.0 対応です。
FreeBSD13.0（というか14も含めて最近のFreeBSD）での標準Cコンパイラはclangで、3.0当時はgccだったのは確実です。なので変更前も変更後も間違ったことは書いてません。が、その間があるよね。標準Cコンパイラは確かかなり以前に切り替わっているよね、と思いました。独り言です。
あと、FreeBSDでは今でも追加でgccを（パッケージから）インストールして使うことは可能です。これも独り言です。
=> update dfunc for 17.0

doc/src/sgml/func.sgml, doc/src/sgml/func2.sgml
バージョン16で奇妙な訳を見つけました。
時刻with time zone
型ではないので、"with time zone"も訳すべきかと。（英語では強調はwithだけですが、直前では時間帯まで含めて強調していますので、そちらに合わせました。）
判断するためのデータがないので
原文はdataではなくdateなので、「日付が指定されないので」だと思います。（日付が指定されないので、夏時間かそうでないか判断するためのデータがない、ということなのかもしれませんが、意訳しすぎかと。）
=> fix typos in AT TIME ZONE

doc/src/sgml/high-availability.sgml
はじめてのPRです。対応漏れや不足がありましたらご指摘いただければと思います、よろしくお願いします。
「これらの方法の欠点は、しばしば必要以上のWALセグメントを保持することで、これらに対してレプリケーションスロットは必要とされる数のセグメントしか保持しません。」
英語では1センテンスでしたが、日本語では2つに分けた方がわかりやすいかもしれません。原本をふまえ1センテンスで書いています。
「ロジカルレプリケーションスロット」とするか、「論理レプリケーションスロット」とするかで悩みましたが、多くの文言が「論理レプリケーション」としていたためこちらを採用しています。
`pg_statio_` という書き方は原本を踏襲しています。 `pg_statio_*` とした方がわかりやすいかもしれませんが好みの範疇と思いました。
=> high-availability.sgmlのPostgreSQL 17.0対応

doc/src/sgml/datatype.sgml
変更箇所はリンクの更新だけでしたが、同行の既存訳も少し修正しています。
=> datatype.sgml の17.0対応

doc/src/sgml/amcheck.sgml
差分の以外に「子／親関係に渡る不変量」を「子／親関係にわたる不変量」とした。
（漢字で書くなら「亘る」）
=> amcheck.sgml の日本語訳の PG17 対応

doc/src/sgml/fdwhandler.sgml, doc/src/sgml/glossary.sgml, doc/src/sgml/information_schema.sgml, doc/src/sgml/perform.sgml, doc/src/sgml/ref/create_publication.sgml
テーブルが抜けている箇所の修正。
information_schema.sgmlは記述を統一するように見直しました。
=> tableに対してテーブルが入っていないところの見直し

doc/src/sgml/ref/pg_rewind.sgml
pg_rewind.sgmlのPostgreSQL17対応です。
差分となっていた翻訳対象が、下記の翻訳済みの「--sync-method=method」と同様の内容でしたので合わせています。
https://pgsql-jp.github.io/current/html/app-pgchecksums.html
=> Update pg_rewind.sgml for v17

doc/src/sgml/planstats.sgml
以下のファイルの 17.0 対応です。
- planstats.sgml
<details><summary>Details</summary>
<p>
英語版のv16とv17の差分です。
```diff
~/ghq/github.com/kkato/jpug-doc/doc/src/sgml % git diff REL_16_4 REL_17_0 planstats.sgml
diff --git a/doc/src/sgml/planstats.sgml b/doc/src/sgml/planstats.sgml
index d2b84b301f5..c7ec749d0a6 100644
--- a/doc/src/sgml/planstats.sgml
+++ b/doc/src/sgml/planstats.sgml
@@ -30,8 +30,6 @@
<para>
The examples shown below use tables in the <productname>PostgreSQL</productname>
regression test database.
-   The outputs shown are taken from version 8.3.
-   The behavior of earlier (or later) versions might vary.
Note also that since <command>ANALYZE</command> uses random sampling
while producing statistics, the results will change slightly after
any new <command>ANALYZE</command>.
@@ -391,18 …
```
=> Update planstats.sgml for v17

doc/src/sgml/ddl.sgml
https://github.com/pgsql-jp/jpug-doc/pull/3194
でディスカッションしないままマージしてしまいました。
「行うことができます、」のところは日本語としては「。」が良いですが、原文の「,」に合わせるとこうなりますが
日本語としておかしい気がするので
「これらの操作は全てコマンドを使用して行うことができ、そのリファレンスページにはここで説明している内容以上の詳細が記載されています。」
くらいにするのはどうでしょうか。
@noborus さん、見ていただけると助かります。
=> sgmlの翻訳改善（PR3194で改善し損ねたコメントの反映）

doc/src/sgml/ref/create_index.sgml
ref/create_index.sgml の 17.0 対応です。
=> update create_index for 17.0

doc/src/sgml/release-17.sgml
現在、半分近くの進捗ですが、量が多くてレビューにも時間がかかるので、現時点でプルリクエストを出します。翻訳は継続して進めていきます。
=> Update for release-17

doc/src/sgml/ref/pg_resetwal.sgml
翻訳時に気になった・迷ったところのメモ
「See Below」は「後述」としました。「下記参照」といった書き方も見られましたが補足的に使う場合は「後述」が多そうだったため。
「otherwise sound database cluster」は、「正常であり他に問題がない」という意味合いであるという認識で「正常なデータベースクラスタ」としました。
「dangerous modes」は、後述するforceオプションやXIDを手動設定するオプションを利用するケースを指している認識です。意味合いとしては「危険なオプション」となるのかなと思いましたが、そのまま「危険なモード」としました。
「read/write」は「読み取り/書き込み」としました。
=> pg_resetwal.sgmlのPostgreSQL17.0対応

doc/src/sgml/func.sgml, doc/src/sgml/func3.sgml, doc/src/sgml/func4.sgml
(see note)は<note>を指していて、これはDocBookで注記となるため、そうしました。
「参照ください」は、語尾の統一のために「参照してください」としました。
=> see noteの訳抜けを修正

doc/src/sgml/ltree.sgml
=> update ltree for 17.0

doc/src/sgml/features.sgml
features.sgml の 17.0 対応です。
それ以外にもcontentをcontextと間違えて訳していた部分を修正しています。
実はどちらも同じものを指しているはずなので、揃えられるなら揃えた方がいいとは思ってます。
コンテントとカタカナにするのも一理あるとは思いますが、JISでは「（XML）内容」とやっているようですし、、、
=> update features for 17.0

doc/src/sgml/datatype.sgml, doc/src/sgml/datetime.sgml, doc/src/sgml/ddl.sgml, doc/src/sgml/high-availability.sgml, doc/src/sgml/libpq.sgml, doc/src/sgml/libpq0.sgml, doc/src/sgml/libpq2.sgml, doc/src/sgml/libpq3.sgml
複数の`<entry>`をまとめて日本語訳を付けていたのを分割しました。
#3244 の対応です。
split-libpq.shの掛け漏れを実行してます。
=> <entry>の分割（3）

doc/src/sgml/indexam.sgml
もともとは「インデックスアクセスメソッド」と翻訳されていた箇所に、原文でacronymタグが追加されていたため、「インデックス<acronym>AM</acronym>」としました。
acronymタグ自体が最近のHTMLでは廃止されているという情報もみかけましたが現時点では原文に合わせています。
=> indexam.sgmlのPostgreSQL17.0対応

doc/src/sgml/plpgsql.sgml
https://github.com/pgsql-jp/jpug-doc/pull/3284/files
の査読中に気になるところを見つけtので別PRをあげました。
①「今や」は不要かと思います。
② fully evaluatedは「完全に評価されます」となっていましたが、カーソルの行ごとではなく、カーゾル「全体が評価されます」ということかと思いますのでそのように修正してみました。
=> plpgsqlの翻訳改善

doc/src/sgml/postgres.sgml
ドキュメントをシンプルにすることが目的で、多くの細かな表現の修正がありました。
https://github.com/pgsql-jp/jpug-doc/commit/322f55bdbd018bf18a0c5605c7bc592c625dc263
1点、悩んでいるのが、以下の文章で、set up が provision になっています。
(16)
Those who set up and manage their own server should also read <xref linkend="admin"/>.
また、サーバをセットアップおよび管理される方は、<xref linkend="admin"/>も参照してください。
(17)
Those who provision and manage their own PostgreSQL installation should also read <xref linkend="admin"/>.
また、PostgreSQLの導入を準備、提供、管理される方は、<xref linkend="admin"/>も参照してください。
上記のようにしましたが、provision をどう表現するのが一番正しいのかは難しいです。
=> postgres.sgmlのファイルをPG17向けに翻訳

doc/src/sgml/config.sgml, doc/src/sgml/config1.sgml, doc/src/sgml/wal.sgml
#3238 の対応でtitleのフォワードポートが漏れていました。
=> 先行書き込みログの修正漏れ（title）

doc/src/sgml/func.sgml, doc/src/sgml/func3.sgml
functionタグとreplaceableタグの中まで訳してしまっているところを見つけました。
=> fix overtranslation

doc/src/sgml/datatype.sgml
前からliteralタグが足りなくてチェックに引っかかっていたので修正
=> （<literal>00:00</literal>）の厳密性を追加

doc/src/sgml/jpug-doc.sgml
貢献者のページがPDFだとページ送りがうまくいっていなかったので、
リリースノートと同じsimplelistにしました。
=> 貢献者の形式をリリースノートに合わせる

doc/src/sgml/amcheck.sgml, doc/src/sgml/dml.sgml, doc/src/sgml/fdwhandler.sgml, doc/src/sgml/logical-replication.sgml, doc/src/sgml/ref/alter_table.sgml, doc/src/sgml/ref/merge.sgml
#3297 の対応です。
基本的に
source -> 元となる
target -> 対象
としています。
ただし、"~ source"でひとまとまりっぽいものはそのままです。（"data source"だけだったかな）
=> fix translation of 'source' and 'target'

doc/src/sgml/func.sgml, doc/src/sgml/func4.sgml
「pg_monitorロールの権限を持つロール」と「pg_monitorロールのメンバ」
が使い分けされていますが、ここだけ訳文が違いました。
=> pg_monitorロールのメンバの統一

doc/src/sgml/func.sgml, doc/src/sgml/func4.sgml, doc/src/sgml/monitoring.sgml
以下の文を共通化しました。
This function is restricted to superusers by default, but other users can be granted EXECUTE to run the function.
デフォルトではこの関数の実行はスーパーユーザに限定されますが、
他のユーザにも関数を実行するEXECUTE権限を与えることができます。
This function is restricted to superusers and roles with privileges of the <literal>pg_monitor</literal> role by default, but other users can be granted EXECUTE to run the function.
デフォルトではこの関数の実行はスーパーユーザと
<literal>pg_monitor</literal>ロールの権限を持つロールに限定されますが、 他のユーザに関数を実行するEXECUTE権限を与えることができます。
This function is restricted to superusers and members of the <literal>pg_monitor</literal> role by default, but other users can be granted EXECUTE to run the function.
デフォルトではこの関数の実行はスーパーユーザと
<literal>pg_monitor</literal>ロールのメンバに限定されますが、
他のユーザに関数を実行するEXECUTE権限を与えることができます。
#2910 の対応です。
=> 段落の文の共通化（EXECUTE権限）

doc/src/sgml/contrib.sgml, doc/src/sgml/external-projects.sgml, doc/src/sgml/spgist.sgml, doc/src/sgml/storage.sgml
「core <productname>PostgreSQL</productname> distribution」を 「<productname>PostgreSQL</productname>のコア配布物」に統一します。
=> <productname>PostgreSQL</productname>のコア配布物に統一

doc/src/sgml/ref/psql-ref.sgml
contextの訳を揃えました。
ここだけ「コンテクスト」になってました。（このファイルの中だけでも他は「コンテキスト」です。）
=> fix translation of "context"

doc/src/sgml/protocol.sgml
原文で怪しそうなところを見つけました、
streamingはパラメータ名、parallelはその値なので、どちらも<literal>タグで修飾すべきかも？
```
The LSN of the abort operation, present only when streaming is set to parallel.
This field is available since protocol version 4.
```
=> translate protocol.sgml

doc/src/sgml/bki.sgml, doc/src/sgml/charset.sgml, doc/src/sgml/config.sgml, doc/src/sgml/config3.sgml, doc/src/sgml/datatype.sgml, doc/src/sgml/extend.sgml, doc/src/sgml/func.sgml, doc/src/sgml/information_schema.sgml, doc/src/sgml/ref/create_conversion.sgml, doc/src/sgml/ref/create_database.sgml, doc/src/sgml/ref/createdb.sgml, doc/src/sgml/ref/grant.sgml, doc/src/sgml/ref/initdb.sgml, doc/src/sgml/ref/pg_dump.sgml, doc/src/sgml/ref/pg_dumpall.sgml, doc/src/sgml/ref/psql-ref.sgml, doc/src/sgml/ref/show.sgml, doc/src/sgml/runtime.sgml, doc/src/sgml/syntax.sgml
「character set」→「文字集合」
「character repertoire」→「文字レパートリ」
に変更。
#3425 で修正してしまったのを再修正で、 #2830 の対応です。
=> character set、character repertoireの訳語変更

doc/src/sgml/syntax.sgml
=> syntax.sgmlの18.0対応です。
